-- Verified curriculum seed: ZIMSEC Form 5 Economics
-- Generated by adapting the merged CAMB A-Level template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 5 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 5', 'Economics', $topics$
[
  {
    "name": "AS: Basic Economic Ideas and Resource Allocation",
    "subtopics": [
      "Scarcity, choice and opportunity cost",
      "Positive and normative statements",
      "Factors of production and specialisation",
      "Production possibility curves",
      "Economic systems: market, planned, mixed",
      "The margin and rational decision making"
    ],
    "learning_objectives": [
      "Apply opportunity cost and the margin to decisions",
      "Distinguish positive from normative economics",
      "Analyse PPC shapes, shifts and points",
      "Compare resource allocation across economic systems"
    ],
    "key_concepts": [
      "Increasing opportunity cost and the bowed PPC",
      "Marginal analysis foundations",
      "Division of labour productivity effects",
      "Transition economies",
      "Value judgements in policy debate"
    ],
    "assessment_objectives": [
      "Explain foundational concepts precisely",
      "Apply concepts to described choices",
      "Evaluate statements distinguishing fact from value",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Explain, with a diagram, the opportunity cost of the government's choice",
      "Distinguish between positive and normative statements in the extract",
      "Assess the advantages of a mixed economic system for the country described",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "IGCSE/O Level Economics helpful but not required"
    ],
    "common_misconceptions": [
      "Confusing movements along the PPC with shifts of it",
      "Treating money cost as identical to opportunity cost",
      "Believing planned economies eliminate scarcity",
      "Classifying testable claims as normative because they sound evaluative"
    ],
    "exemplar_question_stems": [
      "Using a PPC diagram, explain the effect of the natural disaster on the economy's productive capacity",
      "Assess whether the statement in the extract is positive or normative and explain the significance of the distinction"
    ]
  },
  {
    "name": "AS: The Price System and the Microeconomy",
    "subtopics": [
      "Demand and supply analysis with shifts",
      "Elasticities: PED, YED, XED, PES with calculations",
      "Consumer and producer surplus",
      "Interaction of markets and joint/derived demand",
      "Price mechanism functions",
      "Applications: taxes and subsidies incidence"
    ],
    "learning_objectives": [
      "Analyse markets rigorously with demand-supply diagrams",
      "Calculate and interpret all four elasticity types",
      "Analyse surplus changes from market events",
      "Determine tax and subsidy incidence using elasticity"
    ],
    "key_concepts": [
      "Normal vs inferior goods via YED",
      "Substitutes and complements via XED",
      "Elasticity determinants and time horizon",
      "Deadweight loss introduction",
      "Incidence dependent on relative elasticities"
    ],
    "assessment_objectives": [
      "Construct accurate diagrams with correct labelling",
      "Perform elasticity calculations and interpret signs",
      "Analyse welfare effects of market changes",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Calculate the XED between the two goods and interpret the result",
      "Analyse, with a diagram, the effect of the indirect tax on consumers and producers",
      "Explain how the surplus areas change following the price control",
      "Assess the usefulness of elasticity estimates to the firm described",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "AS basic ideas strand"
    ],
    "common_misconceptions": [
      "Dropping the sign of YED and XED and losing the classification information",
      "Believing sellers can always pass a tax fully to consumers",
      "Shifting demand when the good's own price changes",
      "Treating elasticity as constant along a linear demand curve"
    ],
    "exemplar_question_stems": [
      "The government imposes a specific tax on the good with inelastic demand; analyse who bears most of the burden",
      "Income rises by 5 percent and demand for the good falls by 2 percent; calculate YED and classify the good"
    ]
  },
  {
    "name": "AS: Government Microeconomic Intervention",
    "subtopics": [
      "Reasons for intervention: market failure introduction",
      "Maximum and minimum prices",
      "Taxes and subsidies as corrective tools",
      "Transfer payments and direct provision",
      "Nationalisation and privatisation",
      "Effectiveness of intervention"
    ],
    "learning_objectives": [
      "Analyse price control effects with diagrams including shortages and surpluses",
      "Evaluate corrective taxes and subsidies against alternatives",
      "Discuss direct provision and transfer payment rationales",
      "Assess privatisation and nationalisation arguments"
    ],
    "key_concepts": [
      "Binding vs non-binding price controls",
      "Black market emergence",
      "Specific vs ad valorem taxes",
      "Government failure introduction",
      "Equity vs efficiency tension"
    ],
    "assessment_objectives": [
      "Analyse interventions with rigorous diagrams",
      "Evaluate intervention effectiveness with criteria",
      "Consider unintended consequences systematically",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Analyse, with a diagram, the effects of the minimum price on the market",
      "Assess whether a subsidy is the best way to increase consumption of the service",
      "Evaluate the case for privatising the industry described in the extract",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "AS price system strand"
    ],
    "common_misconceptions": [
      "Drawing maximum prices above equilibrium and expecting effects",
      "Assuming subsidies always reach intended beneficiaries fully",
      "Treating privatisation as guaranteeing efficiency without competition",
      "Ignoring enforcement costs in evaluating controls"
    ],
    "exemplar_question_stems": [
      "The government sets a maximum rent below equilibrium; analyse the consequences for the housing market",
      "Evaluate whether direct provision or subsidies would better increase access to the merit good described"
    ]
  },
  {
    "name": "AS: The Macroeconomy — AD/AS, Inflation, Balance of Payments and Exchange Rates",
    "subtopics": [
      "Aggregate demand and its components",
      "Aggregate supply: short run and long run",
      "AD/AS equilibrium and shocks",
      "Inflation: measurement, causes, consequences",
      "Balance of payments structure and disequilibrium",
      "Exchange rate determination and effects",
      "The multiplier concept"
    ],
    "learning_objectives": [
      "Analyse macroeconomic shocks using AD/AS diagrams",
      "Explain demand-pull and cost-push inflation with the framework",
      "Interpret balance of payments accounts and imbalances",
      "Analyse exchange rate changes and their macro effects",
      "Apply the multiplier to spending changes"
    ],
    "key_concepts": [
      "Components: C + I + G + (X - M)",
      "Keynesian vs classical LRAS shapes",
      "Wage-price spiral",
      "Current, capital and financial accounts",
      "Marshall-Lerner condition awareness and J-curve",
      "Multiplier = 1/(1-MPC) in closed simple form"
    ],
    "assessment_objectives": [
      "Construct and interpret AD/AS diagrams accurately",
      "Analyse open-economy linkages",
      "Evaluate the significance of imbalances and inflation",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Analyse, using an AD/AS diagram, the effect of the oil price rise on the economy",
      "Explain the likely causes of the inflation described in the data",
      "Assess the consequences of the current account deficit for the economy",
      "Analyse how the currency depreciation affects the macroeconomy over time",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "AS microeconomic strands"
    ],
    "common_misconceptions": [
      "Treating a current account deficit as identical to government debt",
      "Assuming depreciation improves the trade balance immediately (ignoring the J-curve)",
      "Confusing shifts of AD with movements along it",
      "Believing inflation affects everyone equally"
    ],
    "exemplar_question_stems": [
      "Using AD/AS analysis, assess the likely effects of the investment boom on output and the price level",
      "The currency has depreciated 20 percent; analyse the effects on inflation and the current account over the short and medium term"
    ]
  },
  {
    "name": "AS: Macroeconomic Policy and Performance",
    "subtopics": [
      "Policy objectives: growth, price stability, employment, external balance",
      "Fiscal policy: instruments and the budget",
      "Monetary policy: interest rates and money supply",
      "Supply-side policy tools",
      "Policy conflicts and trade-offs",
      "Evaluating policy effectiveness"
    ],
    "learning_objectives": [
      "Analyse how each policy type transmits to the macroeconomy",
      "Match policies to described macroeconomic problems",
      "Evaluate policy effectiveness including lags and constraints",
      "Discuss conflicts such as inflation vs unemployment in the short run"
    ],
    "key_concepts": [
      "Expansionary vs contractionary stances",
      "Automatic stabilisers vs discretionary policy",
      "Interest rate transmission mechanism",
      "Market-based vs interventionist supply-side tools",
      "Time lags: recognition, implementation, effect"
    ],
    "assessment_objectives": [
      "Analyse policy transmission with diagrams",
      "Evaluate policy suitability for specific problems",
      "Weigh short-run vs long-run effects",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Analyse how a cut in interest rates might affect aggregate demand",
      "Assess which policy would best address the stagflation described",
      "Evaluate the view that supply-side policy is the only route to sustained growth",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "AS macroeconomy strand"
    ],
    "common_misconceptions": [
      "Assuming fiscal and monetary policy work with the same speed and precision",
      "Believing supply-side policies deliver quick results",
      "Treating all unemployment as curable by demand stimulus",
      "Ignoring exchange rate side effects of interest rate changes"
    ],
    "exemplar_question_stems": [
      "The economy faces rising inflation with slowing growth; evaluate the policy options available",
      "Assess the effectiveness of fiscal policy in stimulating the economy described in the extract"
    ]
  },
  {
    "name": "A2: The Microeconomy — Utility, Costs, Market Structures and Labour Markets",
    "subtopics": [
      "Utility theory and indifference curve analysis",
      "Production and cost theory: short and long run",
      "Perfect competition, monopoly, monopolistic competition, oligopoly",
      "Price discrimination and its conditions",
      "Game theory basics and interdependence",
      "Labour market: wage determination, MRP theory, unions, monopsony"
    ],
    "learning_objectives": [
      "Apply utility and indifference analysis to consumer choice",
      "Derive and interpret cost curves and returns to scale",
      "Compare equilibria and efficiency across market structures",
      "Analyse oligopoly behaviour including kinked demand and simple games",
      "Apply MRP theory and analyse union and monopsony effects on wages"
    ],
    "key_concepts": [
      "Equi-marginal principle",
      "Income and substitution effects",
      "Economies of scale and the LRAC envelope",
      "Allocative and productive efficiency benchmarks",
      "Prisoner's dilemma in pricing",
      "Wage differentials and imperfect labour markets"
    ],
    "assessment_objectives": [
      "Analyse advanced micro theory with precise diagrams",
      "Compare market structures against efficiency criteria",
      "Evaluate real-market behaviour using theory",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Using indifference curves, analyse the effect of the price fall on the consumer's choice",
      "Compare the long-run equilibrium of perfect competition and monopoly",
      "Assess whether the oligopoly described is likely to compete on price",
      "Analyse, using MRP theory, why the occupation's wage has risen",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "AS micro strands"
    ],
    "common_misconceptions": [
      "Confusing diminishing returns (short run) with diseconomies of scale (long run)",
      "Assuming monopoly always earns supernormal profit regardless of demand",
      "Treating price discrimination as always harming all consumers",
      "Believing unions always raise unemployment in all labour market structures"
    ],
    "exemplar_question_stems": [
      "Analyse why firms in monopolistic competition earn only normal profit in the long run",
      "In the monopsony labour market described, assess the effect of introducing a minimum wage"
    ]
  },
  {
    "name": "A2: Government Microeconomic Intervention — Market Failure, Equity and Policy",
    "subtopics": [
      "Externalities in depth: MSC/MSB analysis and deadweight loss",
      "Public, merit and demerit goods rigorously defined",
      "Information failure and asymmetric information",
      "Cost-benefit analysis",
      "Policies: taxation, permits, regulation, nudges, provision",
      "Income and wealth distribution: measurement and redistribution policies",
      "Poverty: absolute, relative, and policy responses"
    ],
    "learning_objectives": [
      "Analyse externalities with marginal social cost and benefit diagrams",
      "Evaluate corrective policies including tradable permits",
      "Apply cost-benefit analysis and discuss its limitations",
      "Analyse Gini coefficients and Lorenz curves",
      "Evaluate redistribution tools: progressive taxes, transfers, minimum wages"
    ],
    "key_concepts": [
      "Marginal external cost and the socially optimal output",
      "Property rights and Coase-style reasoning at concept level",
      "Moral hazard and adverse selection",
      "Shadow pricing in CBA",
      "Lorenz curve and Gini interpretation",
      "Universal vs means-tested benefits"
    ],
    "assessment_objectives": [
      "Analyse failures and remedies with advanced diagrams",
      "Evaluate policy packages against efficiency and equity",
      "Interpret distribution data accurately",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Using an MSC/MSB diagram, analyse the market failure and the effect of the corrective tax",
      "Assess the usefulness of cost-benefit analysis for the infrastructure project described",
      "The Gini coefficient rose over the decade; analyse possible causes and evaluate policy responses",
      "Evaluate tradable permits against regulation for reducing the pollution described",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "AS intervention strand",
      "A2 micro strand"
    ],
    "common_misconceptions": [
      "Aiming for zero externality rather than the socially optimal level",
      "Reading the Gini coefficient as a poverty measure rather than inequality",
      "Treating CBA monetisation of intangibles as precise",
      "Assuming information failures can always be fixed by providing information"
    ],
    "exemplar_question_stems": [
      "Analyse, with a diagram, why the free market overproduces the good with negative externalities, and evaluate two corrective policies",
      "Assess the extent to which a more progressive income tax would reduce the inequality shown in the data"
    ]
  },
  {
    "name": "A2: The Macroeconomy and Policy — Growth, Employment, Money and International Economics",
    "subtopics": [
      "Economic growth: actual vs potential, sustainability",
      "National income statistics and living standards comparison",
      "Employment dynamics: types of unemployment and the natural rate",
      "Money and banking: credit creation, central banks, interest rate theory",
      "The Phillips curve: short and long run",
      "Inflation theory: quantity theory and expectations",
      "Trade theory: comparative advantage, terms of trade, protectionism",
      "Exchange rate systems and international policy coordination",
      "Development economics: characteristics, constraints and strategies"
    ],
    "learning_objectives": [
      "Analyse growth using AD/AS and production function reasoning",
      "Evaluate national income comparisons across countries and time",
      "Analyse unemployment-inflation trade-offs with Phillips curve framework",
      "Explain credit creation and monetary transmission in depth",
      "Apply comparative advantage numerically and evaluate protectionism",
      "Compare fixed, managed and floating exchange rate systems",
      "Evaluate development strategies for low-income economies"
    ],
    "key_concepts": [
      "Output gaps",
      "Purchasing power parity adjustment",
      "Expectations-augmented Phillips curve",
      "Quantity theory MV = PT and its critiques",
      "Terms of trade calculation and significance",
      "Trade creation vs diversion in blocs",
      "Harrod-Domar and dual-sector ideas at awareness level"
    ],
    "assessment_objectives": [
      "Analyse advanced macro theory rigorously",
      "Interpret macroeconomic and development data",
      "Evaluate policy and strategy with sustained judgement",
      "Form 5 (Lower Sixth) depth: first year of the A-Level course — AS-labelled strands are the primary focus; A2-labelled strands are introduced only where they scaffold later work."
    ],
    "typical_question_styles": [
      "Assess whether the fall in unemployment must lead to rising inflation",
      "Using comparative advantage, analyse whether the two countries gain from trade",
      "Evaluate the choice of exchange rate system for the economy described",
      "Assess the most effective strategies for promoting development in the country described",
      "AS-level structured and essay questions, appropriate to Form 5"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "AS macro strands",
      "A2 micro strand"
    ],
    "common_misconceptions": [
      "Treating GDP per head growth as synonymous with development",
      "Reading the short-run Phillips curve as a permanent menu of choices",
      "Assuming comparative advantage patterns are static forever",
      "Believing floating exchange rates remove all external constraints on policy"
    ],
    "exemplar_question_stems": [
      "The data show growth with rising inequality and pollution; assess whether living standards have improved",
      "Evaluate the view that protectionism can never benefit a developing economy"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
