-- Verified curriculum seed: CAMB Grade 9 Economics
-- Generated by adapting the merged IGCSE template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 9 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('CAMB', 'Grade 9', 'Economics', $topics$
[
  {
    "name": "The Basic Economic Problem",
    "subtopics": [
      "Scarcity, choice and opportunity cost",
      "Factors of production and their rewards",
      "Economic agents: households, firms, government",
      "Production possibility curves",
      "Movements along and shifts of the PPC",
      "Resource allocation questions: what, how, for whom"
    ],
    "learning_objectives": [
      "Explain scarcity as the fundamental economic problem",
      "Apply opportunity cost to decisions by consumers, firms and governments",
      "Draw and interpret production possibility curves",
      "Classify resources into the four factors of production"
    ],
    "key_concepts": [
      "Finite resources vs unlimited wants",
      "Opportunity cost as next best alternative forgone",
      "Land, labour, capital, enterprise and their rewards",
      "Efficiency points on the PPC vs unattainable and inefficient points",
      "Economic growth as an outward PPC shift"
    ],
    "assessment_objectives": [
      "Define and explain core concepts accurately",
      "Apply concepts to real-world decisions",
      "Interpret and draw PPC diagrams",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Define opportunity cost and give an example from the extract",
      "Draw a PPC and show the effect of the described change",
      "Explain why the point inside the curve represents inefficiency",
      "Identify the factor of production described and its reward",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "None — foundation strand"
    ],
    "common_misconceptions": [
      "Confusing money cost with opportunity cost",
      "Believing scarcity only affects poor countries",
      "Treating any point outside the PPC as achievable with effort",
      "Confusing capital (man-made resources) with money"
    ],
    "exemplar_question_stems": [
      "Using an example from the extract, explain the opportunity cost of the government's decision",
      "Draw a production possibility curve to show the effect of an improvement in technology in one industry"
    ]
  },
  {
    "name": "The Allocation of Resources: Demand, Supply and Markets",
    "subtopics": [
      "Demand curves and shifts",
      "Supply curves and shifts",
      "Market equilibrium and disequilibrium",
      "Price elasticity of demand and supply",
      "Calculation and interpretation of PED and PES",
      "Market economic system and the price mechanism"
    ],
    "learning_objectives": [
      "Draw accurate demand and supply diagrams showing shifts and new equilibria",
      "Distinguish movements along curves from shifts of curves",
      "Calculate PED and PES and interpret the values",
      "Explain how the price mechanism allocates resources"
    ],
    "key_concepts": [
      "Determinants of demand and supply",
      "Excess demand and excess supply adjustment",
      "Elastic vs inelastic ranges and total revenue effects",
      "Determinants of elasticity",
      "Rationing, signalling and incentive functions of price"
    ],
    "assessment_objectives": [
      "Analyse markets using accurate diagrams",
      "Calculate elasticity values from data",
      "Evaluate the significance of elasticity for firms and government",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Draw a diagram to show the effect of the described event on the market",
      "Calculate the PED from the data and comment on the result",
      "Analyse how the price mechanism reallocates resources after the change described",
      "Discuss whether the firm should raise its price given the elasticity estimate",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Basic economic problem strand"
    ],
    "common_misconceptions": [
      "Shifting the demand curve when price itself changes",
      "Ignoring the minus sign convention and misreading PED strength",
      "Believing higher price always raises revenue regardless of elasticity",
      "Reversing the axes or labelling of supply and demand diagrams"
    ],
    "exemplar_question_stems": [
      "The price falls by 10 percent and quantity demanded rises by 25 percent; calculate PED and interpret it",
      "Using a demand and supply diagram, analyse the effect of the subsidy on the market for the product"
    ]
  },
  {
    "name": "Market Failure and Government Intervention",
    "subtopics": [
      "Private vs social costs and benefits",
      "External costs and external benefits",
      "Merit, demerit and public goods",
      "Government policies: taxes, subsidies, regulation, price controls",
      "Maximum and minimum prices",
      "Evaluating intervention: effectiveness and unintended consequences"
    ],
    "learning_objectives": [
      "Explain market failure using externalities and missing markets",
      "Distinguish public goods from private goods using rivalry and excludability",
      "Analyse policy tools with diagrams where appropriate",
      "Evaluate the effectiveness of intervention including drawbacks"
    ],
    "key_concepts": [
      "Social cost = private cost + external cost",
      "Free-rider problem",
      "Overconsumption of demerit goods and underconsumption of merit goods",
      "Indirect taxation and subsidy incidence",
      "Black markets from price ceilings"
    ],
    "assessment_objectives": [
      "Explain causes of market failure clearly",
      "Apply intervention tools to case-study markets",
      "Evaluate policies with balanced judgement",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Explain why the product described is a demerit good",
      "Analyse how a subsidy could correct the market failure identified",
      "Discuss whether a maximum price would benefit consumers of the product",
      "Explain the difference between public and private goods with examples",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Demand and supply strand"
    ],
    "common_misconceptions": [
      "Calling any government-provided good a public good",
      "Assuming taxes eliminate rather than reduce consumption of demerit goods",
      "Ignoring enforcement costs and black markets when evaluating price controls",
      "Confusing external costs (to third parties) with high private costs"
    ],
    "exemplar_question_stems": [
      "Explain two external costs created by the factory described in the extract",
      "Discuss whether government regulation is the best way to reduce consumption of the demerit good"
    ]
  },
  {
    "name": "Microeconomic Decision Makers: Money, Households and Workers",
    "subtopics": [
      "Functions and characteristics of money",
      "Central banks and commercial banks",
      "Households: spending, saving and borrowing influences",
      "Workers: wage determination and wage differentials",
      "Specialisation and division of labour",
      "Trade unions and their effects"
    ],
    "learning_objectives": [
      "Explain the functions of money and the role of banks",
      "Analyse influences on household spending, saving and borrowing",
      "Explain wage determination using demand and supply of labour",
      "Discuss reasons for wage differentials and the role of trade unions"
    ],
    "key_concepts": [
      "Medium of exchange, store of value, unit of account, standard of deferred payment",
      "Central bank functions vs commercial bank functions",
      "Income, interest rates and confidence as spending influences",
      "Derived demand for labour",
      "Collective bargaining, strikes and productivity agreements"
    ],
    "assessment_objectives": [
      "Explain institutional roles accurately",
      "Analyse labour market outcomes with demand and supply",
      "Evaluate the effects of union activity on stakeholders",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Explain two functions of money shown in the extract",
      "Analyse why the occupation described earns more than the other",
      "Discuss whether an increase in interest rates will reduce household spending",
      "Analyse the effects of the union's wage claim on the firm and its workers",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Demand and supply strand"
    ],
    "common_misconceptions": [
      "Confusing the central bank with commercial banks",
      "Believing all wage differences are unfair rather than partly reflecting skill scarcity",
      "Assuming higher wages always reduce employment regardless of productivity",
      "Treating saving as always good and borrowing as always bad"
    ],
    "exemplar_question_stems": [
      "Using the extract, explain how the central bank's action affects commercial bank lending",
      "Analyse two reasons why surgeons earn more than cleaners"
    ]
  },
  {
    "name": "Microeconomic Decision Makers: Firms, Costs and Market Structure",
    "subtopics": [
      "Classification of firms: size, sector, ownership",
      "Small firms and reasons for their survival",
      "Growth of firms: internal and external, mergers",
      "Costs: fixed, variable, total, average",
      "Revenue and profit calculation",
      "Economies and diseconomies of scale",
      "Competition vs monopoly"
    ],
    "learning_objectives": [
      "Calculate and interpret costs, revenue and profit from data",
      "Explain economies of scale and their limits",
      "Analyse motives for and effects of mergers",
      "Compare competitive markets with monopoly outcomes"
    ],
    "key_concepts": [
      "Fixed vs variable cost behaviour",
      "Average cost falling with internal economies",
      "Horizontal, vertical and conglomerate integration",
      "Barriers to entry",
      "Profit maximisation and alternative objectives"
    ],
    "assessment_objectives": [
      "Perform cost and profit calculations accurately",
      "Analyse firm growth and scale effects",
      "Evaluate market structures for consumers and producers",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Calculate total cost, average cost and profit from the table",
      "Explain two economies of scale the firm could gain",
      "Analyse the possible effects of the merger described on consumers",
      "Discuss whether monopoly is always against consumer interest",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Markets strand"
    ],
    "common_misconceptions": [
      "Treating fixed costs as never changing in the long run",
      "Assuming bigger firms always have lower average costs, ignoring diseconomies",
      "Believing profit equals revenue",
      "Assuming all monopolies charge the highest possible price without constraint"
    ],
    "exemplar_question_stems": [
      "From the data, calculate the firm's average cost at each output and identify where economies of scale end",
      "Discuss whether the takeover of the supplier will benefit the firm's customers"
    ]
  },
  {
    "name": "Government Macroeconomic Objectives and Policies",
    "subtopics": [
      "Macroeconomic aims: growth, low unemployment, price stability, balance of payments stability, redistribution",
      "Fiscal policy: taxation and government spending",
      "Monetary policy: interest rates and money supply",
      "Supply-side policy",
      "Conflicts between objectives",
      "Types and canons of taxation"
    ],
    "learning_objectives": [
      "Explain each macroeconomic objective and how it is measured",
      "Analyse how fiscal, monetary and supply-side tools work",
      "Evaluate policy choices for given economic problems",
      "Discuss conflicts such as growth vs inflation"
    ],
    "key_concepts": [
      "Progressive, regressive and proportional taxes",
      "Direct vs indirect taxation",
      "Budget deficit and surplus",
      "Transmission of interest rate changes",
      "Time lags and policy limitations"
    ],
    "assessment_objectives": [
      "Explain policy instruments and their mechanisms",
      "Apply policies to described macroeconomic problems",
      "Evaluate effectiveness including conflicts and side effects",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Explain how a cut in interest rates might increase output",
      "Analyse how the tax change described will affect low-income households",
      "Discuss which policy would best reduce the unemployment described",
      "Explain the difference between fiscal and monetary policy",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Microeconomic strands"
    ],
    "common_misconceptions": [
      "Confusing the government budget deficit with the trade deficit",
      "Believing supply-side policies work as quickly as demand-side policies",
      "Assuming higher taxes always raise more revenue",
      "Treating low inflation as identical to falling prices"
    ],
    "exemplar_question_stems": [
      "Analyse how increased government spending on infrastructure could achieve two macroeconomic aims",
      "Discuss whether raising interest rates is the best way to reduce the inflation described"
    ]
  },
  {
    "name": "Economic Indicators: Inflation, Unemployment and Living Standards",
    "subtopics": [
      "Measuring inflation with the CPI",
      "Causes: demand-pull and cost-push inflation",
      "Consequences of inflation and deflation",
      "Measuring unemployment and its types",
      "Causes and consequences of unemployment",
      "GDP, real GDP and the economic cycle",
      "Living standards: GDP per head, HDI and their limitations"
    ],
    "learning_objectives": [
      "Explain how the CPI is constructed and interpret index numbers",
      "Distinguish causes of inflation and analyse remedies",
      "Classify unemployment as frictional, structural or cyclical",
      "Evaluate GDP and HDI as measures of living standards"
    ],
    "key_concepts": [
      "Weighted basket and base year",
      "Real vs nominal values",
      "Full employment vs zero unemployment",
      "Recession as falling real GDP",
      "Income distribution masked by averages"
    ],
    "assessment_objectives": [
      "Interpret and calculate index and percentage changes",
      "Analyse causes and consequences of indicator movements",
      "Evaluate measures of economic wellbeing",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Calculate the inflation rate from the index numbers provided",
      "Explain whether the inflation described is demand-pull or cost-push",
      "Analyse two consequences of the rise in unemployment for the economy",
      "Discuss whether a rise in GDP means living standards have improved",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Macroeconomic policy strand"
    ],
    "common_misconceptions": [
      "Believing falling inflation means falling prices",
      "Treating GDP per head as capturing income distribution",
      "Assuming all unemployment is caused by laziness or lack of jobs alone",
      "Confusing the price level with the inflation rate"
    ],
    "exemplar_question_stems": [
      "The CPI rose from 120 to 126; calculate the inflation rate and interpret it",
      "Discuss whether HDI is a better measure of living standards than GDP per head"
    ]
  },
  {
    "name": "International Trade, Development and Globalisation",
    "subtopics": [
      "Specialisation and trade between countries",
      "Free trade benefits and protectionism: tariffs, quotas, subsidies, embargoes",
      "Exchange rates: determination, appreciation and depreciation",
      "Balance of payments current account",
      "Differences in economic development between countries",
      "Causes of poverty and policies to alleviate it",
      "Population and development indicators"
    ],
    "learning_objectives": [
      "Analyse gains from trade and arguments for protection",
      "Explain exchange rate movements using demand and supply of currency",
      "Interpret the current account and its components",
      "Discuss characteristics of developing economies and poverty-reduction policies"
    ],
    "key_concepts": [
      "Comparative advantage at an intuitive level",
      "Infant industry and anti-dumping arguments",
      "Floating exchange rates and trade effects",
      "Trade in goods vs trade in services",
      "Absolute vs relative poverty",
      "Population growth and dependency ratios"
    ],
    "assessment_objectives": [
      "Analyse trade and exchange rate changes with diagrams where relevant",
      "Interpret current account data",
      "Evaluate protectionism and development policies",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Analyse how the depreciation will affect the country's exports and imports",
      "Discuss whether the tariff will benefit the domestic economy",
      "Explain two reasons for differences in living standards between the two countries",
      "Analyse the effect of the change described on the current account balance",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Indicators strand",
      "Markets strand"
    ],
    "common_misconceptions": [
      "Believing exports are always good and imports always bad",
      "Assuming depreciation instantly improves the trade balance",
      "Confusing the balance of payments with the government budget",
      "Treating all developing countries as economically identical"
    ],
    "exemplar_question_stems": [
      "The currency depreciated by 15 percent; analyse the likely effects on the country's current account",
      "Discuss whether protectionist policies would help the developing country described in the extract"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
