-- Verified curriculum seed: IEB Grade 10 History
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 10 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('IEB', 'Grade 10', 'History', $topics$
[
  {
    "name": "The Cold War: Origins and Extension to Vietnam",
    "subtopics": [
      "The end of World War II and superpower tension",
      "Ideological rivalry: capitalism vs communism",
      "The division of Europe and Germany",
      "Containment, the Truman Doctrine and Marshall Plan",
      "Case study: Vietnam - French withdrawal and US involvement",
      "US escalation and methods of warfare in Vietnam",
      "Opposition to the war and US withdrawal"
    ],
    "learning_objectives": [
      "Explain the origins of Cold War tension between the USA and USSR",
      "Analyse the ideological differences underpinning superpower rivalry",
      "Describe the division of Germany and Europe into rival blocs",
      "Explain US containment policy and its application in Asia",
      "Analyse why the USA became involved in Vietnam and why it failed to win",
      "Evaluate the significance of the anti-war movement and the outcome of the war"
    ],
    "key_concepts": [
      "Superpower rivalry",
      "Containment",
      "Domino theory",
      "Guerrilla warfare",
      "Escalation",
      "Detente context"
    ],
    "assessment_objectives": [
      "Extract and interpret evidence from historical sources",
      "Construct coherent explanations and sustained essay arguments",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions with levelled sub-questions",
      "Paragraph questions using sources and own knowledge",
      "Discursive essay with a line of argument",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 17,
    "prerequisites": [
      "Grade 11 History skills (source analysis and essay writing)"
    ],
    "common_misconceptions": [
      "Believing the Cold War involved direct military conflict between the superpowers",
      "Assuming the USA lost every military engagement in Vietnam",
      "Confusing the causes of US involvement with the reasons for US failure",
      "Treating containment as a policy applied identically everywhere",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Explain to what extent the ideological differences between the USA and the USSR were responsible for Cold War tension by 1949. Support your line of argument with relevant evidence.",
      "Using Source 1B and your own knowledge, explain why the USA believed the domino theory justified intervention in Vietnam.",
      "Critically discuss the view that the media turned American public opinion against the Vietnam War.",
      "Compare Sources 2A and 2C on the effectiveness of US bombing campaigns. Explain how they differ and why."
    ]
  },
  {
    "name": "Independent Africa: Case Studies Congo and Tanzania",
    "subtopics": [
      "The legacy of colonialism in Africa",
      "Political challenges after independence",
      "Case study Congo: crisis, external interference, Mobutu",
      "Case study Tanzania: Nyerere, Ujamaa and African socialism",
      "Economic successes and failures of each model",
      "Social and cultural developments after independence",
      "Africa in the Cold War context: Angola case study"
    ],
    "learning_objectives": [
      "Analyse the political and economic challenges facing newly independent African states",
      "Compare the paths taken by the Congo and Tanzania after independence",
      "Explain the causes and consequences of the Congo crisis including foreign interference",
      "Evaluate the aims and outcomes of Ujamaa in Tanzania",
      "Assess the impact of Cold War rivalry on Angola's civil war",
      "Weigh internal against external factors in explaining post-independence difficulties"
    ],
    "key_concepts": [
      "Decolonisation",
      "Neo-colonialism",
      "One-party state",
      "Ujamaa and African socialism",
      "Proxy war",
      "Nation-building"
    ],
    "assessment_objectives": [
      "Analyse and compare case-study evidence",
      "Evaluate historical interpretations of Africa's post-independence experience",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions on the Congo or Angola",
      "Essay comparing leadership choices in two states",
      "Paragraph questions on Ujamaa outcomes",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "The Cold War: Origins and Extension to Vietnam"
    ],
    "common_misconceptions": [
      "Treating all newly independent African states as following one path",
      "Blaming either colonialism alone or leadership alone for post-independence problems",
      "Believing Ujamaa was imposed with no popular support at any stage",
      "Ignoring the Cold War dimension of the Angolan conflict",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Critically discuss the view that foreign interference was the main cause of instability in the Congo between 1960 and 1965.",
      "Using Source 3B and your own knowledge, explain why Nyerere introduced the policy of Ujamaa.",
      "To what extent did Cold War rivalry between the superpowers turn Angola into a battleground after 1975?",
      "Explain the usefulness of Source 3D to a historian studying the achievements of Tanzanian nation-building."
    ]
  },
  {
    "name": "Civil Society Protests: 1950s to 1970s",
    "subtopics": [
      "The US Civil Rights Movement: origins and philosophy",
      "Martin Luther King and non-violent protest",
      "Selma, Birmingham and legislative victories",
      "The Black Power movement: Malcolm X, Black Panthers",
      "Comparing civil rights and Black Power approaches",
      "The women's movement and peace movements as global context"
    ],
    "learning_objectives": [
      "Explain the conditions that gave rise to the Civil Rights Movement",
      "Analyse the philosophy and methods of non-violent direct action",
      "Assess the achievements of the Civil Rights Movement including key legislation",
      "Explain the emergence and aims of the Black Power movement",
      "Compare the strategies of Martin Luther King with those of Black Power leaders",
      "Evaluate the extent to which protest movements achieved their aims by the 1970s"
    ],
    "key_concepts": [
      "Segregation",
      "Non-violent direct action",
      "Civil disobedience",
      "Black consciousness in the US context",
      "Black Power",
      "Legislative change"
    ],
    "assessment_objectives": [
      "Interpret protest-era sources including speeches and photographs",
      "Sustain balanced essay arguments on movement effectiveness",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions on a protest campaign",
      "Essay evaluating the achievements of the Civil Rights Movement",
      "Comparison paragraph on King and Malcolm X",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "Grade 11 History skills (source analysis and essay writing)"
    ],
    "common_misconceptions": [
      "Believing the Civil Rights Movement began only with Martin Luther King",
      "Treating Black Power as purely violent and the Civil Rights Movement as purely successful",
      "Assuming legislation immediately ended discrimination in practice",
      "Reading protest photographs as neutral records rather than framed evidence",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Using Source 4A and your own knowledge, explain why the Birmingham campaign of 1963 attracted worldwide attention.",
      "Critically discuss the view that the Black Power movement undermined the achievements of the Civil Rights Movement.",
      "Compare the methods of Martin Luther King and the Black Panther Party in the struggle for African-American rights.",
      "Explain the limitations of Source 4C for a historian studying grassroots activism in the American South."
    ]
  },
  {
    "name": "Civil Resistance in South Africa 1970s-1980s",
    "subtopics": [
      "The challenge of Black Consciousness to apartheid",
      "Steve Biko and the philosophy of Black Consciousness",
      "The 1976 Soweto uprising: causes, events, consequences",
      "The crisis of apartheid in the 1980s",
      "Internal resistance: UDF, trade unions, civics",
      "Government responses: reform, repression, states of emergency",
      "International pressure: sanctions, disinvestment, sport and cultural boycotts"
    ],
    "learning_objectives": [
      "Explain the philosophy of Black Consciousness and its impact on resistance",
      "Analyse the causes and consequences of the Soweto uprising",
      "Assess the significance of Steve Biko's life and death",
      "Explain the growth of mass internal resistance in the 1980s",
      "Analyse the government's dual strategy of reform and repression",
      "Evaluate the contribution of international pressure to the crisis of apartheid"
    ],
    "key_concepts": [
      "Black Consciousness",
      "Mass mobilisation",
      "United Democratic Front",
      "States of emergency",
      "Sanctions and boycotts",
      "Total strategy"
    ],
    "assessment_objectives": [
      "Analyse South African sources in their political context",
      "Construct evidence-based arguments about resistance and repression",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions on Soweto or the 1980s crisis",
      "Essay on the role of Black Consciousness",
      "Paragraph questions on international pressure",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 17,
    "prerequisites": [
      "Grade 11 History skills (source analysis and essay writing)"
    ],
    "common_misconceptions": [
      "Reducing the Soweto uprising to a single-language grievance without its broader context",
      "Treating internal resistance and international pressure as unconnected",
      "Believing government reforms of the 1980s were intended to end apartheid",
      "Overlooking the role of workers and trade unions in resistance",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Using Source 5B and your own knowledge, explain why the ideas of Black Consciousness appealed to young South Africans in the early 1970s.",
      "Critically discuss the view that the Soweto uprising of 1976 marked a turning point in the struggle against apartheid.",
      "To what extent did international sanctions contribute to the crisis of the apartheid state in the 1980s?",
      "Compare Sources 5C and 5D on the aims of the United Democratic Front. How do they support one another?"
    ]
  },
  {
    "name": "The Coming of Democracy in South Africa",
    "subtopics": [
      "The collapse of communism and its impact on South Africa",
      "Negotiations: talks about talks, CODESA, multiparty negotiations",
      "Obstacles and violence during the transition",
      "Leadership: De Klerk, Mandela and compromise",
      "The 1994 election and Government of National Unity",
      "The Truth and Reconciliation Commission: aims, processes, responses",
      "Dealing with the past and constructing memory"
    ],
    "learning_objectives": [
      "Explain how the end of the Cold War changed the calculations of the apartheid government and liberation movements",
      "Trace the course of negotiations from 1990 to 1994",
      "Analyse the obstacles to a negotiated settlement including political violence",
      "Evaluate the roles of key leaders in achieving a settlement",
      "Explain the aims and workings of the Truth and Reconciliation Commission",
      "Critically assess responses to the TRC and debates about justice and reconciliation"
    ],
    "key_concepts": [
      "Negotiated settlement",
      "CODESA",
      "Sunset clauses",
      "Government of National Unity",
      "Truth and reconciliation",
      "Amnesty"
    ],
    "assessment_objectives": [
      "Interpret transition-era sources including negotiation records and testimony",
      "Evaluate competing interpretations of the transition and the TRC",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions on negotiations or the TRC",
      "Essay on the roles of leadership and compromise",
      "Paragraph questions on responses to the TRC",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 17,
    "prerequisites": [
      "Civil Resistance in South Africa 1970s-1980s"
    ],
    "common_misconceptions": [
      "Believing the transition was inevitable once Mandela was released",
      "Treating the negotiations as free of violence and breakdowns",
      "Assuming the TRC prosecuted perpetrators like a court",
      "Crediting the settlement to one leader alone",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Critically discuss the view that compromise by both the National Party and the ANC made the 1994 settlement possible.",
      "Using Source 6A and your own knowledge, explain why political violence threatened to derail the negotiations between 1990 and 1993.",
      "To what extent did the Truth and Reconciliation Commission achieve reconciliation in South Africa?",
      "Explain the reliability of Source 6C, an amnesty hearing transcript, for a historian studying human rights violations."
    ]
  },
  {
    "name": "The End of the Cold War and a New World Order",
    "subtopics": [
      "Gorbachev's reforms: glasnost and perestroika",
      "The collapse of the Soviet Union",
      "The end of the Cold War and its global significance",
      "A new world order: unipolarity and globalisation",
      "The changing balance of world power",
      "Impact on Africa and the developing world"
    ],
    "learning_objectives": [
      "Explain the aims and unintended consequences of Gorbachev's reforms",
      "Analyse the events leading to the disintegration of the USSR",
      "Assess the global significance of the end of the Cold War",
      "Explain features of the post-Cold War world order including globalisation",
      "Evaluate the impact of the new world order on Africa",
      "Connect the end of the Cold War to change in South Africa"
    ],
    "key_concepts": [
      "Glasnost and perestroika",
      "Collapse of communism",
      "Unipolar world",
      "Globalisation",
      "New world order",
      "Post-Cold War Africa"
    ],
    "assessment_objectives": [
      "Explain large-scale historical change using evidence",
      "Evaluate the consequences of global shifts for different regions",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Source-based questions on the collapse of the USSR",
      "Essay on the consequences of the end of the Cold War",
      "Paragraph questions linking global change to South Africa",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 17,
    "prerequisites": [
      "The Coming of Democracy in South Africa"
    ],
    "common_misconceptions": [
      "Believing Gorbachev set out to dissolve the Soviet Union",
      "Attributing the collapse of communism to a single cause",
      "Assuming globalisation benefited all regions equally",
      "Separating the end of the Cold War from developments in southern Africa",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Critically discuss the view that Gorbachev's reforms, rather than Western pressure, ended the Cold War.",
      "Using Source 7B and your own knowledge, explain why the countries of Eastern Europe broke away from Soviet control in 1989.",
      "To what extent did the end of the Cold War create opportunities for the resolution of conflicts in southern Africa?",
      "Compare the interpretations in Sources 7C and 7D of the United States' role in the post-Cold War world."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
