-- Verified curriculum seed: ZIMSEC Form 2 ICT
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 2 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 2', 'ICT', $topics$
[
  {
    "name": "ICT Systems and Devices",
    "subtopics": [
      "Components of an ICT system: hardware, software, data, people, procedures",
      "Categories of computers: desktop, laptop, tablet, smartphone, embedded systems",
      "Input devices and their uses",
      "Output devices and their uses",
      "Storage devices and media",
      "Selecting appropriate devices for tasks",
      "Basic care and maintenance of equipment"
    ],
    "learning_objectives": [
      "Identify the five components of an ICT system and how they interact",
      "Match categories of computing devices to suitable users and tasks",
      "Select appropriate input devices including scanners, sensors and touch screens for given situations",
      "Select appropriate output devices including printers, speakers and projectors",
      "Compare storage options for capacity, portability, speed and cost",
      "Describe routine care that prolongs the life of ICT equipment"
    ],
    "key_concepts": [
      "ICT system components",
      "Device categories",
      "Input and output devices",
      "Storage media",
      "Fitness for purpose",
      "Equipment care"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of ICT hardware and its uses",
      "Apply device knowledge to select tools for real tasks",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Identify-the-device questions from descriptions or pictures",
      "Scenario questions recommending equipment for a user",
      "Comparison questions on storage media",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Foundational literacy and numeracy from earlier grades"
    ],
    "common_misconceptions": [
      "Treating hardware and software as interchangeable terms",
      "Believing more expensive always means more suitable",
      "Confusing storage capacity units (MB, GB, TB)",
      "Ignoring people and procedures as parts of an ICT system"
    ],
    "exemplar_question_stems": [
      "A rural clinic needs a device to record patients' temperatures automatically into a computer. Name a suitable input device and justify your choice.",
      "State two factors a student should consider when choosing between a laptop and a tablet for schoolwork.",
      "Name the output device most suitable for showing a presentation to a full school hall, and give one reason.",
      "List the five components of an ICT system and give an example of each in a school library system."
    ]
  },
  {
    "name": "Word Processing and Desktop Publishing",
    "subtopics": [
      "Creating, editing and saving documents",
      "Text formatting: fonts, styles, alignment",
      "Page layout: margins, columns, headers and footers",
      "Tables, images and text wrapping",
      "Mail merge",
      "Proofing tools: spell check, find and replace",
      "Desktop publishing: flyers, newsletters, posters",
      "Print options and document sharing"
    ],
    "learning_objectives": [
      "Create and format documents using appropriate styles and layout",
      "Insert and position tables, images and shapes with correct text wrapping",
      "Set up headers, footers and page numbering",
      "Perform a mail merge from a data source to personalised letters",
      "Use proofing tools to improve accuracy",
      "Design publications combining text and graphics for a target audience",
      "Choose appropriate print settings and export formats"
    ],
    "key_concepts": [
      "Formatting",
      "Page layout",
      "Mail merge",
      "Proofing",
      "Publication design",
      "Export formats"
    ],
    "assessment_objectives": [
      "Produce well-formatted documents to a given specification",
      "Apply document tools efficiently in practical tasks",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Practical task producing a formatted document from instructions",
      "Theory questions naming features and their uses",
      "Design question producing a flyer or newsletter to a brief",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "ICT Systems and Devices"
    ],
    "common_misconceptions": [
      "Using spaces and blank lines instead of tabs, indents and spacing settings",
      "Believing spell check catches every error including wrong-word errors",
      "Confusing 'save' with 'save as'",
      "Cropping an image when resizing was intended"
    ],
    "exemplar_question_stems": [
      "Describe the steps to carry out a mail merge that sends the same invitation letter to 50 parents whose details are stored in a spreadsheet.",
      "State two advantages of using styles rather than formatting each heading manually.",
      "You are asked to design an A5 flyer advertising a school fun run. List four design decisions you would make and justify each.",
      "Explain why a spell checker did not detect the error in the sentence: 'The principle will address the assembly.'"
    ]
  },
  {
    "name": "Spreadsheets",
    "subtopics": [
      "Workbook, worksheet, cells and ranges",
      "Data entry and cell formatting",
      "Formulas: arithmetic operations and cell references",
      "Relative vs absolute cell references",
      "Functions: SUM, AVERAGE, MAX, MIN, COUNT, IF",
      "Sorting and filtering data",
      "Charts: column, line, pie",
      "Simple modelling and what-if analysis"
    ],
    "learning_objectives": [
      "Enter and format data appropriately including currency and percentages",
      "Construct formulas using correct operators and cell references",
      "Apply absolute references where copying formulas requires them",
      "Use common functions including a simple IF condition",
      "Sort and filter data to answer questions",
      "Create and label appropriate charts for given data",
      "Use a spreadsheet model to answer what-if questions"
    ],
    "key_concepts": [
      "Cell referencing",
      "Formulas and functions",
      "Absolute vs relative references",
      "Sorting and filtering",
      "Charting",
      "What-if modelling"
    ],
    "assessment_objectives": [
      "Build accurate spreadsheet solutions to given problems",
      "Interpret and present spreadsheet results appropriately",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Write-the-formula questions for given cells",
      "Practical task building a marks or budget spreadsheet",
      "Chart selection and interpretation questions",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "ICT Systems and Devices"
    ],
    "common_misconceptions": [
      "Typing calculated values instead of formulas",
      "Forgetting the equals sign at the start of a formula",
      "Using relative references where absolute references are required",
      "Choosing a pie chart for data that does not represent parts of a whole"
    ],
    "exemplar_question_stems": [
      "Cell B10 must show the total of cells B2 to B9. Write the formula you would enter.",
      "The VAT rate is stored in cell E1. Write a formula for cell C2 that calculates VAT on the amount in B2 so that it can be copied down the column correctly.",
      "A teacher's spreadsheet shows marks for 40 learners. Describe how to display only learners who scored below 50.",
      "Write an IF function for cell D2 that displays 'PASS' if the mark in C2 is 50 or more, and 'FAIL' otherwise."
    ]
  },
  {
    "name": "Databases and Presentations",
    "subtopics": [
      "Database structure: tables, records, fields",
      "Data types and field properties",
      "Primary keys",
      "Creating and running queries with criteria",
      "Forms for data entry and reports for output",
      "Presentation software: slides, layouts, master slides",
      "Multimedia elements: images, audio, video, transitions, animations",
      "Delivering effective presentations"
    ],
    "learning_objectives": [
      "Design a single-table database with appropriate fields, types and a primary key",
      "Enter and edit records using a form",
      "Construct queries using comparison and logical criteria",
      "Produce reports that present selected data clearly",
      "Create presentations using consistent layouts and master slides",
      "Use multimedia and animation purposefully without overloading slides",
      "Apply good practice when presenting to an audience"
    ],
    "key_concepts": [
      "Records and fields",
      "Data types",
      "Queries and criteria",
      "Forms and reports",
      "Slide design",
      "Multimedia balance"
    ],
    "assessment_objectives": [
      "Create working database and presentation solutions to a brief",
      "Apply design principles for clarity and audience impact",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Design-a-table question for a given scenario",
      "Write-the-query-criteria question",
      "Practical presentation task with design requirements",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Spreadsheets"
    ],
    "common_misconceptions": [
      "Storing ages instead of dates of birth so data goes out of date",
      "Using the wrong data type, such as text for quantities to be calculated",
      "Filling every slide with dense paragraphs of text",
      "Believing more animations always make a presentation better"
    ],
    "exemplar_question_stems": [
      "A sports club stores member details. Suggest five suitable fields, their data types, and identify a primary key.",
      "Write the query criteria to list all members who joined after 1 January 2024 and live in Gweru.",
      "State three features of a well-designed slide for a classroom presentation.",
      "Explain one advantage of entering data through a form rather than directly into the table."
    ]
  },
  {
    "name": "Communication Networks and Internet Services",
    "subtopics": [
      "Reasons for networking computers",
      "LANs, WANs and wireless networks",
      "Internet connection methods and requirements",
      "Web browsers and search engines",
      "Effective and safe searching for information",
      "Electronic communication: email, instant messaging, video conferencing, social media",
      "E-services: e-learning, e-banking, e-government, e-commerce",
      "Netiquette and responsible online communication"
    ],
    "learning_objectives": [
      "Explain the benefits and drawbacks of networking computers",
      "Distinguish LANs from WANs and wired from wireless connections",
      "Describe what is needed to connect to the Internet",
      "Use search engines effectively including refining search terms",
      "Evaluate the reliability of information found online",
      "Compare electronic communication methods for different purposes",
      "Describe e-services and their benefits to citizens and businesses",
      "Apply netiquette rules in online communication"
    ],
    "key_concepts": [
      "Networking benefits",
      "LAN vs WAN",
      "Internet access",
      "Search strategies",
      "Information reliability",
      "E-communication",
      "E-services",
      "Netiquette"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of networks and Internet services",
      "Apply safe and effective online practices",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Scenario questions choosing a communication method",
      "Short-answer questions on Internet requirements",
      "Discussion questions on e-services benefits and challenges",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "ICT Systems and Devices"
    ],
    "common_misconceptions": [
      "Believing everything published online is accurate",
      "Confusing a web browser with a search engine",
      "Assuming email attachments are always safe to open",
      "Thinking e-commerce only means large international websites"
    ],
    "exemplar_question_stems": [
      "A business owner in Mutare needs face-to-face discussion with a supplier in Harare without travelling. Recommend a communication method and state the equipment required.",
      "State three things a student should check before trusting information found on a website.",
      "Explain the difference between a web browser and a search engine, giving one example of each.",
      "Describe two benefits of e-banking to a customer who lives far from town."
    ]
  },
  {
    "name": "Systems Analysis and Development Basics",
    "subtopics": [
      "Stages of the system development life cycle",
      "Problem identification and feasibility",
      "Investigation methods: interviews, questionnaires, observation, record inspection",
      "Design: input forms, output layouts, file structures",
      "Implementation and changeover methods: direct, parallel, phased, pilot",
      "Testing systems",
      "Documentation: user and technical",
      "Evaluation and maintenance"
    ],
    "learning_objectives": [
      "List the stages of the system development life cycle in order",
      "Compare methods of investigating an existing system",
      "Produce simple designs for inputs, outputs and data storage",
      "Compare changeover methods and recommend one for a given situation",
      "Explain the purpose of testing before full use",
      "Distinguish user documentation from technical documentation",
      "Explain why systems are evaluated and maintained after implementation"
    ],
    "key_concepts": [
      "System life cycle",
      "Fact-finding methods",
      "Design artefacts",
      "Changeover strategies",
      "Testing",
      "Documentation",
      "Maintenance"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of how ICT systems are developed",
      "Apply life-cycle concepts to a scenario-based development task",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Order-the-stages questions",
      "Scenario question recommending an investigation or changeover method",
      "Design question sketching an input screen or report layout",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Databases and Presentations"
    ],
    "common_misconceptions": [
      "Believing development ends at implementation",
      "Confusing parallel running with phased changeover",
      "Assuming interviews are always the best fact-finding method",
      "Writing user documentation full of technical jargon"
    ],
    "exemplar_question_stems": [
      "A school is replacing its manual attendance register with a computerised system. Recommend a changeover method and justify your choice.",
      "State two advantages of using questionnaires rather than interviews when investigating a system used by 300 workers.",
      "Design a simple input screen for capturing a new learner's enrolment details.",
      "Explain the difference between user documentation and technical documentation, stating who uses each."
    ]
  },
  {
    "name": "Safety, Security and ICT in Society",
    "subtopics": [
      "Physical safety and ergonomics in the computer room",
      "Health issues: eyesight, posture, repetitive strain",
      "Data security: passwords, access rights, backups, antivirus",
      "Online safety: cyberbullying, strangers, oversharing",
      "Malware and phishing awareness",
      "Copyright, software piracy and licensing",
      "Impact of ICT on employment and daily life",
      "ICT for national development and environmental considerations"
    ],
    "learning_objectives": [
      "Apply safe working practices in a computer laboratory",
      "Describe health risks of prolonged computer use and their prevention",
      "Recommend measures to protect data against loss and unauthorised access",
      "Identify online risks and describe responsible responses",
      "Recognise phishing attempts and malware warning signs",
      "Explain copyright rules and the consequences of software piracy",
      "Discuss positive and negative effects of ICT on jobs and communities",
      "Describe how ICT supports development and how e-waste should be handled"
    ],
    "key_concepts": [
      "Ergonomics",
      "Data security measures",
      "Online safety",
      "Phishing and malware",
      "Copyright and licensing",
      "Social impact",
      "E-waste"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of safe, secure and legal ICT use",
      "Evaluate the social and economic impact of ICT",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Scenario question on responding to an online risk",
      "List-and-explain questions on security measures",
      "Discussion question on ICT and employment",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "Communication Networks and Internet Services"
    ],
    "common_misconceptions": [
      "Believing antivirus software makes other precautions unnecessary",
      "Thinking copying licensed software for a friend is legal if no money changes hands",
      "Assuming cyberbullying should be handled by replying angrily",
      "Treating old computers as ordinary rubbish"
    ],
    "exemplar_question_stems": [
      "A learner receives a message asking for their password to 'verify' their account. State what the learner should do and name this type of attack.",
      "Describe three measures a school should take to protect learner records stored on its computers.",
      "Discuss one positive and one negative effect of ICT on employment in the banking sector.",
      "State two ways of disposing of old computers responsibly."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
