-- Verified curriculum seed: ZIMSEC Form 6 Business Studies
-- Generated by adapting the merged CAMB A-Level template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 6 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 6', 'Business Studies', $topics$
[
  {
    "name": "AS: Business and Its Environment",
    "subtopics": [
      "Enterprise and the nature of business activity",
      "Business structures: sole traders to public limited companies",
      "Size of business and measurement",
      "Business objectives and stakeholder interests",
      "External influences: economic, legal, social, technological",
      "Business ethics introduction"
    ],
    "learning_objectives": [
      "Compare legal structures and recommend forms for scenarios",
      "Analyse conflicts between stakeholder objectives",
      "Assess the impact of external environment changes on businesses",
      "Evaluate objectives beyond profit including social enterprise aims"
    ],
    "key_concepts": [
      "Limited vs unlimited liability",
      "Divorce of ownership and control",
      "SMART objectives and objective hierarchies",
      "Stakeholder mapping",
      "Opportunity cost in enterprise decisions"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of business concepts and terms",
      "Apply concepts to unfamiliar business contexts",
      "Analyse and evaluate business situations and decisions",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Analyse two advantages to the business of converting to a private limited company",
      "Evaluate whether profit maximisation should be the main objective of the business described",
      "Assess the likely impact of the legal change on the business in the case",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "IGCSE/O Level Business Studies helpful but not required"
    ],
    "common_misconceptions": [
      "Believing shareholders manage public companies day to day",
      "Treating all stakeholders as having equal influence in every decision",
      "Assuming larger business size always means greater profitability",
      "Confusing revenue with profit in objective discussions"
    ],
    "exemplar_question_stems": [
      "The founder is considering converting the partnership to a private limited company before expansion; evaluate this decision",
      "Assess the extent to which the interests of shareholders and employees conflict in the case described"
    ]
  },
  {
    "name": "AS: People in Organisations",
    "subtopics": [
      "Management and leadership styles",
      "Motivation theories: Taylor, Maslow, Herzberg, McGregor",
      "Financial and non-financial motivators in practice",
      "Human resource management: workforce planning, recruitment, training",
      "Organisational structure: hierarchy, span, delegation, centralisation",
      "Communication in business"
    ],
    "learning_objectives": [
      "Apply motivation theory to workplace scenarios",
      "Evaluate leadership styles for described situations",
      "Analyse HRM practices and their effects on performance",
      "Assess organisational structure choices for businesses of different sizes"
    ],
    "key_concepts": [
      "Theory X and Y assumptions",
      "Hygiene factors vs motivators",
      "Delayering and its consequences",
      "On-the-job vs off-the-job training",
      "Formal vs informal communication channels"
    ],
    "assessment_objectives": [
      "Apply people-management theory to contexts",
      "Analyse effects of HR decisions on stakeholders",
      "Evaluate people strategies with justified judgement",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Analyse how the manager could use non-financial methods to motivate the staff described",
      "Evaluate whether the autocratic style is appropriate for the situation in the case",
      "Assess the likely effects of delayering on the business and its employees",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "AS environment strand"
    ],
    "common_misconceptions": [
      "Believing pay is the only effective motivator",
      "Applying one leadership style as universally best",
      "Confusing delegation (authority) with abdication (responsibility dumped)",
      "Treating motivation theories as proven laws rather than models"
    ],
    "exemplar_question_stems": [
      "Staff turnover has risen since the pay-only bonus scheme began; use motivation theory to evaluate alternative approaches",
      "Evaluate whether a wider span of control would benefit the growing business described"
    ]
  },
  {
    "name": "AS: Marketing",
    "subtopics": [
      "Markets and marketing objectives",
      "Market research: methods, sampling, reliability",
      "The marketing mix: product, price, place, promotion",
      "Product life cycle and portfolio analysis",
      "Elasticity of demand in marketing decisions",
      "Segmentation, targeting and positioning"
    ],
    "learning_objectives": [
      "Evaluate market research methods for given decisions",
      "Apply the marketing mix to build coherent strategies",
      "Use elasticity estimates in pricing decisions",
      "Recommend segmentation and positioning for described products"
    ],
    "key_concepts": [
      "Primary vs secondary research trade-offs",
      "Niche vs mass marketing",
      "Price elasticity and revenue linkage",
      "Extension strategies in the life cycle",
      "Consistency across the mix"
    ],
    "assessment_objectives": [
      "Apply marketing concepts to case contexts",
      "Analyse marketing data including elasticity",
      "Evaluate marketing strategies with recommendations",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Analyse the usefulness of the market research data collected by the business",
      "Evaluate a suitable marketing mix for the product launch described",
      "The PED estimate is given; assess whether the price rise will increase revenue",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "AS environment strand"
    ],
    "common_misconceptions": [
      "Treating promotion as the whole of marketing",
      "Ignoring sample size and bias when using research findings",
      "Assuming price cuts always raise total revenue",
      "Applying the same mix to all segments"
    ],
    "exemplar_question_stems": [
      "Evaluate whether the business should reposition its product as a premium brand",
      "Using the elasticity data, assess the proposed pricing strategy for the new market"
    ]
  },
  {
    "name": "AS: Operations and Finance Foundations",
    "subtopics": [
      "Productivity and efficiency measures",
      "Capacity utilisation",
      "Production methods: job, batch, flow, cell",
      "Inventory management including JIT introduction",
      "Business finance sources: short and long term",
      "Forecasting cash flows and working capital",
      "Budgets and simple variance awareness",
      "Income statements and balance sheet interpretation for decisions"
    ],
    "learning_objectives": [
      "Calculate and interpret productivity and capacity measures",
      "Recommend production methods for described products",
      "Prepare and analyse cash flow forecasts",
      "Select appropriate finance sources for scenarios"
    ],
    "key_concepts": [
      "Labour productivity calculation",
      "Under- vs over-utilisation costs",
      "JIT prerequisites and risks",
      "Cash vs profit distinction",
      "Matching finance duration to asset life"
    ],
    "assessment_objectives": [
      "Perform operations and finance calculations accurately",
      "Analyse operational and financial data for decisions",
      "Evaluate operations and funding choices",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Calculate the capacity utilisation and analyse the implications",
      "Prepare the cash flow forecast and identify the financing need",
      "Evaluate whether the business should adopt just-in-time inventory management",
      "Recommend suitable sources of finance for the expansion described",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Basic numeracy"
    ],
    "common_misconceptions": [
      "Confusing productivity (rate) with total production (volume)",
      "Believing 100 percent capacity utilisation is always desirable",
      "Treating a profitable business as immune to cash flow failure",
      "Choosing overdrafts to finance long-term assets"
    ],
    "exemplar_question_stems": [
      "The forecast shows a negative closing balance in two months; analyse options to manage the shortfall",
      "Evaluate whether flow production is suitable for the artisan product described"
    ]
  },
  {
    "name": "A2: Strategic Management and the Business Environment",
    "subtopics": [
      "Strategic analysis: SWOT, PEST, Porter's five forces",
      "Strategic choice: Ansoff's matrix and Porter's generic strategies",
      "Strategic implementation and corporate planning",
      "Business and globalisation: multinationals and international strategy",
      "Managing change and contingency planning",
      "Decision-making techniques: decision trees, force field analysis"
    ],
    "learning_objectives": [
      "Apply strategic frameworks to extended case material",
      "Evaluate strategic options with quantitative and qualitative evidence",
      "Analyse globalisation opportunities and threats for businesses",
      "Use decision trees and other tools to structure choices"
    ],
    "key_concepts": [
      "Strategy vs tactics",
      "Market penetration, development, product development, diversification",
      "Expected value calculations in decision trees",
      "Resistance to change and its management",
      "Core competences at concept level"
    ],
    "assessment_objectives": [
      "Analyse strategic situations using frameworks",
      "Evaluate strategic options with justified recommendation",
      "Synthesise across business functions at A2 level",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Use Ansoff's matrix to evaluate the growth options facing the business",
      "Calculate the expected values in the decision tree and recommend the option",
      "Assess the risks to the business of entering the international market described",
      "Evaluate the approach taken by management to implement the change",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "All AS strands"
    ],
    "common_misconceptions": [
      "Using frameworks descriptively without drawing strategic conclusions",
      "Reading decision tree expected values as guaranteed outcomes",
      "Treating diversification as automatically the riskiest and best-avoided option in all cases",
      "Ignoring implementation feasibility when recommending strategy"
    ],
    "exemplar_question_stems": [
      "The case business is considering diversification versus market development; evaluate both using the evidence and recommend",
      "Assess the usefulness of the five forces framework to the business analysing its new industry"
    ]
  },
  {
    "name": "A2: Advanced Marketing, Operations and Human Resources",
    "subtopics": [
      "Marketing strategy: new product development, international marketing",
      "Sales forecasting: moving averages and correlation awareness",
      "Operations strategy: capacity, location, lean production, quality",
      "Critical path analysis for project scheduling",
      "HR strategy: workforce planning, management by objectives, labour relations",
      "Organisational culture and its strategic role"
    ],
    "learning_objectives": [
      "Evaluate marketing strategies including entry into international markets",
      "Apply moving-average forecasting and interpret its limits",
      "Construct and interpret critical path networks",
      "Analyse strategic HR and culture questions in extended cases"
    ],
    "key_concepts": [
      "Standardisation vs adaptation in international marketing",
      "Seasonal variation in forecasts",
      "Earliest start and latest finish times; float",
      "Kaizen and lean principles",
      "Culture types and strategic fit"
    ],
    "assessment_objectives": [
      "Apply advanced functional techniques accurately",
      "Interpret quantitative outputs for management decisions",
      "Evaluate functional strategies within whole-business context",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Calculate the four-quarter moving average and comment on the trend",
      "Construct the network diagram, identify the critical path and the float on the named activity",
      "Evaluate whether the business should standardise or adapt its product for the new country",
      "Assess how the culture described may affect the proposed strategy",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "AS marketing, operations, people strands"
    ],
    "common_misconceptions": [
      "Extrapolating moving averages far beyond the data range",
      "Believing activities with float are on the critical path",
      "Treating lean production as simply inventory reduction",
      "Assuming culture change can be implemented as quickly as structural change"
    ],
    "exemplar_question_stems": [
      "The project network has the durations shown; calculate the critical path and assess the impact of a two-day delay in the named activity",
      "Evaluate the human resource issues raised by the proposed relocation of production"
    ]
  },
  {
    "name": "A2: Strategic Finance and Whole-Business Evaluation",
    "subtopics": [
      "Investment appraisal at strategic level: NPV, IRR, payback with qualitative factors",
      "Published accounts interpretation for strategy",
      "Ratio analysis synthesis for strategic judgement",
      "Sources of long-term finance for strategy",
      "Contingency and crisis finance",
      "Integrated case evaluation and report writing"
    ],
    "learning_objectives": [
      "Appraise strategic investments combining quantitative results with qualitative factors",
      "Interpret financial statements to judge strategic capability",
      "Recommend financing structures for major strategies",
      "Write integrated evaluations synthesising all functional areas"
    ],
    "key_concepts": [
      "Discounted cash flow logic and cost of capital",
      "Gearing constraints on strategy",
      "Quantitative-qualitative balance in judgement",
      "Shareholder vs stakeholder outcomes of strategy",
      "Report format with recommendation and justification"
    ],
    "assessment_objectives": [
      "Perform strategic financial analysis accurately",
      "Synthesise evidence across functions",
      "Evaluate and recommend with sustained justification",
      "Form 6 (Upper Sixth) depth: completion of the full A-Level course — A2-labelled strands completed and integrated with AS foundations for final examinations."
    ],
    "typical_question_styles": [
      "Using the NPV results and other evidence, recommend whether to proceed with the investment",
      "Assess the financial position of the business and its capacity to fund the strategy",
      "Write a report to the board recommending one of the two strategic options",
      "Evaluate the importance of non-financial factors in this investment decision",
      "Full A-Level structured, essay and synoptic questions"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "AS finance strand",
      "A2 strategy strand"
    ],
    "common_misconceptions": [
      "Recommending purely on NPV while ignoring risk, financing and stakeholders",
      "Treating IRR above cost of capital as sufficient without scale considerations",
      "Ignoring gearing implications of debt-funded strategies",
      "Writing unbalanced reports that evaluate only the preferred option"
    ],
    "exemplar_question_stems": [
      "Both projects have positive NPVs but different risk profiles; write a justified recommendation to the board",
      "Assess whether the business's financial position supports the acquisition strategy described in the case"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
