-- Verified curriculum seed: NSC Grade 9 Afrikaans First Additional Language
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 9 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('NSC', 'Grade 9', 'Afrikaans First Additional Language', $topics$
[
  {
    "name": "Leesbegrip (Reading Comprehension)",
    "subtopics": [
      "Literal and inferential comprehension of Afrikaans texts",
      "Vocabulary in context (woordeskat in konteks)",
      "Tone, register and the writer's intention",
      "Fact vs opinion in articles",
      "Visual texts: advertisements and photographs with captions",
      "Answering in full Afrikaans sentences"
    ],
    "learning_objectives": [
      "Retrieve explicit information from Afrikaans reading passages",
      "Infer meaning, attitude and intention from context",
      "Deduce the meaning of unfamiliar Afrikaans words from context clues",
      "Distinguish feite (facts) from menings (opinions)",
      "Interpret visual texts together with written passages",
      "Formulate grammatically correct answers in own words in Afrikaans"
    ],
    "key_concepts": [
      "Letterlike en afleidende begrip",
      "Woordeskat in konteks",
      "Toon en register",
      "Feit teenoor mening",
      "Visuele geletterdheid",
      "Eie woorde"
    ],
    "assessment_objectives": [
      "Demonstrate comprehension of written and visual Afrikaans texts",
      "Respond accurately in appropriate Afrikaans",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Short-answer comprehension questions on an unseen passage",
      "True/false with motivation (Waar/Onwaar, motiveer)",
      "Vocabulary questions asking for synonyms or explanations in context",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Graad 11 Afrikaans EAT vaardighede (Grade 11 Afrikaans FAL skills)"
    ],
    "common_misconceptions": [
      "Answering in English when Afrikaans is required",
      "Copying whole sentences instead of answering the specific question",
      "Ignoring question words like 'Waarom' (why) vs 'Hoe' (how)",
      "Translating idioms word-for-word"
    ],
    "exemplar_question_stems": [
      "Haal EEN woord uit paragraaf 2 aan wat toon dat die seun bang was. (Quote one word from paragraph 2 showing the boy was afraid.)",
      "Is die volgende stelling WAAR of ONWAAR? Motiveer jou antwoord met 'n aanhaling. (True or false? Motivate with a quotation.)",
      "Verduidelik in jou eie woorde waarom die skrywer die stad verlaat het. (Explain in your own words why the writer left the city.)",
      "Wat is die funksie van die foto saam met die artikel? (What is the function of the photo accompanying the article?)"
    ]
  },
  {
    "name": "Opsomming (Summary Writing)",
    "subtopics": [
      "Identifying seven main points from a passage",
      "Writing points in full sentences in own words",
      "Observing the word limit (about 60-70 words)",
      "Numbering points and indicating the word count",
      "Avoiding examples, repetition and direct copying"
    ],
    "learning_objectives": [
      "Select the required main points from an Afrikaans passage",
      "Rewrite points as full, grammatically correct Afrikaans sentences in own words",
      "Keep within the prescribed word limit",
      "Present the summary in the required point format with a word count",
      "Avoid lifting sentences directly from the text"
    ],
    "key_concepts": [
      "Hoofgedagtes",
      "Eie woorde",
      "Woordbeperking",
      "Puntsgewyse formaat",
      "Parafrasering"
    ],
    "assessment_objectives": [
      "Identify and reformulate essential content in correct Afrikaans",
      "Apply summary conventions accurately",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Point-form summary of seven main points within a word limit on a given aspect of a passage",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "Leesbegrip (Reading Comprehension)"
    ],
    "common_misconceptions": [
      "Copying sentences directly from the passage",
      "Writing a paragraph when points are required",
      "Exceeding the word limit",
      "Including examples as main points"
    ],
    "exemplar_question_stems": [
      "Som SEWE wenke op oor hoe om veilig op sosiale media te wees. Skryf die wenke puntsgewys in volsinne in jou eie woorde neer. Jou opsomming mag nie langer as 70 woorde wees nie. (Summarise seven tips about staying safe on social media, in point form, own words, max 70 words.)",
      "Die skrywer noem verskeie voordele van sport op skool. Som SEWE voordele puntsgewys op en dui die getal woorde aan. (Summarise seven benefits of school sport.)"
    ]
  },
  {
    "name": "Taalstrukture en -konvensies (Language Structures)",
    "subtopics": [
      "Werkwoorde en tye: verlede, teenwoordige, toekomende tyd",
      "Lydende en bedrywende vorm (passive and active voice)",
      "Direkte en indirekte rede (direct and reported speech)",
      "Ontkenning (the double negative: nie ... nie)",
      "Voorsetsels, voegwoorde en woordorde (STOMPI)",
      "Trappe van vergelyking (degrees of comparison)",
      "Meervoude, verkleinwoorde, intensiewe vorme en idiome",
      "Advertisement and cartoon language questions"
    ],
    "learning_objectives": [
      "Convert sentences correctly between tenses maintaining word order rules",
      "Transform sentences between active and passive voice",
      "Convert direct speech to indirect speech with correct pronoun and tense shifts",
      "Apply the Afrikaans double negative correctly",
      "Apply STOMPI word order in complex sentences",
      "Form plurals, diminutives, intensives and degrees of comparison correctly",
      "Interpret language use in advertisements and cartoons"
    ],
    "key_concepts": [
      "Tydsvorme",
      "Lydende vorm",
      "Indirekte rede",
      "Ontkenning",
      "STOMPI-woordorde",
      "Verbuigings",
      "Idiome"
    ],
    "assessment_objectives": [
      "Apply Afrikaans grammatical rules accurately in context",
      "Analyse language use in visual and advertising texts",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Rewrite-the-sentence transformation questions",
      "Fill in the correct form of the word in brackets",
      "Questions on an advertisement and a cartoon",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Graad 11 Afrikaans EAT vaardighede (Grade 11 Afrikaans FAL skills)"
    ],
    "common_misconceptions": [
      "Omitting the second 'nie' in negative sentences",
      "Keeping English word order after conjunctions like 'omdat'",
      "Forgetting 'het ge-' constructions in the past tense",
      "Using 'as' and 'soos' interchangeably in comparisons"
    ],
    "exemplar_question_stems": [
      "Skryf die sin in die verlede tyd: 'Die leerders skryf die eksamen in die saal.' (Rewrite in the past tense.)",
      "Skryf die sin in die ontkennende vorm: 'Thabo eet altyd sy ontbyt.' (Rewrite in the negative form.)",
      "Skryf die sin in die indirekte rede: Sannie sê: 'Ek sal môre die boek bring.' (Rewrite in reported speech.)",
      "Kyk na die advertensie en noem EEN oorredingstegniek wat gebruik word. (Name one persuasion technique used in the advertisement.)"
    ]
  },
  {
    "name": "Letterkunde: Gedigte (Poetry)",
    "subtopics": [
      "Voorgeskrewe gedigte: inhoud en tema",
      "Beeldspraak: metafoor, vergelyking, personifikasie",
      "Klankeffekte: alliterasie, assonansie, rym",
      "Stemming en toon in gedigte",
      "Strofebou en versreëls",
      "Kontekstuele vrae oor gedigte"
    ],
    "learning_objectives": [
      "Explain the content and theme of prescribed Afrikaans poems",
      "Identify and explain imagery including metaphors and similes",
      "Recognise sound devices and their effect",
      "Describe the mood and tone of a poem with evidence",
      "Comment on structure: stanzas, line length and rhyme scheme",
      "Answer contextual questions with quotation and motivation"
    ],
    "key_concepts": [
      "Tema",
      "Beeldspraak",
      "Klankeffekte",
      "Stemming en toon",
      "Strofebou",
      "Kontekstuele analise"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of prescribed poems",
      "Analyse poetic devices and their effects in Afrikaans",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Contextual questions on a prescribed poem with quotation-based answers",
      "Identify-and-explain questions on imagery and sound",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Leesbegrip (Reading Comprehension)"
    ],
    "common_misconceptions": [
      "Naming a device without explaining its effect",
      "Confusing the speaker (spreker) with the poet (digter)",
      "Translating figurative language literally",
      "Ignoring the title when interpreting the poem"
    ],
    "exemplar_question_stems": [
      "Benoem die beeldspraak in versreël 3 en verduidelik dit. (Name and explain the figure of speech in line 3.)",
      "Wat is die stemming in die laaste strofe? Motiveer jou antwoord. (What is the mood in the last stanza? Motivate.)",
      "Waarom is die titel van die gedig gepas? (Why is the title of the poem appropriate?)",
      "Haal 'n voorbeeld van alliterasie uit strofe 2 aan. (Quote an example of alliteration from stanza 2.)"
    ]
  },
  {
    "name": "Letterkunde: Roman en Drama (Novel and Drama)",
    "subtopics": [
      "Intrige en verhaalverloop (plot development)",
      "Karakters en karakterisering",
      "Ruimte en tyd (setting and time)",
      "Temas en boodskap",
      "Verteller en perspektief in die roman",
      "Dramatiese elemente: dialoog, spanning, toneelaanwysings",
      "Kontekstuele vrae oor voorgeskrewe werke"
    ],
    "learning_objectives": [
      "Trace the plot and key turning points of the prescribed novel and drama",
      "Describe main characters and their development with textual support",
      "Explain the role of setting and time in the prescribed works",
      "Discuss themes and the message of each work",
      "Answer contextual questions on extracts with quotation and motivation",
      "Comment on dramatic techniques such as tension and dialogue"
    ],
    "key_concepts": [
      "Intrige",
      "Karakterisering",
      "Ruimte",
      "Tema",
      "Verteller",
      "Dramatiese spanning"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of the prescribed novel and drama",
      "Interpret extracts and support answers from the text",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Contextual questions on an extract from the novel",
      "Contextual questions on an extract from the drama",
      "Character and theme questions with motivation",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Leesbegrip (Reading Comprehension)"
    ],
    "common_misconceptions": [
      "Retelling the whole story instead of answering the question",
      "Confusing characters with similar roles",
      "Ignoring the specific extract when answering contextual questions",
      "Giving opinions without textual motivation"
    ],
    "exemplar_question_stems": [
      "Beskryf die verhouding tussen die twee hoofkarakters aan die begin van die roman. (Describe the relationship between the two main characters at the start of the novel.)",
      "Hoe dra hierdie toneel by tot die spanning in die drama? (How does this scene contribute to the tension in the drama?)",
      "Noem TWEE karaktereienskappe van die hoofkarakter en motiveer uit die teks. (Name two character traits of the protagonist, with motivation.)",
      "Wat is die tema van die roman? Verduidelik met verwysing na die slot. (What is the theme of the novel? Explain with reference to the ending.)"
    ]
  },
  {
    "name": "Skryf: Opstel (Essay Writing)",
    "subtopics": [
      "Verhalende opstel (narrative essay)",
      "Beskrywende opstel (descriptive essay)",
      "Bespiegelende en argumenterende opstelle",
      "Beplanning en paragraafbou",
      "Woordeskat en sinsbou vir impak",
      "Redigering van eie werk"
    ],
    "learning_objectives": [
      "Plan and write a structured Afrikaans essay of the prescribed length",
      "Sustain a storyline or description with appropriate vocabulary",
      "Apply correct tense consistently throughout the essay",
      "Use connectors and varied sentence structures",
      "Edit for spelling, word order and negation errors",
      "Choose and interpret topics including picture prompts"
    ],
    "key_concepts": [
      "Opstelsoorte",
      "Beplanning",
      "Paragraafbou",
      "Tydsgebruik",
      "Sinsbou",
      "Redigering"
    ],
    "assessment_objectives": [
      "Communicate ideas in coherent written Afrikaans",
      "Apply language conventions accurately in extended writing",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Choice of essay topics including picture prompts, of prescribed length",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Taalstrukture en -konvensies (Language Structures)"
    ],
    "common_misconceptions": [
      "Thinking in English and translating literally",
      "Switching tenses mid-narrative",
      "Ignoring STOMPI word order in longer sentences",
      "Choosing a topic without enough vocabulary to sustain it"
    ],
    "exemplar_question_stems": [
      "Skryf 'n opstel met die titel: 'Die dag toe alles verander het'. (Write an essay titled 'The day everything changed'.)",
      "Skryf 'n verhalende opstel wat eindig met die woorde: '... en toe weet ek ek is veilig.' (Narrative essay ending with given words.)",
      "Kies EEN van die prente en skryf 'n opstel daaroor. Gee jou eie titel. (Choose one picture and write an essay on it.)",
      "'Selfone hoort nie in die klaskamer nie.' Skryf 'n argumenterende opstel. (Argumentative essay on cellphones in class.)"
    ]
  },
  {
    "name": "Skryf: Transaksionele Tekste (Transactional Writing)",
    "subtopics": [
      "Vriendskaplike brief (friendly letter)",
      "Formele brief (formal letter)",
      "E-pos en uitnodiging",
      "Dagboekinskrywing (diary entry)",
      "Dialoog en onderhoud",
      "Formaat, register en toon vir elke tekssoort"
    ],
    "learning_objectives": [
      "Apply the correct Afrikaans format for letters, emails and other transactional texts",
      "Match register and tone to the audience and purpose",
      "Cover all required content points in the task",
      "Write within the prescribed length",
      "Use appropriate greetings, closings and conventions in Afrikaans"
    ],
    "key_concepts": [
      "Formaat",
      "Register",
      "Aanhef en slot",
      "Inhoudspunte",
      "Lengtebeperking"
    ],
    "assessment_objectives": [
      "Produce transactional texts that meet format and content requirements",
      "Use appropriate register and correct Afrikaans conventions",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Choice of two transactional tasks with a scenario and required content",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "Skryf: Opstel (Essay Writing)"
    ],
    "common_misconceptions": [
      "Using the informal 'jy/jou' in a formal letter",
      "Omitting the address and date in letters",
      "Mixing English formats with Afrikaans conventions",
      "Ignoring the required content points in the scenario"
    ],
    "exemplar_question_stems": [
      "Skryf 'n formele brief aan die stadsraad waarin jy kla oor die stukkende straatligte in jou woonbuurt. (Formal letter of complaint about broken streetlights.)",
      "Jou vriend het 'n belangrike sportbyeenkoms gewen. Skryf 'n vriendskaplike brief om hom/haar geluk te wens. (Friendly congratulatory letter.)",
      "Skryf die dialoog tussen jou en 'n nuwe leerder wat by julle skool aansluit. (Dialogue with a new learner.)",
      "Skryf 'n dagboekinskrywing oor die aand voor jou eerste eindeksamen. (Diary entry before the first final exam.)"
    ]
  },
  {
    "name": "Mondeling en Luister (Oral and Listening)",
    "subtopics": [
      "Voorbereide toespraak (prepared speech)",
      "Onvoorbereide praatbeurte (unprepared speaking)",
      "Leesbegrip hardop: voorbereide voorlesing",
      "Luisterbegrip: instructions and passages",
      "Gesprekvoering en rolspel",
      "Uitspraak, tempo en oogkontak"
    ],
    "learning_objectives": [
      "Prepare and deliver a structured speech in Afrikaans",
      "Respond in unprepared speaking situations with reasonable fluency",
      "Read a prepared passage aloud with correct pronunciation and pacing",
      "Extract main ideas and details from spoken Afrikaans",
      "Participate in conversations and role play using appropriate register",
      "Apply presentation skills: eye contact, volume and tempo"
    ],
    "key_concepts": [
      "Voorbereide toespraak",
      "Onvoorbereide praat",
      "Voorlesing",
      "Luisterbegrip",
      "Gespreksvaardighede",
      "Aanbiedingsvaardighede"
    ],
    "assessment_objectives": [
      "Communicate orally in comprehensible, appropriate Afrikaans",
      "Demonstrate listening comprehension of spoken Afrikaans",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Prepared speech assessment on a chosen topic",
      "Listening comprehension with short-answer questions",
      "Prepared reading-aloud assessment",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 5,
    "prerequisites": [
      "Leesbegrip (Reading Comprehension)"
    ],
    "common_misconceptions": [
      "Memorising a speech without understanding it, then stalling",
      "Reading aloud in a monotone ignoring punctuation",
      "Trying to write down every word during listening tests",
      "Believing oral marks do not affect the final result"
    ],
    "exemplar_question_stems": [
      "Lewer 'n voorbereide toespraak van twee minute oor 'n persoon wat jou inspireer. (Two-minute prepared speech on someone who inspires you.)",
      "Luister na die aankondiging en beantwoord die vrae: Waar en wanneer vind die byeenkoms plaas? (Listening: where and when does the event take place?)",
      "Lees die gegewe paragraaf hardop voor met aandag aan uitspraak en leestekens. (Read the paragraph aloud attending to pronunciation and punctuation.)"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
