
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

DO $seed$
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN
    SELECT * FROM (VALUES
      ('OpenStax — Algebra & Trigonometry 2e', 'textbook', 'Mathematics', 'Algebra & Trigonometry', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE'],
       'https://openstax.org/details/books/algebra-and-trigonometry-2e',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=OpenStax%0AAlgebra+%26%0ATrigonometry',
       'Comprehensive algebra and trigonometry: functions, equations, identities, analytic trig. CC-BY.', 1392),
      ('OpenStax — College Algebra 2e', 'textbook', 'Mathematics', 'Algebra', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/college-algebra-2e',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=OpenStax%0ACollege%0AAlgebra+2e',
       'College-level algebra: equations, polynomials, exponentials, logarithms. CC-BY.', 1126),
      ('OpenStax — Precalculus 2e', 'textbook', 'Mathematics', 'Precalculus', 'CAPS',
       ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level'],
       'https://openstax.org/details/books/precalculus-2e',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=OpenStax%0APrecalculus+2e',
       'Functions, trigonometry, analytic geometry, sequences and series. CC-BY.', 1248),
      ('OpenStax — Introductory Statistics', 'textbook', 'Mathematics', 'Statistics & Probability', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','A-Level'],
       'https://openstax.org/details/books/introductory-statistics',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=OpenStax%0AIntroductory%0AStatistics',
       'Descriptive and inferential statistics, probability, hypothesis testing. CC-BY.', 906),
      ('OpenStax — Biology 2e', 'textbook', 'Biology', 'General Biology', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/biology-2e',
       'https://placehold.co/600x800/15803d/ffffff?text=OpenStax%0ABiology+2e',
       'Cell biology, genetics, evolution, ecology, animal/plant systems. CC-BY.', 1648),
      ('OpenStax — Concepts of Biology', 'textbook', 'Biology', 'Cells, Genetics, Ecology', 'CAPS',
       ARRAY['Grade 9','Grade 10','Grade 11','Form 3','Form 4','Form 5','O-Level','IGCSE'],
       'https://openstax.org/details/books/concepts-biology',
       'https://placehold.co/600x800/15803d/ffffff?text=OpenStax%0AConcepts+of%0ABiology',
       'Approachable intro biology — life chemistry, cells, genetics, ecosystems. CC-BY.', 779),
      ('OpenStax — Chemistry: Atoms First 2e', 'textbook', 'Chemistry', 'General Chemistry', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/chemistry-atoms-first-2e',
       'https://placehold.co/600x800/b91c1c/ffffff?text=OpenStax%0AChemistry%0AAtoms+First',
       'Chemistry from the atomic perspective: bonding, stoichiometry, kinetics. CC-BY.', 1428),
      ('OpenStax — College Physics', 'textbook', 'Physics', 'Mechanics, Waves, Electromagnetism', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/college-physics',
       'https://placehold.co/600x800/0e7490/ffffff?text=OpenStax%0ACollege%0APhysics',
       'Algebra-based physics: mechanics, thermodynamics, waves, electricity, modern physics. CC-BY.', 1278),
      ('OpenStax — Microbiology', 'textbook', 'Biology', 'Microbiology', 'CAPS',
       ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level'],
       'https://openstax.org/details/books/microbiology',
       'https://placehold.co/600x800/15803d/ffffff?text=OpenStax%0AMicrobiology',
       'Bacteria, viruses, fungi, immunity, microbial diseases. CC-BY.', 968),
      ('OpenStax — Astronomy 2e', 'textbook', 'Physics', 'Astronomy', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/astronomy-2e',
       'https://placehold.co/600x800/0e7490/ffffff?text=OpenStax%0AAstronomy+2e',
       'Solar system, stars, galaxies, cosmology — accessible science reading. CC-BY.', 1340),
      ('OpenStax — U.S. History', 'textbook', 'History', 'Modern History', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://openstax.org/details/books/us-history',
       'https://placehold.co/600x800/7c2d12/ffffff?text=OpenStax%0AU.S.+History',
       'Comprehensive US history from pre-Columbian to present. CC-BY.', 998),
      ('OpenStax — Psychology 2e', 'textbook', 'Life Orientation', 'Psychology', 'CAPS',
       ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level'],
       'https://openstax.org/details/books/psychology-2e',
       'https://placehold.co/600x800/7c3aed/ffffff?text=OpenStax%0APsychology+2e',
       'Intro psychology: cognition, development, personality, social psychology. CC-BY.', 832),
      ('Siyavula Mathematics — Grade 10', 'textbook', 'Mathematics', 'CAPS Mathematics', 'CAPS',
       ARRAY['Grade 10','Form 4','O-Level','IGCSE'],
       'https://www.siyavula.com/read/za/mathematics/grade-10',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=Siyavula%0AMaths%0AGrade+10',
       'Siyavula open Mathematics aligned to South African CAPS Grade 10. CC-BY.', 540),
      ('Siyavula Mathematics — Grade 11', 'textbook', 'Mathematics', 'CAPS Mathematics', 'CAPS',
       ARRAY['Grade 11','Form 4','Form 5','O-Level','A-Level'],
       'https://www.siyavula.com/read/za/mathematics/grade-11',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=Siyavula%0AMaths%0AGrade+11',
       'Siyavula open Mathematics aligned to CAPS Grade 11. CC-BY.', 580),
      ('Siyavula Mathematics — Grade 12', 'textbook', 'Mathematics', 'CAPS Mathematics', 'CAPS',
       ARRAY['Grade 12','Form 5','Form 6','A-Level'],
       'https://www.siyavula.com/read/za/mathematics/grade-12',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=Siyavula%0AMaths%0AGrade+12',
       'Siyavula open Mathematics aligned to CAPS Grade 12 (matric prep). CC-BY.', 612),
      ('Siyavula Physical Sciences — Grade 10', 'textbook', 'Physical Sciences', 'Physics & Chemistry', 'CAPS',
       ARRAY['Grade 10','Form 4','O-Level','IGCSE'],
       'https://www.siyavula.com/read/za/physical-sciences/grade-10',
       'https://placehold.co/600x800/0f766e/ffffff?text=Siyavula%0APhys+Sci%0AGrade+10',
       'Combined physics and chemistry for South African Grade 10. CC-BY.', 488),
      ('Siyavula Physical Sciences — Grade 11', 'textbook', 'Physical Sciences', 'Physics & Chemistry', 'CAPS',
       ARRAY['Grade 11','Form 4','Form 5','O-Level','A-Level'],
       'https://www.siyavula.com/read/za/physical-sciences/grade-11',
       'https://placehold.co/600x800/0f766e/ffffff?text=Siyavula%0APhys+Sci%0AGrade+11',
       'Physical Sciences for Grade 11 — mechanics, electricity, organic chemistry. CC-BY.', 524),
      ('Siyavula Physical Sciences — Grade 12', 'textbook', 'Physical Sciences', 'Physics & Chemistry', 'CAPS',
       ARRAY['Grade 12','Form 5','Form 6','A-Level'],
       'https://www.siyavula.com/read/za/physical-sciences/grade-12',
       'https://placehold.co/600x800/0f766e/ffffff?text=Siyavula%0APhys+Sci%0AGrade+12',
       'Physical Sciences for Grade 12 — matric exam-ready. CC-BY.', 558),
      ('Siyavula Life Sciences — Grade 10', 'textbook', 'Life Sciences', 'Biology', 'CAPS',
       ARRAY['Grade 10','Form 4','O-Level','IGCSE'],
       'https://www.siyavula.com/read/za/life-sciences/grade-10',
       'https://placehold.co/600x800/15803d/ffffff?text=Siyavula%0ALife+Sci%0AGrade+10',
       'Life Sciences Grade 10: cells, biodiversity, plant/animal tissue. CC-BY.', 432),
      ('Siyavula Mathematical Literacy — Grade 12', 'textbook', 'Mathematical Literacy', 'Numeracy & Finance', 'CAPS',
       ARRAY['Grade 12','Form 5','Form 6'],
       'https://www.siyavula.com/read/za/mathematical-literacy/grade-12',
       'https://placehold.co/600x800/7c3aed/ffffff?text=Siyavula%0AMaths+Lit%0AGrade+12',
       'Practical numeracy: finance, measurement, data handling. CC-BY.', 410),
      ('CK-12 Earth Science', 'textbook', 'Geography', 'Earth Science', 'CAPS',
       ARRAY['Grade 8','Grade 9','Grade 10','Form 2','Form 3','Form 4','O-Level','IGCSE'],
       'https://www.ck12.org/book/ck-12-earth-science-for-high-school/',
       'https://placehold.co/600x800/0891b2/ffffff?text=CK-12%0AEarth%0AScience',
       'Geology, oceanography, atmosphere, weather, ecosystems. CC-BY-NC.', 720),
      ('CK-12 Trigonometry', 'textbook', 'Mathematics', 'Trigonometry', 'CAPS',
       ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level'],
       'https://www.ck12.org/book/ck-12-trigonometry-second-edition/',
       'https://placehold.co/600x800/1a3fc4/ffffff?text=CK-12%0ATrigonometry',
       'Trigonometric functions, identities, equations, polar coordinates. CC-BY-NC.', 412),
      ('Romeo and Juliet — William Shakespeare', 'textbook', 'English', 'Drama / Set Work', 'CAPS',
       ARRAY['Grade 10','Grade 11','Form 4','Form 5','O-Level','IGCSE'],
       'https://www.gutenberg.org/files/1513/1513-h/1513-h.htm',
       'https://placehold.co/600x800/991b1b/ffffff?text=Romeo+%26%0AJuliet%0AShakespeare',
       'Shakespeare''s tragedy — common high-school set work. Public domain.', 152),
      ('Pride and Prejudice — Jane Austen', 'textbook', 'English', 'Novel / Set Work', 'CAPS',
       ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level'],
       'https://www.gutenberg.org/files/1342/1342-h/1342-h.htm',
       'https://placehold.co/600x800/831843/ffffff?text=Pride+%26%0APrejudice%0AAusten',
       'Austen classic — set work for many English curricula. Public domain.', 432),
      ('A Tale of Two Cities — Charles Dickens', 'textbook', 'English', 'Novel / Set Work', 'CAPS',
       ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level'],
       'https://www.gutenberg.org/files/98/98-h/98-h.htm',
       'https://placehold.co/600x800/365314/ffffff?text=A+Tale+of%0ATwo+Cities%0ADickens',
       'Dickens'' historical novel set during the French Revolution. Public domain.', 488),
      ('Alice''s Adventures in Wonderland — Lewis Carroll', 'textbook', 'English', 'Novel', 'CAPS',
       ARRAY['Grade 8','Grade 9','Grade 10','Form 2','Form 3','Form 4','O-Level','IGCSE'],
       'https://www.gutenberg.org/files/11/11-h/11-h.htm',
       'https://placehold.co/600x800/0369a1/ffffff?text=Alice+in%0AWonderland%0ACarroll',
       'Carroll''s beloved children''s/YA classic. Public domain.', 192)
    ) AS t(title, kind, subject, topic, curriculum, grade_levels, pdf_url, thumbnail_url, description, pages)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM public.library_system_resources WHERE title = rec.title) THEN
      INSERT INTO public.library_system_resources
        (title, kind, subject, topic, curriculum, grade_levels, pdf_url, thumbnail_url, description, pages)
      VALUES
        (rec.title, rec.kind, rec.subject, rec.topic, rec.curriculum, rec.grade_levels,
         rec.pdf_url, rec.thumbnail_url, rec.description, rec.pages);
    END IF;
  END LOOP;
END
$seed$;
