-- Verified curriculum seed: NSC Grade 10 Life Orientation
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 10 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('NSC', 'Grade 10', 'Life Orientation', $topics$
[
  {
    "name": "Development of the Self in Society",
    "subtopics": [
      "Life skills and personal lifestyle choices",
      "Stress management and coping mechanisms",
      "Conflict resolution and interpersonal skills",
      "Gender roles and relationships",
      "Human factors causing ill health, accidents and disasters",
      "Healthy balanced lifestyle choices"
    ],
    "learning_objectives": [
      "Apply strategies to manage stress and conflict constructively",
      "Evaluate the impact of lifestyle choices on personal wellbeing",
      "Analyse how gender constructs influence relationships and behaviour",
      "Assess human factors that contribute to ill health and unsafe situations"
    ],
    "key_concepts": [
      "Stressors and coping strategies (problem-focused vs emotion-focused)",
      "Assertiveness vs aggression vs passivity",
      "Gender stereotyping and gender-based violence awareness",
      "Risky behaviour and its consequences",
      "Self-awareness and emotional intelligence",
      "Work-life balance"
    ],
    "assessment_objectives": [
      "Define and explain personal development concepts",
      "Apply coping and conflict-resolution strategies to scenarios",
      "Critically evaluate lifestyle and relationship choices",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Define the concept and give a relevant example",
      "Suggest strategies the person in the scenario could use to manage stress",
      "Critically discuss how gender stereotypes could affect the relationship described",
      "Evaluate the impact of the lifestyle choice on the person's studies and health",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "Grade 11 development of the self"
    ],
    "common_misconceptions": [
      "Believing stress is always harmful rather than potentially motivating in moderation",
      "Confusing assertiveness with aggression",
      "Treating conflict as inherently negative rather than an opportunity for growth",
      "Assuming lifestyle diseases only affect older people"
    ],
    "exemplar_question_stems": [
      "Define the term coping mechanism and give TWO examples suitable for a Grade 12 learner",
      "The learner in the scenario faces exam pressure and family responsibilities; recommend THREE stress-management strategies and motivate each",
      "Critically discuss TWO ways in which rigid gender roles may negatively affect both partners in a relationship"
    ]
  },
  {
    "name": "Social and Environmental Responsibility",
    "subtopics": [
      "Environmental issues that cause ill health (pollution, waste, water quality)",
      "Community responsibility to provide environments promoting health",
      "Social issues: poverty, food security, HIV and AIDS awareness",
      "Community projects and social responsibility campaigns",
      "Laws, policies and practices protecting environmental health",
      "Personal contribution to a healthy environment"
    ],
    "learning_objectives": [
      "Analyse environmental factors that impact community health",
      "Evaluate community and government responses to environmental issues",
      "Design or assess a community project addressing a social issue",
      "Explain individual responsibility toward sustainable environments"
    ],
    "key_concepts": [
      "Environmental health and disease links",
      "Sustainability and conservation",
      "Community participation and volunteerism",
      "Public health campaigns",
      "Environmental legislation awareness",
      "Ubuntu and collective responsibility"
    ],
    "assessment_objectives": [
      "Explain links between environment and health",
      "Evaluate the effectiveness of campaigns and projects",
      "Propose realistic personal and community actions",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Explain how the environmental problem described could affect the health of residents",
      "Evaluate the effectiveness of the community project in the case study",
      "Suggest practical ways learners could contribute to solving the issue",
      "Discuss the role of legislation in addressing the environmental concern",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "Grade 11 social and environmental responsibility"
    ],
    "common_misconceptions": [
      "Believing environmental care is only the government's responsibility",
      "Confusing weather events with long-term environmental degradation",
      "Assuming awareness campaigns automatically change behaviour",
      "Thinking recycling alone solves waste management problems"
    ],
    "exemplar_question_stems": [
      "Explain TWO ways in which polluted water sources could affect the health of the community in the scenario",
      "Critically evaluate whether the awareness campaign described is likely to change behaviour, giving reasons",
      "Recommend THREE actions your school community could take to reduce waste, and motivate each"
    ]
  },
  {
    "name": "Democracy and Human Rights",
    "subtopics": [
      "Responsible citizenship",
      "Bill of Rights and responsibilities",
      "Discrimination and human rights violations",
      "The role of the media in a democratic society",
      "Ideologies, beliefs and worldviews",
      "Sport and nation building",
      "Democratic participation and structures"
    ],
    "learning_objectives": [
      "Explain rights and the responsibilities that accompany them",
      "Analyse cases of discrimination and evaluate responses",
      "Evaluate the role of a free press and social media in democracy",
      "Discuss how diversity of beliefs can be respected in society"
    ],
    "key_concepts": [
      "Human rights vs responsibilities",
      "Equality, dignity and freedom",
      "Discrimination (direct and indirect)",
      "Media freedom, bias and fake news",
      "Tolerance and social cohesion",
      "Nation building through shared events"
    ],
    "assessment_objectives": [
      "Define democratic and human-rights concepts",
      "Apply rights principles to case studies",
      "Critically evaluate media and societal practices against democratic values",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Name the right violated in the scenario and justify your answer",
      "Discuss the responsibility that accompanies the stated right",
      "Critically evaluate the role of social media in the situation described",
      "Explain how the event described could contribute to nation building",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 16,
    "prerequisites": [
      "Grade 11 democracy and human rights"
    ],
    "common_misconceptions": [
      "Believing rights are absolute with no accompanying responsibilities",
      "Confusing freedom of speech with freedom from consequences for hate speech",
      "Assuming discrimination must be intentional to be a violation",
      "Thinking democracy only involves voting in elections"
    ],
    "exemplar_question_stems": [
      "Identify the human right most clearly violated in the case study and motivate your choice",
      "Critically discuss TWO ways in which fake news can undermine democratic decision-making",
      "Explain how participation in the national sporting event described could promote social cohesion"
    ]
  },
  {
    "name": "Careers and Career Choices",
    "subtopics": [
      "Commitment to a career decision",
      "Requirements for admission to higher education and other post-school options",
      "Applications, funding (bursaries, loans, schemes) and planning",
      "Preparation for job applications: CVs, interviews",
      "Core elements of a job contract and conditions of employment",
      "Labour rights and responsibilities; trade unions",
      "Unemployment and entrepreneurship as an option"
    ],
    "learning_objectives": [
      "Plan realistic post-school pathways aligned to interests and results",
      "Prepare application documents and interview strategies",
      "Interpret basic employment contract elements and labour rights",
      "Evaluate entrepreneurship as a response to unemployment"
    ],
    "key_concepts": [
      "Admission point scores and entry requirements",
      "Funding options and obligations",
      "CV structure and interview etiquette",
      "Employment contract essentials (hours, remuneration, leave)",
      "Fair labour practice",
      "SWOT of self for career fit"
    ],
    "assessment_objectives": [
      "Explain post-school study and funding options",
      "Apply application and interview skills to scenarios",
      "Evaluate career decisions and employment situations against relevant information",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Advise the learner in the scenario on suitable post-school options and motivate",
      "List the key elements that must appear in the described document",
      "Explain the funding option and TWO obligations attached to it",
      "Evaluate whether the employment condition described is fair, with reference to labour rights",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "Grade 11 careers and career choices"
    ],
    "common_misconceptions": [
      "Believing university is the only worthwhile post-school pathway",
      "Confusing a bursary (often service-linked) with a loan (repayable)",
      "Thinking a CV should include every personal detail regardless of relevance",
      "Assuming verbal job offers carry the same protection as written contracts"
    ],
    "exemplar_question_stems": [
      "The learner qualifies for a diploma but not a degree; advise them on TWO realistic pathways and motivate each",
      "Name THREE essential elements of an employment contract and explain why each protects the employee",
      "Discuss TWO advantages and TWO challenges of entrepreneurship for a school leaver facing unemployment"
    ]
  },
  {
    "name": "Study Skills and Examination Preparation",
    "subtopics": [
      "Study styles and study methods",
      "Time management and study timetables",
      "Goal setting for examinations",
      "Examination writing skills and managing exam stress",
      "Reflection on own study habits",
      "Process of assessment and moderation awareness"
    ],
    "learning_objectives": [
      "Select study methods appropriate to own learning style and content type",
      "Construct and maintain a realistic study timetable",
      "Apply examination techniques such as question analysis and time allocation",
      "Reflect critically on and adjust personal study strategies"
    ],
    "key_concepts": [
      "Active vs passive study methods",
      "Mnemonics, mind maps and summarisation",
      "Spaced practice vs cramming",
      "SMART goals",
      "Action verbs in exam questions (discuss, evaluate, critically analyse)",
      "Exam-stress management"
    ],
    "assessment_objectives": [
      "Explain and apply study methods and planning tools",
      "Interpret exam instructions and action verbs correctly",
      "Evaluate the effectiveness of study strategies in scenarios",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Recommend study methods suited to the subject described and motivate",
      "Draw up guidelines for an effective study timetable for the learner in the scenario",
      "Explain what the action verb requires the learner to do",
      "Evaluate the learner's current study habits and suggest improvements",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Grade 11 study skills"
    ],
    "common_misconceptions": [
      "Believing re-reading notes repeatedly equals effective studying",
      "Thinking longer study hours automatically produce better results than focused sessions",
      "Assuming cramming the night before is an effective strategy",
      "Treating all exam questions as requiring the same depth of answer regardless of the action verb"
    ],
    "exemplar_question_stems": [
      "The learner studies by reading through notes once; recommend THREE more active study methods and motivate each",
      "Explain the difference between what is required by the action verbs describe and critically evaluate",
      "Suggest FOUR guidelines for drawing up an effective examination study timetable"
    ]
  },
  {
    "name": "Physical Education and Recreation",
    "subtopics": [
      "Value of participation in physical activity",
      "Fitness components and personal fitness programmes",
      "Safety in physical activity",
      "Recreational and relaxation activities for stress relief",
      "Long-term benefits of an active lifestyle",
      "Umpiring, administration and leadership in sport"
    ],
    "learning_objectives": [
      "Explain the physical, mental and social benefits of regular activity",
      "Design or evaluate a basic personal fitness programme",
      "Apply safety principles to physical activities",
      "Discuss recreation as a strategy for wellbeing and stress management"
    ],
    "key_concepts": [
      "Cardiovascular endurance, strength, flexibility, muscular endurance",
      "FITT principle (frequency, intensity, time, type)",
      "Warm-up and cool-down",
      "Hydration and injury prevention",
      "Recreation vs competitive sport",
      "Leadership roles in physical activity"
    ],
    "assessment_objectives": [
      "Explain fitness and recreation concepts",
      "Apply programme-design principles to scenarios",
      "Evaluate the contribution of activity to holistic health",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Explain TWO benefits of regular physical activity for a matric learner",
      "Apply the FITT principle to improve the fitness component named",
      "Suggest safety measures for the activity described",
      "Discuss how recreation could help the person in the scenario manage stress",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "Grade 11 physical education"
    ],
    "common_misconceptions": [
      "Believing exercise only benefits physical health and not mental wellbeing",
      "Thinking more intense training is always better, ignoring rest and recovery",
      "Confusing recreation (enjoyment-focused) with competitive sport",
      "Assuming stretching alone constitutes an adequate warm-up"
    ],
    "exemplar_question_stems": [
      "Explain how regular physical activity could benefit a Grade 12 learner during the examination period",
      "Use the FITT principle to design a two-week plan to improve cardiovascular endurance",
      "Recommend THREE safety measures for the outdoor activity described in the scenario"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
