-- Verified curriculum seed: ZIMSEC Form 2 Geography
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 2 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 2', 'Geography', $topics$
[
  {
    "name": "Map Work and Geographical Skills",
    "subtopics": [
      "Grid references (four- and six-figure)",
      "Scale and distance measurement",
      "Direction and bearings",
      "Contours and relief interpretation",
      "Cross-sections and gradient",
      "Map symbols and settlement patterns on maps",
      "Photograph interpretation",
      "Sketch maps and field sketches"
    ],
    "learning_objectives": [
      "Read four- and six-figure grid references accurately",
      "Measure straight-line and curved distances using the map scale",
      "State compass directions and calculate three-figure bearings between points",
      "Interpret relief from contour patterns (valley, spur, ridge, escarpment, saddle)",
      "Draw a cross-section between two points and calculate gradient",
      "Identify and interpret human and physical features from map evidence",
      "Relate ground and aerial photographs to map extracts"
    ],
    "key_concepts": [
      "eastings before northings",
      "representative fraction and linear scale",
      "contour interval",
      "intervisibility",
      "gradient as vertical interval over horizontal equivalent",
      "settlement site and situation from map evidence",
      "drainage patterns visible on maps"
    ],
    "assessment_objectives": [
      "Skill: accurate measurement and reading of map data",
      "Interpretation: explain patterns and relationships shown on the map extract",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Compulsory map-reading question with grid references, distance, bearing and relief parts (about 20 marks across parts)",
      "Draw a cross-section and mark a named feature (4-5 marks)",
      "Give map evidence for a stated land use (2-3 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Reading northings before eastings in grid references",
      "Measuring bearings anticlockwise or from south",
      "Confusing closely spaced contours (steep) with widely spaced (gentle)",
      "Quoting features without grid-reference evidence when evidence is demanded"
    ],
    "exemplar_question_stems": [
      "Give the six-figure grid reference of the school shown on the map extract.",
      "Measure the distance along the road from the bridge to the clinic. Give your answer in kilometres.",
      "Calculate the bearing of the dam wall from the trigonometrical station.",
      "Using contour evidence, describe the relief of the area shown in the north-east of the extract."
    ]
  },
  {
    "name": "Weather and Climate",
    "subtopics": [
      "Elements of weather and measuring instruments",
      "The Stevenson screen and weather station siting",
      "Recording and interpreting weather data",
      "Clouds and precipitation types",
      "Factors affecting temperature and rainfall",
      "Climate of Zimbabwe and southern Africa",
      "Tropical climates and the ITCZ",
      "Weather hazards: drought and tropical cyclones"
    ],
    "learning_objectives": [
      "Name the instruments used to measure temperature, rainfall, humidity, pressure, wind speed and direction, and describe how each works",
      "Explain the siting requirements of a weather station and the purpose of the Stevenson screen",
      "Calculate mean, range and totals from weather data and draw climate graphs",
      "Describe the three main rainfall types (convectional, relief, frontal) with diagrams",
      "Explain how latitude, altitude, distance from the sea and ocean currents affect climate",
      "Describe the seasonal movement of the ITCZ and its effect on rainfall in the region",
      "Outline the causes and effects of drought and tropical cyclones and possible responses"
    ],
    "key_concepts": [
      "maximum-minimum thermometer",
      "wet-and-dry bulb hygrometer",
      "isohyets and isotherms",
      "convectional uplift",
      "rain-shadow effect",
      "ITCZ migration with the overhead sun",
      "El Niño influence on regional rainfall",
      "cyclone tracking and warning systems"
    ],
    "assessment_objectives": [
      "Knowledge of instruments and processes",
      "Interpretation of weather data and climate graphs in context",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Label a diagram of a rain gauge or Stevenson screen and explain siting (4-6 marks)",
      "Draw and interpret a climate graph for a named station (6-8 marks)",
      "Explain, with a diagram, how relief rainfall forms (5-6 marks)",
      "Describe the effects of a named tropical cyclone on people and the environment (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Placing the rain gauge under a roof or tree when describing siting",
      "Reading the wet bulb as the actual air temperature",
      "Confusing weather (short-term) with climate (long-term average)",
      "Assuming the ITCZ is stationary at the equator all year"
    ],
    "exemplar_question_stems": [
      "Describe how a maximum and minimum thermometer is used to obtain the daily temperature range.",
      "The table shows monthly rainfall and temperature for a station in Zimbabwe. Draw a climate graph and describe the rainfall regime.",
      "With the aid of a labelled diagram, explain the formation of convectional rainfall.",
      "Suggest three measures communities can take to reduce the impact of drought."
    ]
  },
  {
    "name": "Landforms and Geomorphic Processes",
    "subtopics": [
      "Weathering (physical, chemical, biological)",
      "Mass wasting",
      "River processes: erosion, transportation, deposition",
      "River landforms (V-shaped valley, waterfall, meander, floodplain, delta)",
      "Granite landforms (dwalas, castle kopjes, balancing rocks)",
      "Rift valleys, folding and faulting",
      "Coastal and wind processes overview"
    ],
    "learning_objectives": [
      "Distinguish the main types of weathering and the conditions favouring each",
      "Describe river erosion processes (hydraulic action, abrasion, attrition, solution) and transport processes (traction, saltation, suspension, solution)",
      "Explain the formation of major river landforms with annotated diagrams",
      "Explain the formation of granite landforms common on the Zimbabwean landscape",
      "Describe folding, faulting and the formation of rift valleys with reference to African examples",
      "Relate landforms to human activity (settlement, tourism, farming)"
    ],
    "key_concepts": [
      "exfoliation in hot climates",
      "freeze-thaw where temperatures cross zero",
      "load and discharge",
      "lateral vs vertical erosion",
      "slip-off slope and river cliff",
      "jointing in granite and spheroidal weathering",
      "horst and graben structures"
    ],
    "assessment_objectives": [
      "Knowledge of processes and landform formation",
      "Application: annotated diagrams and named local/regional examples",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Explain, with diagrams, the formation of a waterfall and gorge (6-8 marks)",
      "Describe the processes by which a river transports its load (4-6 marks)",
      "Explain the formation of a castle kopje (5-6 marks)",
      "Describe the formation of the Great Rift Valley (6 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Treating weathering (in situ breakdown) as the same as erosion (removal by a moving agent)",
      "Drawing meanders eroding on the inside bank instead of the outside",
      "Assuming waterfalls only form on faults rather than on resistant rock bands",
      "Confusing folding (compression, no fracture) with faulting (fracture and displacement)"
    ],
    "exemplar_question_stems": [
      "Distinguish between physical and chemical weathering, giving one example of each.",
      "With the aid of labelled diagrams, describe the formation of an oxbow lake.",
      "Explain why balancing rocks are common in granite areas of Zimbabwe.",
      "Describe two ways in which river floodplains are useful to farmers."
    ]
  },
  {
    "name": "Population",
    "subtopics": [
      "Population distribution and density",
      "Factors affecting distribution",
      "Population structure and pyramids",
      "Fertility, mortality and natural increase",
      "Migration: types, causes and effects",
      "Population growth and resources",
      "Census and population data"
    ],
    "learning_objectives": [
      "Define density and distribution and describe world and regional patterns",
      "Explain physical and human factors influencing where people live",
      "Interpret population pyramids for developing and developed countries",
      "Calculate birth rate, death rate and natural increase from data",
      "Classify migration (rural-urban, international, forced, voluntary) and analyse push and pull factors",
      "Evaluate the effects of migration on source and destination areas",
      "Discuss the relationship between population growth and resources, including responses such as family planning"
    ],
    "key_concepts": [
      "persons per square kilometre",
      "dependency ratio",
      "wide-based pyramid indicating high fertility",
      "demographic transition stages",
      "push and pull factors",
      "remittances",
      "brain drain",
      "population-resource balance"
    ],
    "assessment_objectives": [
      "Knowledge of terms and patterns",
      "Interpretation of pyramids, data tables and case studies",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe and explain the population distribution shown on a map (6-8 marks)",
      "Compare two population pyramids and account for the differences (6-8 marks)",
      "Explain the causes and effects of rural-to-urban migration in a named country (8-10 marks)",
      "Calculate the natural increase from given birth and death rates (2-3 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Using density and distribution interchangeably",
      "Reading a pyramid's bars as absolute totals when they are percentages",
      "Treating natural increase as including migration",
      "Assuming all migration is permanent and international"
    ],
    "exemplar_question_stems": [
      "Define population density and state how it is calculated.",
      "Study the population pyramid provided. Describe three features of the population structure it shows.",
      "Explain four push factors that cause people to leave rural areas.",
      "Describe the problems caused by rapid population growth in developing countries."
    ]
  },
  {
    "name": "Settlement and Urbanisation",
    "subtopics": [
      "Settlement types, site and situation",
      "Rural settlement patterns (nucleated, linear, dispersed)",
      "Settlement hierarchy and functions",
      "Urban land-use zones and models",
      "Urbanisation causes and consequences",
      "Urban problems and solutions in developing cities",
      "Rural service centres and growth points"
    ],
    "learning_objectives": [
      "Distinguish site from situation and identify factors favouring settlement growth",
      "Describe rural settlement patterns and the factors producing them",
      "Rank settlements in a hierarchy using population and services",
      "Describe urban land-use zones (CBD, industrial, residential) and their characteristics",
      "Explain the causes of rapid urbanisation in developing countries",
      "Analyse urban problems (housing shortages, informal settlements, congestion, unemployment, pollution) and evaluate solutions",
      "Explain the role of growth points and rural service centres in decentralisation"
    ],
    "key_concepts": [
      "wet point and dry point sites",
      "sphere of influence",
      "range and threshold of services",
      "CBD characteristics: high land values, tall buildings",
      "informal sector employment",
      "site-and-service schemes",
      "decentralisation policy"
    ],
    "assessment_objectives": [
      "Knowledge of settlement concepts",
      "Application to named cities and map evidence",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe the pattern of settlement shown on the map extract and suggest reasons (5-6 marks)",
      "Draw a labelled sketch of urban land-use zones for a named city (6 marks)",
      "Explain the problems caused by the growth of informal settlements and suggest solutions (8-10 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "Population"
    ],
    "common_misconceptions": [
      "Confusing site (the actual land) with situation (position relative to surroundings)",
      "Assuming the CBD is residential",
      "Treating urbanisation as the growth of cities' area rather than the rising share of people living in towns",
      "Believing informal settlements have no economic function"
    ],
    "exemplar_question_stems": [
      "Distinguish between the site and the situation of a settlement.",
      "Describe three characteristics of the central business district of a city you have studied.",
      "Explain why growth points were established in Zimbabwe and assess their success.",
      "Suggest three practical solutions to housing shortages in rapidly growing cities."
    ]
  },
  {
    "name": "Agriculture and Rural Land Use",
    "subtopics": [
      "Farming systems: subsistence and commercial",
      "Arable, pastoral and mixed farming",
      "Communal, small-scale and large-scale farming in Zimbabwe",
      "Factors affecting farming (physical, economic, political)",
      "Irrigation schemes",
      "Cash crops and food crops",
      "Problems facing farmers and possible solutions",
      "Sustainable farming practices"
    ],
    "learning_objectives": [
      "Classify farming systems by inputs, processes and outputs",
      "Compare subsistence and commercial farming with examples",
      "Describe the main farming regions and land tenure categories of Zimbabwe",
      "Explain how rainfall, soils, capital, markets and government policy influence farming decisions",
      "Describe a named irrigation scheme: location, water source, crops and benefits",
      "Analyse problems such as drought, pests, poor prices and land degradation, and evaluate responses",
      "Describe conservation farming methods (crop rotation, contour ridging, mulching, agroforestry)"
    ],
    "key_concepts": [
      "inputs-processes-outputs model",
      "natural farming regions by rainfall",
      "cash crop vs food crop trade-offs",
      "gravity-fed vs pump irrigation",
      "soil erosion on overgrazed land",
      "conservation farming basins",
      "market access and price fluctuation"
    ],
    "assessment_objectives": [
      "Knowledge of farming systems and factors",
      "Evaluation of problems and solutions using named examples",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe a named commercial farming system as inputs, processes and outputs (6-8 marks)",
      "Explain how physical factors influence crop farming in a named region (6 marks)",
      "Describe the benefits and problems of a named irrigation scheme (6-8 marks)",
      "Suggest measures to reduce soil erosion on communal farmland (4-6 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Weather and Climate"
    ],
    "common_misconceptions": [
      "Assuming subsistence farmers never sell any produce",
      "Attributing all low yields to laziness rather than rainfall, soils, capital and market access",
      "Treating irrigation as free of drawbacks such as salinisation and waterlogging",
      "Confusing pastoral (livestock) with arable (crop) farming"
    ],
    "exemplar_question_stems": [
      "Using the inputs-processes-outputs framework, describe small-scale cotton farming.",
      "Explain three physical factors that make Natural Region One suitable for tea and coffee growing.",
      "Describe the advantages that irrigation has brought to farmers in a scheme you have studied.",
      "Explain how contour ridging helps to conserve soil on sloping land."
    ]
  },
  {
    "name": "Mining, Industry and Energy",
    "subtopics": [
      "Mineral resources and mining methods",
      "A named mining area: extraction, processing, markets",
      "Effects of mining on the environment and communities",
      "Types of industry (primary, secondary, tertiary)",
      "Industrial location factors",
      "A named manufacturing industry case study",
      "Energy sources: hydro, thermal, solar, fuelwood",
      "Energy problems and conservation"
    ],
    "learning_objectives": [
      "Name major minerals and the methods used to mine them (open cast, shaft, alluvial)",
      "Describe a named mining case study from extraction to market",
      "Assess the economic benefits and environmental costs of mining",
      "Classify industries and explain the factors influencing industrial location (raw materials, power, labour, markets, transport, government policy)",
      "Describe a named manufacturing industry: location, inputs, products and markets",
      "Compare energy sources and explain the importance of hydroelectric power in the region",
      "Discuss energy shortages, fuelwood dependence and conservation strategies"
    ],
    "key_concepts": [
      "open cast vs shaft mining trade-offs",
      "mineral beneficiation",
      "land degradation and tailings dams",
      "footloose industries",
      "industrial linkages",
      "hydroelectric power generation at a named dam",
      "load shedding and demand management",
      "renewable vs non-renewable sources"
    ],
    "assessment_objectives": [
      "Knowledge of resources, methods and location factors",
      "Evaluation of impacts using case studies",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe the method used to mine a named mineral and explain why that method is used (5-6 marks)",
      "Assess the effects of mining on the environment of a named area (6-8 marks)",
      "Explain the factors that influenced the location of a named industry (6-8 marks)",
      "Explain why many rural households still depend on fuelwood and the effects of this dependence (6 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Assuming all mining is underground shaft mining",
      "Ignoring transport costs when explaining industrial location",
      "Treating electricity generation and distribution problems as identical",
      "Believing renewable sources have no environmental impact at all"
    ],
    "exemplar_question_stems": [
      "Describe open cast mining and state one advantage and one disadvantage of the method.",
      "Explain three factors that favoured the growth of manufacturing industry in a city you have studied.",
      "Describe how electricity is generated at a hydroelectric power station.",
      "Suggest ways in which households can reduce their use of fuelwood."
    ]
  },
  {
    "name": "Transport, Trade and Tourism",
    "subtopics": [
      "Modes of transport and their advantages",
      "Transport networks and route factors",
      "Problems of transport in the region",
      "International and regional trade",
      "Trade balance, imports and exports",
      "Regional cooperation (SADC and trading blocs)",
      "Tourism: attractions, benefits and problems",
      "A named tourist area case study"
    ],
    "learning_objectives": [
      "Compare road, rail, air and water transport in cost, speed and suitability",
      "Explain physical and economic factors influencing route location",
      "Describe trade patterns: typical exports (minerals, agricultural products) and imports (machinery, fuel)",
      "Explain the meaning and consequences of an unfavourable balance of trade",
      "Describe the aims and benefits of regional groupings for trade and transport",
      "Identify major tourist attractions and assess the economic, social and environmental effects of tourism",
      "Describe a named tourist destination and measures used to manage it sustainably"
    ],
    "key_concepts": [
      "landlocked country dependence on corridors",
      "feeder roads",
      "containerisation",
      "visible and invisible trade",
      "trade deficit",
      "ecotourism",
      "carrying capacity of attractions",
      "multiplier effect of tourism"
    ],
    "assessment_objectives": [
      "Knowledge of transport, trade and tourism patterns",
      "Evaluation of benefits and problems with named examples",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Compare the suitability of road and rail for transporting minerals to a port (5-6 marks)",
      "Explain the problems faced by a landlocked country in conducting foreign trade (6 marks)",
      "Describe the benefits and problems that tourism brings to a named area (8-10 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 9,
    "prerequisites": [
      "Primary school environmental and map-skills foundations"
    ],
    "common_misconceptions": [
      "Assuming air transport is best for all goods regardless of bulk and cost",
      "Confusing balance of trade with balance of payments",
      "Treating tourism income as automatically staying in the local area (leakage ignored)",
      "Believing regional trade blocs remove all trade barriers instantly"
    ],
    "exemplar_question_stems": [
      "State three advantages of rail transport for carrying bulky goods.",
      "Explain why an unfavourable balance of trade is a problem for a developing country.",
      "Describe the natural attractions that draw tourists to a destination you have studied.",
      "Suggest measures to reduce the environmental damage caused by tourists at a popular attraction."
    ]
  },
  {
    "name": "Environmental Management and Hazards",
    "subtopics": [
      "Deforestation: causes, effects and remedies",
      "Soil erosion and land degradation",
      "Water pollution and management",
      "Air pollution and climate change basics",
      "Wildlife conservation and national parks",
      "Community-based natural resource management",
      "Natural hazards: floods and drought responses",
      "Sustainable development concepts"
    ],
    "learning_objectives": [
      "Explain the causes and consequences of deforestation and evaluate afforestation and agroforestry responses",
      "Describe the causes of soil erosion and gully formation and appropriate conservation measures",
      "Identify sources of water and air pollution and their effects on health and ecosystems",
      "Explain conservation approaches including national parks and community-based programmes",
      "Describe the causes, effects and management of floods and droughts",
      "Define sustainable development and apply it to resource-use decisions"
    ],
    "key_concepts": [
      "fuelwood-driven forest loss",
      "gully reclamation",
      "siltation of dams",
      "point and non-point pollution sources",
      "poaching pressure and anti-poaching strategies",
      "community benefit-sharing from wildlife",
      "early warning systems",
      "sustainability as meeting present needs without compromising the future"
    ],
    "assessment_objectives": [
      "Knowledge of environmental processes and problems",
      "Evaluation of management strategies using examples",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Explain the causes and effects of deforestation in a named area (6-8 marks)",
      "Describe measures used to control soil erosion (5-6 marks)",
      "Assess the success of community-based wildlife management (6-8 marks)",
      "Describe how communities can prepare for and respond to floods (6 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 9,
    "prerequisites": [
      "Agriculture and Rural Land Use"
    ],
    "common_misconceptions": [
      "Blaming deforestation on a single cause instead of interacting pressures",
      "Treating conservation and use of resources as always incompatible",
      "Assuming pollution effects are only local and immediate",
      "Confusing weather hazards (events) with climate change (long-term trend)"
    ],
    "exemplar_question_stems": [
      "Explain three causes of deforestation in communal areas.",
      "Describe how gullies form and outline two methods used to reclaim them.",
      "Explain how local communities can benefit from wildlife conservation programmes.",
      "Define sustainable development and give one example of a sustainable farming practice."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
