-- Verified curriculum seed: IEB Grade 8 Economics
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 8 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('IEB', 'Grade 8', 'Economics', $topics$
[
  {
    "name": "The Circular Flow and National Account Aggregates",
    "subtopics": [
      "The open economy circular flow model",
      "Participants: households, firms, government, foreign sector",
      "Leakages and injections",
      "National account aggregates: GDP, GNI, and conversions",
      "Methods of calculating GDP: production, expenditure, income",
      "Nominal vs real figures and the GDP deflator",
      "The multiplier and its calculation"
    ],
    "learning_objectives": [
      "Draw and explain the open-economy circular flow model",
      "Identify leakages and injections and their effect on the size of the flow",
      "Distinguish between GDP and GNI and convert between basic prices and market prices",
      "Compare the three methods of calculating GDP",
      "Convert nominal values to real values",
      "Calculate and interpret the multiplier"
    ],
    "key_concepts": [
      "Circular flow",
      "Leakages and injections",
      "GDP and GNI",
      "National accounting conversions",
      "Real vs nominal",
      "Multiplier"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of macroeconomic models and aggregates",
      "Apply calculations and interpret national account data",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Data response with national account figures",
      "Draw-and-label the circular flow",
      "Multiplier calculation with interpretation",
      "Eight-mark paragraph and 40-mark essay formats",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Grade 11 Economics foundations"
    ],
    "common_misconceptions": [
      "Confusing leakages (savings, taxes, imports) with injections",
      "Treating GDP and GNI as interchangeable",
      "Adding intermediate goods into GDP causing double counting",
      "Believing the multiplier only applies to government spending",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "With the aid of a fully labelled diagram, explain the circular flow in an open economy.",
      "Calculate the multiplier if the marginal propensity to consume is 0.75, and explain the effect of an injection of R2 billion.",
      "Study the national accounts table and convert GDP at basic prices to GDP at market prices.",
      "Briefly discuss savings and imports as leakages from the circular flow."
    ]
  },
  {
    "name": "Business Cycles and Forecasting",
    "subtopics": [
      "Composition and phases of the business cycle",
      "Endogenous and exogenous explanations",
      "Government policy responses: monetary and fiscal",
      "Features underpinning forecasting: leading, coincident, lagging indicators",
      "Length of cycles and trend lines",
      "The new economic paradigm: smoothing cycles"
    ],
    "learning_objectives": [
      "Describe the four phases of the business cycle with their characteristics",
      "Compare endogenous and exogenous explanations of cycles",
      "Explain how monetary and fiscal policy can smooth the cycle",
      "Interpret leading, coincident and lagging indicators",
      "Analyse trend lines, amplitude and extrapolation in forecasting",
      "Discuss the new economic paradigm and its policy implications"
    ],
    "key_concepts": [
      "Business cycle phases",
      "Endogenous vs exogenous views",
      "Stabilisation policy",
      "Economic indicators",
      "Amplitude and trend",
      "New economic paradigm"
    ],
    "assessment_objectives": [
      "Explain cyclical behaviour and its indicators",
      "Evaluate policy approaches to managing cycles",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Diagram question on cycle phases",
      "Data response using indicator movements",
      "Essay on government responses to a recession",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "The Circular Flow and National Account Aggregates"
    ],
    "common_misconceptions": [
      "Believing every downswing is a depression",
      "Confusing leading indicators with the most important indicators",
      "Assuming government can eliminate cycles entirely",
      "Reading a trend line as a forecast guarantee",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "With the aid of a diagram, describe the phases of the business cycle.",
      "Distinguish between leading and lagging economic indicators, giving an example of each.",
      "Discuss how the South African Reserve Bank could respond to an overheating economy.",
      "Explain why exogenous factors make business cycle forecasting difficult."
    ]
  },
  {
    "name": "The Public Sector and Fiscal Policy",
    "subtopics": [
      "Composition and necessity of the public sector",
      "Problems of public sector provisioning",
      "Objectives of the public sector and its budgets",
      "Fiscal policy: the main budget, revenue and expenditure",
      "Types of taxes and criteria for a good tax",
      "The Laffer curve",
      "Public sector failure and accountability"
    ],
    "learning_objectives": [
      "Explain why the public sector exists and what it provides",
      "Analyse problems of public provisioning including inefficiency and lack of pricing",
      "Outline the composition of the national budget",
      "Distinguish direct from indirect taxes and progressive from regressive taxes",
      "Evaluate taxes against the criteria of a good tax",
      "Interpret the Laffer curve and its policy implications",
      "Discuss causes and examples of public sector failure"
    ],
    "key_concepts": [
      "Public goods",
      "Fiscal policy",
      "Budget composition",
      "Direct vs indirect tax",
      "Progressive taxation",
      "Laffer curve",
      "Public sector failure"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of the state's economic role",
      "Evaluate fiscal instruments and public sector performance",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Data response using budget figures",
      "Paragraph on criteria of a good tax",
      "Essay on public sector failure with examples",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "The Circular Flow and National Account Aggregates"
    ],
    "common_misconceptions": [
      "Confusing public goods with goods produced by the public sector",
      "Believing indirect taxes are progressive",
      "Reading the Laffer curve as proof that all tax cuts raise revenue",
      "Treating budget deficits as always harmful",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Explain the characteristics of public goods that prevent private markets from providing them.",
      "Evaluate VAT against any three criteria of a good tax.",
      "With the aid of the Laffer curve, explain the possible effect of raising the top marginal tax rate.",
      "Discuss reasons for public sector failure in the delivery of basic services."
    ]
  },
  {
    "name": "Foreign Exchange Markets and the Balance of Payments",
    "subtopics": [
      "The main reasons for international trade",
      "The balance of payments: current, capital and financial accounts",
      "Foreign exchange markets and exchange rate determination",
      "Exchange rate systems: free floating, managed floating, fixed",
      "Appreciation and depreciation: causes and effects",
      "Corrections of balance of payments disequilibria",
      "Terms of trade"
    ],
    "learning_objectives": [
      "Explain the structure of the balance of payments and record transactions in the correct account",
      "Analyse how exchange rates are determined by supply and demand for currencies",
      "Compare exchange rate systems and their suitability",
      "Explain the causes and effects of currency appreciation and depreciation",
      "Discuss measures to correct a balance of payments deficit",
      "Calculate and interpret the terms of trade"
    ],
    "key_concepts": [
      "Balance of payments accounts",
      "Exchange rate determination",
      "Floating vs fixed systems",
      "Appreciation and depreciation",
      "Disequilibria corrections",
      "Terms of trade"
    ],
    "assessment_objectives": [
      "Interpret international finance data and diagrams",
      "Evaluate exchange rate policies and corrective measures",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Diagram question on currency supply and demand",
      "Data response using balance of payments figures",
      "Essay on the effects of rand depreciation",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "The Public Sector and Fiscal Policy"
    ],
    "common_misconceptions": [
      "Recording foreign direct investment in the current account",
      "Believing depreciation always improves the trade balance immediately",
      "Confusing the balance of trade with the balance of payments",
      "Assuming a strong currency is always desirable",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "With the aid of a diagram, explain how an increase in demand for South African exports affects the value of the rand.",
      "Study the balance of payments extract and identify the account in which each transaction is recorded.",
      "Discuss the effects of a depreciation of the rand on households and on exporting firms.",
      "Explain two measures the authorities could use to address a persistent current account deficit."
    ]
  },
  {
    "name": "Economic Growth, Development and Globalisation",
    "subtopics": [
      "Growth and development: definitions and measures",
      "Demand-side and supply-side approaches to growth",
      "The North-South divide",
      "South Africa's growth and development policies",
      "Industrial development policies and regional development",
      "Appropriateness of policies in the international context",
      "Globalisation: features, effects and responses",
      "Trade policy: import substitution vs export promotion"
    ],
    "learning_objectives": [
      "Distinguish economic growth from economic development and their indicators",
      "Explain demand-side and supply-side approaches to stimulating growth",
      "Analyse the North-South divide and its implications",
      "Evaluate South African growth, development and industrial policies",
      "Compare import substitution with export promotion strategies",
      "Assess the benefits and costs of globalisation for developing economies"
    ],
    "key_concepts": [
      "Growth vs development",
      "Demand-side and supply-side policies",
      "North-South divide",
      "Industrial policy",
      "Import substitution vs export promotion",
      "Globalisation"
    ],
    "assessment_objectives": [
      "Explain growth and development strategies",
      "Evaluate policy appropriateness in local and global contexts",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Paragraph on supply-side measures",
      "Essay evaluating export promotion",
      "Data response on development indicators",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Foreign Exchange Markets and the Balance of Payments"
    ],
    "common_misconceptions": [
      "Using growth and development interchangeably",
      "Believing import substitution guarantees industrialisation",
      "Treating globalisation as uniformly positive or negative",
      "Assuming supply-side policy works only in the long run and demand-side only in the short run without qualification",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Distinguish between economic growth and economic development.",
      "Discuss export promotion as a strategy for South African industrial development, including its advantages and disadvantages.",
      "Briefly discuss the effects of globalisation on developing countries.",
      "Evaluate the appropriateness of supply-side measures in addressing South Africa's growth constraints."
    ]
  },
  {
    "name": "Perfect Markets and Imperfect Markets",
    "subtopics": [
      "Perfect competition: characteristics and demand curve of the firm",
      "Short-run equilibrium: profit maximisation where MR = MC",
      "Economic profit, normal profit and losses",
      "Long-run equilibrium under perfect competition",
      "Monopoly: characteristics, equilibrium, comparison with perfect competition",
      "Oligopoly and monopolistic competition: characteristics and behaviour",
      "Market structure comparisons and competition policy"
    ],
    "learning_objectives": [
      "Describe the characteristics of perfect competition and explain the firm's horizontal demand curve",
      "Determine equilibrium output using the MR = MC rule with cost and revenue curves",
      "Illustrate economic profit, normal profit and economic loss graphically",
      "Explain the adjustment to long-run equilibrium under perfect competition",
      "Analyse monopoly equilibrium and compare it with perfect competition",
      "Describe the features of oligopoly and monopolistic competition including non-price competition",
      "Discuss competition policy responses to market power"
    ],
    "key_concepts": [
      "Market structures",
      "MR = MC rule",
      "Economic vs normal profit",
      "Long-run adjustment",
      "Monopoly",
      "Oligopoly behaviour",
      "Competition policy"
    ],
    "assessment_objectives": [
      "Draw and interpret cost-revenue diagrams accurately",
      "Compare market structures and evaluate their outcomes",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Diagram question showing profit or loss positions",
      "Paragraph comparing monopoly with perfect competition",
      "Essay on the characteristics and behaviour of oligopolies",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Grade 11 Economics foundations"
    ],
    "common_misconceptions": [
      "Drawing the perfectly competitive firm's demand curve as downward sloping",
      "Believing monopolies can charge any price without losing sales",
      "Confusing normal profit with zero accounting profit",
      "Assuming collusion is the only behaviour in oligopoly",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "With the aid of a diagram, explain the economic loss position of a firm under perfect competition in the short run.",
      "Compare the output and price outcomes of a monopoly with those of a perfectly competitive industry.",
      "Explain why firms in an oligopoly prefer non-price competition.",
      "Use the MR = MC rule to determine the profit-maximising level of output from the table provided."
    ]
  },
  {
    "name": "Market Failure and State Intervention",
    "subtopics": [
      "Causes of market failure: externalities, public goods, imperfect information, immobility",
      "Positive and negative externalities with diagrams",
      "Cost-benefit analysis",
      "State intervention: taxes, subsidies, price controls",
      "Minimum and maximum prices and their effects",
      "Minimum wages in the labour market",
      "Consequences and limits of intervention"
    ],
    "learning_objectives": [
      "Explain the main causes of market failure",
      "Illustrate positive and negative externalities using social vs private cost-benefit diagrams",
      "Apply cost-benefit analysis to public projects",
      "Analyse the effects of maximum prices, minimum prices and subsidies with diagrams",
      "Discuss minimum wages and their effects on employment and incomes",
      "Evaluate the effectiveness and unintended consequences of state intervention"
    ],
    "key_concepts": [
      "Market failure",
      "Externalities",
      "Social vs private costs",
      "Cost-benefit analysis",
      "Price controls",
      "Minimum wage"
    ],
    "assessment_objectives": [
      "Illustrate market failure and intervention graphically",
      "Evaluate intervention outcomes with balanced argument",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Diagram question on a negative externality",
      "Data response on a price control scenario",
      "Essay evaluating state intervention in markets",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Perfect Markets and Imperfect Markets"
    ],
    "common_misconceptions": [
      "Placing a maximum price above equilibrium and expecting an effect",
      "Treating all externalities as negative",
      "Believing subsidies have no opportunity cost",
      "Assuming minimum wages affect all sectors identically",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "With the aid of a diagram, explain how a negative externality leads to overproduction in a free market.",
      "Analyse the effects of a maximum price set below equilibrium in the rental housing market.",
      "Discuss arguments for and against a national minimum wage.",
      "Explain how cost-benefit analysis assists government in deciding whether to build a new dam."
    ]
  },
  {
    "name": "Contemporary Economic Issues: Inflation, Tourism and Environment",
    "subtopics": [
      "Inflation: types, measurement, causes and consequences",
      "Demand-pull and cost-push inflation with diagrams",
      "Anti-inflation policy: monetary and fiscal measures",
      "Tourism: reasons for growth, effects and benefits",
      "Tourism policy suggestions for South Africa",
      "Environmental sustainability: problems and measures",
      "International environmental agreements and granting of property rights"
    ],
    "learning_objectives": [
      "Distinguish types of inflation and how the CPI measures inflation",
      "Explain demand-pull and cost-push inflation with illustrations",
      "Evaluate measures used to combat inflation including inflation targeting",
      "Analyse the economic effects of tourism on growth, employment and externalities",
      "Suggest policies to expand tourism's benefits",
      "Explain environmental problems and evaluate measures such as taxes, permits and property rights",
      "Discuss major international environmental agreements in broad terms"
    ],
    "key_concepts": [
      "CPI and inflation targeting",
      "Demand-pull vs cost-push",
      "Anti-inflation policy",
      "Tourism multiplier",
      "Sustainability",
      "Market-based environmental instruments"
    ],
    "assessment_objectives": [
      "Analyse contemporary issues with data and diagrams",
      "Evaluate policy responses to inflation, tourism and environmental challenges",
      "Demonstrate higher-order analysis, evaluation and synthesis expected at IEB level, including integration across topics",
      "Senior Phase (Grade 8) depth: foundational treatment of this strand — introductory concepts and skills; full IEB NSC examination demand is reached in Grade 12."
    ],
    "typical_question_styles": [
      "Data response using CPI figures",
      "Paragraph on the effects of tourism",
      "Essay on measures to ensure environmental sustainability",
      "Extended discursive/response questions requiring integrated argument across topics with independently structured answers (IEB style)",
      "Short scaffolded questions with worked-example support, appropriate to Grade 8"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Market Failure and State Intervention"
    ],
    "common_misconceptions": [
      "Believing falling inflation means falling prices",
      "Attributing all inflation to money supply growth alone",
      "Counting all tourism spending as net benefit without leakages",
      "Treating environmental protection and growth as always opposed",
      "Preparing only for structured recall questions and being caught out by IEB's emphasis on unseen application, integrated scenarios and independently structured extended responses"
    ],
    "exemplar_question_stems": [
      "Distinguish between demand-pull and cost-push inflation, using diagrams.",
      "Evaluate inflation targeting as a policy to maintain price stability in South Africa.",
      "Briefly discuss the benefits of tourism for a developing economy.",
      "Explain how the granting of property rights can help to protect environmental resources."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
