-- Verified curriculum seed: ZIMSEC Form 3 English Literature
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 3 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 3', 'English Literature', $topics$
[
  {
    "name": "Studying the Novel and Short Story",
    "subtopics": [
      "Plot structure: exposition, conflict, climax, resolution",
      "Characterisation: direct and indirect methods",
      "Setting and its significance",
      "Narrative point of view",
      "Themes and how they develop",
      "African and Zimbabwean prose traditions",
      "Keeping textual evidence: quotations and episodes"
    ],
    "learning_objectives": [
      "Trace the development of plot and identify major turning points in a set novel",
      "Analyse how a writer reveals character through speech, action and description",
      "Explain the contribution of setting to atmosphere and meaning",
      "Identify the narrative perspective and its effect on the reader",
      "Trace major themes across a novel with supporting episodes",
      "Select and integrate short quotations as evidence in answers"
    ],
    "key_concepts": [
      "Plot and subplot",
      "Characterisation",
      "Setting",
      "Point of view",
      "Theme",
      "Textual evidence"
    ],
    "assessment_objectives": [
      "Demonstrate detailed knowledge of the set prose text",
      "Analyse how the writer's choices shape meaning and communicate personal response",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Essay question on a character or theme in the set novel",
      "Context/extract question asking what happens before and after a passage",
      "Discuss-the-significance question on an episode or setting",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 20,
    "prerequisites": [
      "Foundational literacy and numeracy from earlier grades"
    ],
    "common_misconceptions": [
      "Retelling the story instead of answering the question",
      "Treating characters as real people rather than authorial constructs",
      "Quoting long passages instead of short, purposeful evidence",
      "Ignoring the ending when discussing theme development"
    ],
    "exemplar_question_stems": [
      "Show how the main character in your set novel changes from the beginning to the end of the story.",
      "With close reference to the text, discuss how the writer presents the conflict between tradition and modernity.",
      "Choose an episode in the novel that you find memorable and show how it contributes to the development of the plot.",
      "How does the setting of the novel help the reader to understand the struggles of the characters?"
    ]
  },
  {
    "name": "Studying Drama",
    "subtopics": [
      "Dramatic structure: acts, scenes, climax",
      "Dialogue, monologue and soliloquy",
      "Stage directions and their significance",
      "Dramatic irony, tension and suspense",
      "Character motivation and conflict on stage",
      "Themes in the set play",
      "The play in performance: audience effect"
    ],
    "learning_objectives": [
      "Describe the structure of the set play and the function of key scenes",
      "Analyse how dialogue and soliloquy reveal character and motive",
      "Interpret stage directions as clues to mood, movement and relationships",
      "Identify dramatic irony and explain its effect on the audience",
      "Trace the development of central conflicts to their resolution",
      "Discuss themes with reference to specific scenes and speeches"
    ],
    "key_concepts": [
      "Dramatic structure",
      "Soliloquy and aside",
      "Stage directions",
      "Dramatic irony",
      "Conflict",
      "Audience response"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of the set play as text and performance",
      "Analyse dramatic techniques and their effects on an audience",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Essay on a character's role or a theme in the play",
      "Extract-based question on what a passage reveals and its dramatic effect",
      "Question on how tension is built in a particular scene",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 20,
    "prerequisites": [
      "Foundational literacy and numeracy from earlier grades"
    ],
    "common_misconceptions": [
      "Analysing a play as if it were a novel, ignoring performance",
      "Confusing dramatic irony with coincidence",
      "Overlooking stage directions as mere instructions",
      "Assuming the audience knows only what the characters know"
    ],
    "exemplar_question_stems": [
      "Show how the playwright builds tension in one scene of your set play that you found gripping.",
      "What does the extract reveal about the relationship between the two speakers? Support your answer with details from the passage.",
      "Discuss the role of the minor characters in advancing the action of the play.",
      "How does the playwright use dramatic irony to hold the audience's interest? Refer closely to two moments in the play."
    ]
  },
  {
    "name": "Shakespeare Study",
    "subtopics": [
      "Shakespeare's language: blank verse, prose, imagery",
      "Understanding archaic vocabulary in context",
      "Major characters and their motives",
      "Key soliloquies and speeches",
      "Themes: ambition, love, justice, appearance vs reality",
      "The Elizabethan stage and conventions",
      "Relating Shakespeare's concerns to modern life"
    ],
    "learning_objectives": [
      "Paraphrase passages of Shakespearean verse accurately",
      "Analyse imagery and figurative language in key speeches",
      "Explain the motives and development of major characters",
      "Interpret soliloquies as windows into a character's mind",
      "Discuss the play's central themes with textual support",
      "Connect the play's issues to contemporary experience"
    ],
    "key_concepts": [
      "Blank verse",
      "Imagery",
      "Soliloquy",
      "Tragic/comic convention",
      "Theme",
      "Dramatic convention"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of Shakespeare's language and stagecraft",
      "Analyse character, theme and dramatic effect with textual evidence",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Passage-based question requiring explanation and comment",
      "Character essay tracing development across the play",
      "Theme essay with reference to at least three episodes",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Studying Drama"
    ],
    "common_misconceptions": [
      "Translating word-for-word instead of grasping the sense of a speech",
      "Believing verse and prose are assigned to characters at random",
      "Treating soliloquies as conversations overheard by other characters",
      "Assuming Shakespeare's themes are irrelevant to modern readers"
    ],
    "exemplar_question_stems": [
      "Read the following speech from your Shakespeare set text. Explain what the speaker is saying and comment on the imagery used.",
      "Trace the change in the main character's fortunes, showing what causes the change.",
      "Discuss the theme of appearance versus reality in the play, referring closely to at least three episodes.",
      "What impressions of the speaker does the audience form from this soliloquy? Support your answer from the passage."
    ]
  },
  {
    "name": "Studying Poetry",
    "subtopics": [
      "Poetic forms: sonnet, ballad, lyric, free verse",
      "Imagery: simile, metaphor, personification, symbolism",
      "Sound devices: rhyme, rhythm, alliteration, assonance",
      "Tone, mood and voice",
      "African and Zimbabwean poetry: oral traditions and praise poetry",
      "Analysing a poem's structure and development",
      "Comparing poems on similar subjects"
    ],
    "learning_objectives": [
      "Identify poetic forms and explain how form supports meaning",
      "Analyse imagery and explain the effects created",
      "Identify sound devices and link them to mood and emphasis",
      "Determine the tone and voice of a poem with evidence",
      "Discuss features of oral and praise poetry within the African tradition",
      "Compare two poems in terms of subject, technique and effect"
    ],
    "key_concepts": [
      "Form and structure",
      "Imagery",
      "Sound devices",
      "Tone and mood",
      "Oral tradition",
      "Comparison"
    ],
    "assessment_objectives": [
      "Analyse poetic techniques and their effects",
      "Communicate informed personal response to poetry",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Essay on a studied poem's theme and techniques",
      "Comparison question on two poems from the anthology",
      "Line-by-line commentary question on imagery or sound",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Foundational literacy and numeracy from earlier grades"
    ],
    "common_misconceptions": [
      "Identifying devices without explaining their effect",
      "Assuming every poem must rhyme to be poetry",
      "Confusing the poet with the speaker of the poem",
      "Paraphrasing a poem line by line instead of analysing it"
    ],
    "exemplar_question_stems": [
      "Choose one poem from your anthology that deals with loss. Show how the poet conveys the speaker's feelings.",
      "Compare how two poems you have studied present the experience of migration or exile.",
      "Discuss the use of imagery in one poem that made a strong impression on you.",
      "How does the poet use rhythm and repetition to create the effect of a praise song?"
    ]
  },
  {
    "name": "Unseen Literary Criticism",
    "subtopics": [
      "Approaching an unseen prose passage",
      "Approaching an unseen poem",
      "Identifying subject, tone and purpose quickly",
      "Commenting on diction and figurative language",
      "Structuring a critical response",
      "Supporting every point with evidence"
    ],
    "learning_objectives": [
      "Read an unfamiliar passage or poem and establish its literal meaning",
      "Identify the tone, mood and purpose of an unseen text",
      "Analyse the writer's choice of words and images and their effects",
      "Organise a critical commentary with introduction, development and conclusion",
      "Support all critical claims with brief quotations",
      "Manage time effectively when responding to unseen material"
    ],
    "key_concepts": [
      "First reading strategy",
      "Diction",
      "Tone recognition",
      "Effect analysis",
      "Evidence-based commentary",
      "Structure of response"
    ],
    "assessment_objectives": [
      "Respond critically to unfamiliar literary material",
      "Analyse language and style with appropriate terminology",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Unseen poem with guided questions on meaning and technique",
      "Unseen prose extract with questions on character, mood and style",
      "Open commentary question with bullet-point prompts",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Studying Poetry",
      "Studying the Novel and Short Story"
    ],
    "common_misconceptions": [
      "Panicking and summarising instead of analysing",
      "Forcing every known device onto a text where it does not appear",
      "Writing about what the text should say rather than what it says",
      "Leaving claims unsupported by quotation"
    ],
    "exemplar_question_stems": [
      "Read the following poem, which you have not seen before. What is the speaker's attitude towards the city, and how is it conveyed?",
      "In the passage below, how does the writer create sympathy for the old woman? Refer closely to the words used.",
      "Comment on the effectiveness of the description of the storm in the extract, paying attention to imagery and sentence structure.",
      "What feelings does this poem leave you with? Show how the poet's choice of words creates those feelings."
    ]
  },
  {
    "name": "Essay Technique and Context Questions",
    "subtopics": [
      "Understanding the demands of question words: show, discuss, trace, compare",
      "Planning an argument before writing",
      "Paragraphing: point, evidence, comment",
      "Using quotations effectively",
      "Answering passage-based (context) questions",
      "Avoiding narration and irrelevance",
      "Timed writing practice and revision strategies"
    ],
    "learning_objectives": [
      "Interpret essay questions accurately and identify their key demands",
      "Plan essays with a clear line of argument",
      "Construct paragraphs that make a point, support it and comment on it",
      "Blend short quotations smoothly into sentences",
      "Answer context questions by locating, explaining and analysing the extract",
      "Allocate examination time across questions effectively"
    ],
    "key_concepts": [
      "Question analysis",
      "Argument planning",
      "PEC paragraphing",
      "Quotation integration",
      "Context technique",
      "Time management"
    ],
    "assessment_objectives": [
      "Communicate a relevant, structured and supported argument",
      "Demonstrate sustained engagement with the terms of the question",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Any essay or context question across the set texts",
      "Practice tasks in planning and paragraph construction",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Studying the Novel and Short Story",
      "Studying Drama"
    ],
    "common_misconceptions": [
      "Believing that retelling the plot answers the question",
      "Starting to write without a plan",
      "Using quotations as decoration rather than evidence",
      "Spending too long on one question and abandoning another"
    ],
    "exemplar_question_stems": [
      "Plan and write an essay in response to: 'Trace the events that lead to the downfall of the main character, showing who is most to blame.'",
      "Rewrite the following narrative paragraph so that it makes an analytical point supported by evidence.",
      "Using the extract provided from your set text, explain what has just happened, what the passage reveals about the speaker, and its importance to the play as a whole.",
      "Draft an essay plan comparing the treatment of betrayal in your two set texts."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
