-- Verified curriculum seed: CAMB Grade 9 Accounting
-- Generated by adapting the merged IGCSE template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 9 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('CAMB', 'Grade 9', 'Accounting', $topics$
[
  {
    "name": "Fundamentals of Accounting and the Double Entry System",
    "subtopics": [
      "Purpose of accounting and bookkeeping distinction",
      "The accounting equation",
      "Double entry for assets, liabilities, capital, income and expenses",
      "The ledger and division of the ledger",
      "Balancing accounts",
      "The trial balance and its limitations"
    ],
    "learning_objectives": [
      "Apply the accounting equation to transactions",
      "Record transactions using double entry principles",
      "Balance ledger accounts and bring down balances",
      "Prepare a trial balance and explain which errors it cannot reveal"
    ],
    "key_concepts": [
      "Assets = Capital + Liabilities",
      "Debit and credit rules by account class",
      "Personal, real and nominal accounts",
      "Trial balance as arithmetic check only",
      "Errors not revealed: omission, commission, principle, original entry, reversal, compensating"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of double entry procedures",
      "Record transactions accurately in ledger accounts",
      "Explain the purpose and limitations of the trial balance",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Complete the ledger accounts to record the given transactions",
      "Prepare a trial balance from the list of balances",
      "State two errors that do not affect the agreement of the trial balance",
      "Show the effect of each transaction on the accounting equation",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Basic arithmetic"
    ],
    "common_misconceptions": [
      "Believing debit always means increase for every account type",
      "Thinking a balanced trial balance proves the books are error-free",
      "Confusing the business's records with the owner's personal finances (entity concept)",
      "Reversing debit and credit entries for expenses and income"
    ],
    "exemplar_question_stems": [
      "Record the following transactions in the ledger of the trader and balance the accounts at month end",
      "The trial balance totals agree but two errors have been made; name and explain the types of error"
    ]
  },
  {
    "name": "Books of Prime Entry and Business Documents",
    "subtopics": [
      "Sales, purchases and returns journals",
      "The general journal",
      "Cash book (two and three column) and petty cash book",
      "Business documents: invoice, credit note, statement, cheque, receipt",
      "Trade and cash discounts",
      "The imprest system"
    ],
    "learning_objectives": [
      "Match business documents to the transactions they evidence",
      "Write up books of prime entry from documents",
      "Prepare two- and three-column cash books including discounts",
      "Operate a petty cash book under the imprest system"
    ],
    "key_concepts": [
      "Prime entry before ledger posting",
      "Trade discount never recorded in accounts",
      "Discount allowed vs discount received",
      "Contra entries in the cash book",
      "Restoring the imprest"
    ],
    "assessment_objectives": [
      "Process source documents into the correct books of prime entry",
      "Post totals and individual entries to the ledgers",
      "Apply discount treatment correctly",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Enter the transactions in the sales journal and post to the ledger",
      "Prepare the three-column cash book for the month",
      "Write up the petty cash book and show the amount required to restore the imprest",
      "Name the document issued when goods are returned",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Double entry strand"
    ],
    "common_misconceptions": [
      "Recording trade discount in the ledger accounts",
      "Treating discount columns in the cash book as part of double entry rather than memoranda totals",
      "Confusing debit notes with credit notes",
      "Posting the petty cash analysis column totals to the wrong side"
    ],
    "exemplar_question_stems": [
      "From the invoices and credit notes provided, write up the purchases and purchases returns journals",
      "Prepare the cash book, balance it, and state the meaning of the closing bank balance"
    ]
  },
  {
    "name": "Bank Reconciliation and Control Accounts",
    "subtopics": [
      "Updating the cash book from the bank statement",
      "Preparing the bank reconciliation statement",
      "Causes of difference: unpresented cheques, uncredited deposits, bank charges, dishonoured cheques",
      "Sales and purchases ledger control accounts",
      "Contra entries between control accounts",
      "Uses and limitations of control accounts"
    ],
    "learning_objectives": [
      "Update the cash book with items appearing only on the bank statement",
      "Reconcile the updated cash book balance to the bank statement balance",
      "Prepare sales and purchases ledger control accounts",
      "Explain the purposes of control accounts in locating errors and deterring fraud"
    ],
    "key_concepts": [
      "Timing differences vs items requiring cash book entries",
      "Bank statement debit = customer credit perspective",
      "Control account sources from books of prime entry",
      "Set-off/contra between ledgers",
      "Credit balances on sales ledger control"
    ],
    "assessment_objectives": [
      "Prepare reconciliations and control accounts accurately",
      "Explain causes of differences and the purpose of each statement",
      "Interpret balances produced",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Update the cash book and prepare a bank reconciliation statement at the month end",
      "Prepare the sales ledger control account from the totals provided",
      "Explain two advantages of maintaining control accounts",
      "Give one reason for a credit balance on a customer's account",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Cash book strand",
      "Double entry strand"
    ],
    "common_misconceptions": [
      "Entering unpresented cheques in the cash book instead of the reconciliation statement",
      "Confusing the direction of bank statement debits and credits",
      "Building control accounts from individual customer accounts rather than prime entry totals",
      "Forgetting dishonoured cheques increase the debtor balance again"
    ],
    "exemplar_question_stems": [
      "The cash book shows a different balance from the bank statement; update the cash book and reconcile the remaining difference",
      "Prepare the purchases ledger control account and explain the meaning of its closing balance"
    ]
  },
  {
    "name": "Adjustments: Depreciation, Provisions, Accruals and Prepayments",
    "subtopics": [
      "Capital vs revenue expenditure and receipts",
      "Depreciation: straight line, reducing balance, revaluation",
      "Disposal of non-current assets",
      "Accrued and prepaid expenses and income",
      "Irrecoverable debts and provision for doubtful debts",
      "Effects of adjustments on profit and the balance sheet"
    ],
    "learning_objectives": [
      "Classify expenditure as capital or revenue and explain the effect of errors",
      "Calculate and record depreciation by each method",
      "Prepare disposal accounts and calculate profit or loss on disposal",
      "Adjust ledger accounts and final statements for accruals, prepayments and doubtful debts"
    ],
    "key_concepts": [
      "Matching/accruals concept driving adjustments",
      "Depreciation as allocation, not valuation",
      "Provision creation and subsequent adjustment",
      "Expense account balances carried down",
      "Net realisable value of trade receivables"
    ],
    "assessment_objectives": [
      "Calculate adjustment figures accurately",
      "Record adjustments in ledger accounts and final statements",
      "Explain the accounting concepts behind each adjustment",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Calculate the annual depreciation charge under each method and comment on which suits the asset",
      "Prepare the disposal account and calculate the profit or loss on sale",
      "Prepare the expense account showing the transfer to the income statement and the balance carried down",
      "Show the entries to create and later adjust the provision for doubtful debts",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Double entry strand"
    ],
    "common_misconceptions": [
      "Treating depreciation as saving cash for replacement",
      "Charging a full year's depreciation regardless of the stated policy on acquisition/disposal",
      "Confusing irrecoverable debts written off with the provision for doubtful debts",
      "Adding prepaid expenses to the expense figure instead of deducting"
    ],
    "exemplar_question_stems": [
      "A machine bought for the given cost is sold after three years; prepare the disposal account using reducing balance depreciation",
      "Rent of the given amount was paid during the year, of which part relates to next year; prepare the rent account"
    ]
  },
  {
    "name": "Financial Statements of Sole Traders and Partnerships",
    "subtopics": [
      "Income statement for a trader",
      "Statement of financial position",
      "Adjustments incorporated into final statements",
      "Partnership appropriation account",
      "Partners' capital and current accounts",
      "Interest on capital, drawings and partners' salaries"
    ],
    "learning_objectives": [
      "Prepare income statements incorporating all adjustments",
      "Prepare classified statements of financial position",
      "Prepare appropriation accounts dividing profit under the agreement",
      "Maintain partners' capital and current accounts"
    ],
    "key_concepts": [
      "Gross profit vs profit for the year",
      "Current vs non-current classification",
      "Residual profit sharing ratio",
      "Fixed vs fluctuating capital accounts",
      "Debit balance on a current account meaning"
    ],
    "assessment_objectives": [
      "Prepare final statements in good format with adjustments",
      "Apply partnership agreement terms accurately",
      "Interpret figures produced in the statements",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Prepare the income statement for the year from the trial balance and notes",
      "Prepare the statement of financial position at the year end",
      "Prepare the appropriation account and the partners' current accounts",
      "Explain why interest on drawings is charged to partners",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Adjustments strand"
    ],
    "common_misconceptions": [
      "Including drawings as an expense in the income statement",
      "Misclassifying non-current and current items in the balance sheet",
      "Sharing all profit in the ratio while ignoring salaries and interest first",
      "Entering partners' salaries as a business expense rather than appropriation"
    ],
    "exemplar_question_stems": [
      "From the trial balance and the five adjustment notes, prepare the income statement for the year",
      "The partnership agreement provides interest on capital and a partner salary; prepare the appropriation account and current accounts"
    ]
  },
  {
    "name": "Incomplete Records, Non-Profit Organisations and Manufacturing",
    "subtopics": [
      "Calculating profit from changes in capital",
      "Constructing accounts from incomplete information",
      "Mark-up, margin and inventory relationships",
      "Receipts and payments vs income and expenditure accounts",
      "Subscriptions account and special funds",
      "Manufacturing account: prime cost and factory overheads"
    ],
    "learning_objectives": [
      "Derive missing figures using control accounts and ratios",
      "Compute profit where full records are unavailable",
      "Prepare income and expenditure accounts and subscription workings for clubs",
      "Prepare manufacturing accounts distinguishing cost classifications"
    ],
    "key_concepts": [
      "Opening statement of affairs",
      "Margin vs mark-up conversion",
      "Accumulated fund vs capital",
      "Subscriptions in arrears and in advance",
      "Prime cost, factory overhead, work in progress adjustment"
    ],
    "assessment_objectives": [
      "Reconstruct financial information from incomplete data",
      "Prepare statements appropriate to non-trading organisations",
      "Classify manufacturing costs correctly",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Calculate credit sales using the trade receivables control account",
      "Calculate the profit for the year from the change in net assets",
      "Prepare the subscriptions account showing the transfer to income and expenditure",
      "Prepare the manufacturing account and state the cost of production",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Financial statements strand",
      "Control accounts strand"
    ],
    "common_misconceptions": [
      "Confusing margin (on selling price) with mark-up (on cost)",
      "Treating receipts and payments account as equivalent to income and expenditure",
      "Counting subscriptions received as income regardless of the period they relate to",
      "Including factory overheads in prime cost"
    ],
    "exemplar_question_stems": [
      "A trader lost most records in a flood; use the statements of affairs to calculate the profit for the year",
      "The club's records show subscription receipts including arrears and advances; prepare the subscriptions account"
    ]
  },
  {
    "name": "Limited Companies, Analysis and Interpretation",
    "subtopics": [
      "Issue of shares and debentures",
      "Statement of changes in equity basics",
      "Company income statement and balance sheet features",
      "Ratios: gross margin, profit margin, ROCE, current ratio, liquid ratio, rate of inventory turnover, trade receivables/payables days",
      "Interpreting and commenting on ratio movements",
      "Inter-firm comparison and limitations of ratios"
    ],
    "learning_objectives": [
      "Record share and debenture issues and explain their differences",
      "Prepare simple company financial statements",
      "Calculate the standard ratio set accurately",
      "Interpret ratios to comment on profitability and liquidity, recognising limitations"
    ],
    "key_concepts": [
      "Ordinary shares vs debentures (risk and return)",
      "Dividends vs interest treatment",
      "Profitability vs liquidity distinction",
      "Working capital management",
      "Non-financial factors and different accounting policies limiting comparison"
    ],
    "assessment_objectives": [
      "Prepare company records and statements accurately",
      "Calculate and interpret accounting ratios",
      "Evaluate business performance with awareness of limitations",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Calculate the given ratios to two decimal places and comment on the change from last year",
      "Suggest two reasons for the fall in gross margin",
      "Explain the difference between a share and a debenture from an investor's viewpoint",
      "State two limitations of using ratios to compare two businesses",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Financial statements strand"
    ],
    "common_misconceptions": [
      "Treating debenture interest as an appropriation like dividends",
      "Believing a very high current ratio is automatically good",
      "Comparing ratios across firms with different year ends or policies without caveats",
      "Inverting receivables days and payables days formulas"
    ],
    "exemplar_question_stems": [
      "Calculate the current ratio and liquid ratio and explain why they move in different directions this year",
      "The rate of inventory turnover fell from 8 times to 5 times; suggest two possible causes and one consequence"
    ]
  },
  {
    "name": "Accounting Principles, Policies and Ethics",
    "subtopics": [
      "Concepts: going concern, accruals/matching, consistency, prudence, materiality, business entity, duality, money measurement, realisation",
      "International accounting standards awareness",
      "Objectives of financial statements and users' needs",
      "Qualitative characteristics: relevance, reliability, comparability, understandability",
      "Professional ethics in accounting",
      "Correction of errors and suspense accounts"
    ],
    "learning_objectives": [
      "Explain and apply each accounting concept to given scenarios",
      "Identify which concept justifies or forbids a treatment",
      "Discuss the needs of different users of accounts",
      "Correct errors through the journal and suspense account and recalculate profit"
    ],
    "key_concepts": [
      "Concept-to-scenario mapping",
      "Users: owners, lenders, suppliers, employees, government",
      "Neutrality and faithful representation",
      "Suspense account as temporary difference holder",
      "Effect of error correction on draft profit"
    ],
    "assessment_objectives": [
      "Explain principles and apply them to practical situations",
      "Identify users and their information needs",
      "Correct errors and adjust profit accordingly",
      "Cambridge Lower Secondary (Grade 9) depth: developing treatment of this strand — consolidating foundations in readiness for the IGCSE course."
    ],
    "typical_question_styles": [
      "Name the accounting principle applied when the treatment described is followed",
      "Explain why the trader should not record the item at its expected selling price",
      "Prepare journal entries to correct the errors and the suspense account",
      "Prepare a statement showing the corrected profit for the year",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "All preceding strands"
    ],
    "common_misconceptions": [
      "Using prudence to justify deliberate understatement of profit",
      "Confusing consistency (same method over time) with comparability across firms",
      "Opening a suspense account for errors that do not affect trial balance agreement",
      "Adjusting profit in the wrong direction when correcting expense errors"
    ],
    "exemplar_question_stems": [
      "The owner recorded personal groceries as business purchases; name the concept breached and explain the correction",
      "The trial balance failed to agree and a suspense account was opened; journalise the corrections and show the effect on profit"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
