UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/algebra-and-trigonometry-2e%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/college-algebra-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/college-algebra-2e%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/precalculus-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/precalculus-2e%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/introductory-statistics%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/biology-2e%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsofBiology-WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/concepts-biology%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/chemistry%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/college-physics%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/university-physics-volume-1_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/university-physics-volume-1%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/university-physics-volume-2_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/university-physics-volume-2%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/university-physics-volume-3_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/university-physics-volume-3%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-1_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/calculus-volume-1%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-2_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/calculus-volume-2%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-3_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/calculus-volume-3%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/microbiology_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/microbiology%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/anatomy-and-physiology-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/anatomy-and-physiology%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/principles-economics-3e%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/principles-microeconomics-3e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/principles-microeconomics-3e%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/principles-macroeconomics-3e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/principles-macroeconomics-3e%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/introduction-sociology-3e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/introduction-sociology-3e%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/astronomy-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/astronomy-2e%' AND pdf_url NOT LIKE '%assets.openstax.org%';
UPDATE public.library_system_resources SET pdf_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra-2e_-_WEB.pdf' WHERE pdf_url ILIKE '%openstax.org/details/books/prealgebra-2e%' AND pdf_url NOT LIKE '%assets.openstax.org%';

INSERT INTO public.library_system_resources
  (kind, curriculum, subject, topic, title, description, pdf_url, thumbnail_url, grade_levels)
SELECT v.kind, c.curriculum, v.subject, v.topic, v.title, v.description, v.pdf_url, v.thumbnail_url, v.grade_levels
FROM (VALUES
  ('textbook','Study Skills','Study Techniques & Time Management','College Success — How to Study, Manage Time & Thrive','OpenStax College Success covers managing time, reading strategies, memory techniques, note-taking, test preparation, stress and goal setting. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/College_Success_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/College_Success_-_WEB.pdf',ARRAY['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Study Techniques & Time Management','College Success Concise — Essential Study & Life Skills Guide','A condensed version of College Success. Planning, reading, note-taking, exam prep, wellbeing. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/college-success-concise_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college-success-concise_-_WEB.pdf',ARRAY['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Psychology of Learning','Lifespan Development — Understanding How We Learn & Grow','Cognitive development, memory, motivation, learning styles, emotional regulation. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/Lifespan_Development_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Lifespan_Development_-_WEB.pdf',ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Memory & Motivation','Psychology 2e — Memory, Learning & Motivation (OpenStax)','Learning, memory, thinking, motivation and emotion. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/psychology-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/psychology-2e_-_WEB.pdf',ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Academic Writing & Research','Writing Guide with Handbook — Academic Writing & Research Skills','Writing process, research, argument construction, citation. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf',ARRAY['Grade 9','Grade 10','Grade 11','Grade 12','Form 3','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Goal Setting & Planning','Principles of Management — Goal Setting, Planning & Leadership','SMART goals, time management, decision-making, self-leadership. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-management_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/principles-management_-_WEB.pdf',ARRAY['Grade 11','Grade 12','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Motivation & Teamwork','Organisational Behavior — Motivation, Communication & Teamwork','Motivation theories, communication, group dynamics, stress. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/organizational-behavior_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/organizational-behavior_-_WEB.pdf',ARRAY['Grade 11','Grade 12','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Critical Thinking & Ethics','Business Ethics — Critical Thinking, Reasoning & Decision Making','Critical-thinking and ethical-reasoning skills. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/business-ethics_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/business-ethics_-_WEB.pdf',ARRAY['Grade 11','Grade 12','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Logical Thinking & Data','Introductory Statistics — Logical Thinking, Data & Problem Solving','Quantitative reasoning, pattern recognition, problem solving. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Decision Making & Resources','Principles of Microeconomics — Decision Making & Resource Management','Opportunity cost, incentives, trade-offs. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-microeconomics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['Grade 11','Grade 12','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Society & Wellbeing','Introduction to Sociology — Society, Identity & Wellbeing','Social structures, identity, inequality, collective behaviour. CC-BY.','https://assets.openstax.org/oscms-prodcms/media/documents/introduction-sociology-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/introduction-sociology-3e_-_WEB.pdf',ARRAY['Grade 10','Grade 11','Grade 12','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level']),
  ('textbook','Study Skills','Study Techniques','How to Study — A Classic Guide to Study Technique (Public Domain)','Concentration, memory, reading, note-taking, exam prep. Public domain.','https://www.gutenberg.org/files/16317/16317-h/16317-h.htm','https://placehold.co/600x800/7c3aed/ffffff?text=How+to+Study%0AClassic+Guide',ARRAY['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6','O-Level','A-Level','IGCSE','AS Level'])
) AS v(kind, subject, topic, title, description, pdf_url, thumbnail_url, grade_levels)
CROSS JOIN (VALUES ('CAPS'), ('ZIMSEC'), ('Cambridge'), ('IEB')) AS c(curriculum)
WHERE NOT EXISTS (
  SELECT 1 FROM public.library_system_resources r
  WHERE r.title = v.title AND r.curriculum = c.curriculum
);