-- Verified curriculum seed: ZIMSEC Form 2 Mathematics
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 2 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 2', 'Mathematics', $topics$
[
  {
    "name": "Real Numbers and Number Operations",
    "subtopics": [
      "Integers, fractions and decimals",
      "Ratio, rate and proportion",
      "Percentages",
      "Standard form (scientific notation)",
      "Number bases",
      "Approximation, estimation and limits of accuracy",
      "Squares, cubes and their roots"
    ],
    "learning_objectives": [
      "Perform the four operations on integers, fractions and decimals without a calculator",
      "Express numbers in standard form A×10^n where 1≤A<10 and compute with them",
      "Convert between number bases (base 2, 5, 10)",
      "Solve ratio, direct and inverse proportion problems",
      "Round to given significant figures/decimal places and state upper and lower bounds"
    ],
    "key_concepts": [
      "order of operations (BODMAS)",
      "recurring decimals to fractions",
      "standard form multiplication and division",
      "ratio sharing",
      "inverse proportion",
      "significant figures",
      "upper and lower bounds",
      "base conversion",
      "HCF and LCM",
      "directed numbers"
    ],
    "assessment_objectives": [
      "AO1: recall and use number facts and standard techniques",
      "AO2: apply number skills to routine and non-routine problems",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Paper 1 short-answer non-calculator arithmetic (1-3 marks)",
      "Express in standard form / evaluate giving answer in standard form (2 marks)",
      "Ratio sharing word problem (3 marks)",
      "Bounds question: state the least and greatest possible value (2 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Form 2 number work"
    ],
    "common_misconceptions": [
      "Adding indices when multiplying numbers in standard form instead of handling the A-parts separately",
      "Rounding before the final step, losing accuracy marks",
      "Treating inverse proportion like direct proportion",
      "Sign errors with directed numbers when subtracting negatives"
    ],
    "exemplar_question_stems": [
      "Express 0.00047 in standard form.",
      "Share $840 between Tino and Rudo in the ratio 5:7. Calculate Rudo's share.",
      "A length is measured as 12.4 cm correct to 1 decimal place. Write down the least possible length.",
      "Convert 43 (base 10) to base 2."
    ]
  },
  {
    "name": "Sets",
    "subtopics": [
      "Set notation and vocabulary",
      "Venn diagrams (two and three sets)",
      "Union, intersection and complement",
      "Number of elements n(A)",
      "Subsets and universal set",
      "Problem solving with Venn diagrams"
    ],
    "learning_objectives": [
      "Use set notation ∈, ∉, ⊂, ∪, ∩, ξ and A′ correctly",
      "Represent given information on a two- or three-set Venn diagram",
      "Solve word problems by forming equations from Venn diagram regions"
    ],
    "key_concepts": [
      "intersection vs union",
      "complement of a set",
      "n(A∪B) = n(A)+n(B)−n(A∩B)",
      "shading regions",
      "three-set region counting with an unknown x"
    ],
    "assessment_objectives": [
      "AO1: use set language and notation",
      "AO2: model survey-type problems with Venn diagrams",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Shade a named region on a Venn diagram (1-2 marks)",
      "Three-set survey problem: form an equation in x and solve (4-5 marks, Paper 2)",
      "List elements of a set defined by a rule (1 mark)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 4,
    "prerequisites": [
      "Real Numbers and Number Operations"
    ],
    "common_misconceptions": [
      "Confusing union with intersection",
      "Forgetting the region outside all circles when totals are given",
      "Double-counting the central three-set overlap region"
    ],
    "exemplar_question_stems": [
      "In a class of 40 pupils, 24 study Accounts, 19 study Geography and 6 study neither. Find the number who study both.",
      "Given ξ = {x : 1 ≤ x ≤ 12, x an integer}, A = {multiples of 3}, B = {factors of 12}, list the elements of A ∩ B."
    ]
  },
  {
    "name": "Financial Mathematics",
    "subtopics": [
      "Simple and compound interest",
      "Profit, loss and discount",
      "Commission and hire purchase",
      "Household bills and budgets",
      "Taxation (PAYE, VAT)",
      "Foreign exchange",
      "Bank statements"
    ],
    "learning_objectives": [
      "Calculate simple and compound interest, principal, rate or time",
      "Solve profit/loss and percentage profit problems",
      "Compute hire-purchase total cost and compare with cash price",
      "Convert between currencies using given exchange rates",
      "Calculate VAT-inclusive and VAT-exclusive prices"
    ],
    "key_concepts": [
      "I = PRT/100",
      "compound interest year-by-year and formula",
      "percentage profit on cost price",
      "deposit plus instalments",
      "exchange rate conversion both directions",
      "value added tax",
      "net pay after deductions"
    ],
    "assessment_objectives": [
      "AO1: perform money calculations accurately",
      "AO2: interpret real financial documents and situations",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Multi-part Paper 2 question walking through a household budget or HP purchase (6-8 marks)",
      "Compound interest over 2-3 years (3-4 marks)",
      "Currency conversion with buying/selling rates (2-3 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 7,
    "prerequisites": [
      "Real Numbers and Number Operations"
    ],
    "common_misconceptions": [
      "Using simple interest formula for compound interest",
      "Calculating percentage profit on selling price instead of cost price",
      "Forgetting to add the deposit when totalling hire-purchase cost"
    ],
    "exemplar_question_stems": [
      "A stove costs $520 cash or a deposit of $100 plus 12 monthly instalments of $40. Calculate the extra cost of buying on hire purchase.",
      "Calculate the compound interest on $2 000 invested for 2 years at 8% per annum."
    ]
  },
  {
    "name": "Measures and Mensuration",
    "subtopics": [
      "Units and conversions",
      "Perimeter and area of plane shapes",
      "Circle: circumference, area, arc length and sector area",
      "Surface area and volume of solids (prism, cylinder, cone, pyramid, sphere)",
      "Density, mass and volume",
      "Combined and similar solids"
    ],
    "learning_objectives": [
      "Convert between metric units of length, area, volume and capacity",
      "Calculate arc length and sector area as fractions of the circle",
      "Find surface area and volume of standard solids and composite solids",
      "Apply density = mass/volume"
    ],
    "key_concepts": [
      "area formulas for triangle, trapezium, parallelogram",
      "circumference 2πr and area πr²",
      "sector angle over 360",
      "volume of prism = cross-section × length",
      "cone volume (1/3)πr²h",
      "sphere volume (4/3)πr³",
      "cm³ to litres",
      "similar solids: area ratio k², volume ratio k³"
    ],
    "assessment_objectives": [
      "AO1: recall and apply mensuration formulas",
      "AO2: dissect composite shapes and solids",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Paper 2 structured question on a composite solid (cylinder + cone) asking volume then surface area (6-9 marks)",
      "Sector arc length/area given angle (3 marks)",
      "Unit conversion embedded in a word problem (2 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 9,
    "prerequisites": [
      "Real Numbers and Number Operations"
    ],
    "common_misconceptions": [
      "Mixing radius and diameter",
      "Using slant height instead of perpendicular height in volume of a cone (and vice versa in curved surface area)",
      "Forgetting that 1 m² = 10 000 cm², not 100 cm²"
    ],
    "exemplar_question_stems": [
      "A sector of a circle of radius 14 cm has an angle of 135°. Taking π = 22/7, calculate the arc length.",
      "A solid consists of a cylinder of radius 7 cm and height 10 cm surmounted by a hemisphere. Calculate its total volume."
    ]
  },
  {
    "name": "Graphs and Variation",
    "subtopics": [
      "Cartesian plane and coordinates",
      "Linear graphs and gradient",
      "Quadratic and cubic graphs",
      "Inverse/reciprocal graphs",
      "Travel graphs (distance-time, speed-time)",
      "Direct, inverse, joint and partial variation"
    ],
    "learning_objectives": [
      "Draw and interpret straight-line graphs; find gradient and intercept",
      "Complete a table of values and draw a smooth quadratic/cubic curve",
      "Use graphs to solve equations including intersection of line and curve",
      "Interpret speed-time graphs: acceleration as gradient, distance as area",
      "Form and solve variation equations with a constant k"
    ],
    "key_concepts": [
      "y = mx + c",
      "gradient between two points",
      "roots as x-intercepts",
      "line of symmetry of a parabola",
      "area under speed-time graph",
      "acceleration and deceleration",
      "direct variation y ∝ x",
      "inverse variation y ∝ 1/x",
      "partial variation y = a + bx"
    ],
    "assessment_objectives": [
      "AO1: plot and read graphs accurately",
      "AO2: translate between graphical, algebraic and verbal descriptions",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Full-page Paper 2 graph question: table of values, draw curve, solve f(x)=k graphically, gradient of tangent (10-12 marks)",
      "Speed-time graph: find acceleration and total distance (4-6 marks)",
      "Variation: find k then evaluate (3-4 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Algebra",
      "Real Numbers and Number Operations"
    ],
    "common_misconceptions": [
      "Joining quadratic points with straight line segments",
      "Reading distance from a speed-time graph directly instead of computing area",
      "Swapping direct and inverse variation when forming the equation"
    ],
    "exemplar_question_stems": [
      "The variables x and y are such that y varies inversely as the square of x, and y = 2 when x = 3. Find y when x = 2.",
      "A car accelerates uniformly from rest to 20 m/s in 8 s, travels at 20 m/s for 12 s, then decelerates to rest in 5 s. Calculate the total distance travelled."
    ]
  },
  {
    "name": "Algebra",
    "subtopics": [
      "Algebraic expressions and simplification",
      "Indices (laws, negative and fractional)",
      "Expansion and factorisation (common factor, grouping, difference of two squares, quadratic trinomials)",
      "Algebraic fractions",
      "Linear equations and inequalities",
      "Simultaneous linear equations",
      "Quadratic equations (factorisation, formula)",
      "Changing the subject of a formula",
      "Word problems leading to equations"
    ],
    "learning_objectives": [
      "Apply all laws of indices including negative and fractional indices",
      "Factorise fully all four standard types",
      "Solve quadratic equations by factorisation and by formula giving answers to 2 d.p.",
      "Solve simultaneous equations by elimination and substitution",
      "Rearrange formulas where the subject appears once or twice"
    ],
    "key_concepts": [
      "laws of indices",
      "difference of two squares",
      "quadratic trinomial factorisation",
      "quadratic formula",
      "LCM of algebraic denominators",
      "inequality sign reversal when multiplying by a negative",
      "forming equations from word contexts"
    ],
    "assessment_objectives": [
      "AO1: manipulate algebraic expressions accurately",
      "AO2: construct and solve equations modelling given situations",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Paper 1 factorise/simplify (2-3 marks each)",
      "Solve the quadratic giving answers correct to 2 decimal places (4-5 marks, Paper 2)",
      "Word problem: form a quadratic and solve (6-7 marks)",
      "Make x the subject (3 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Real Numbers and Number Operations"
    ],
    "common_misconceptions": [
      "Expanding (a+b)² as a² + b²",
      "Cancelling a term instead of a factor when simplifying a fraction",
      "Losing a solution by dividing both sides by a variable",
      "Not reversing the inequality when multiplying by −1"
    ],
    "exemplar_question_stems": [
      "Factorise completely: 3x² − 12.",
      "Solve the equation 2x² − 5x − 1 = 0, giving your answers correct to two decimal places.",
      "The length of a rectangle is 3 cm more than its width. Its area is 40 cm². Form an equation and find the width."
    ]
  },
  {
    "name": "Geometry",
    "subtopics": [
      "Angles on lines, at a point, in parallel lines",
      "Angle properties of triangles and polygons",
      "Congruency and similarity",
      "Circle theorems",
      "Constructions and loci",
      "Symmetry",
      "Pythagoras' theorem",
      "Bearings"
    ],
    "learning_objectives": [
      "Calculate interior/exterior angles of regular polygons",
      "Apply all circle theorems with correct reasons stated",
      "Construct triangles, perpendicular bisectors and angle bisectors with ruler and compasses only",
      "Describe and construct standard loci",
      "Use three-figure bearings in scale-drawing and calculation problems"
    ],
    "key_concepts": [
      "angle sum of polygon (n−2)×180",
      "angle in a semicircle",
      "angles in the same segment",
      "cyclic quadrilateral opposite angles",
      "tangent perpendicular to radius",
      "alternate segment theorem",
      "similar triangles ratio of sides",
      "locus equidistant from two points/lines",
      "back bearings"
    ],
    "assessment_objectives": [
      "AO1: recall angle facts and theorems",
      "AO2: chain multiple theorems with reasons in a multi-step deduction",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Circle geometry: find marked angles giving reasons (5-7 marks, Paper 2)",
      "Ruler-and-compasses construction then locus shading (6-8 marks)",
      "Polygon angle short answer (2-3 marks, Paper 1)",
      "Bearings with scale drawing (4-6 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 11,
    "prerequisites": [
      "Measures and Mensuration"
    ],
    "common_misconceptions": [
      "Quoting the wrong theorem as the reason",
      "Measuring bearings anticlockwise or from the wrong north line",
      "Assuming a quadrilateral is cyclic without justification",
      "Using a protractor in a 'compasses only' construction"
    ],
    "exemplar_question_stems": [
      "A, B, C and D lie on a circle centre O. Angle AOC = 140°. Calculate angle ABC, giving a reason for your answer.",
      "The bearing of Q from P is 065°. Write down the bearing of P from Q.",
      "Construct triangle PQR with PQ = 8 cm, angle P = 60° and PR = 6 cm. Construct the locus of points equidistant from P and Q."
    ]
  },
  {
    "name": "Trigonometry",
    "subtopics": [
      "Sine, cosine and tangent in right-angled triangles",
      "Angles of elevation and depression",
      "Sine rule and cosine rule",
      "Area of triangle ½ab sin C",
      "Obtuse angles",
      "3-D problems",
      "Bearings with trigonometry"
    ],
    "learning_objectives": [
      "Choose the correct ratio to find sides and angles in right-angled triangles",
      "Apply sine and cosine rules in non-right-angled triangles including the obtuse case",
      "Solve elevation/depression and bearing problems",
      "Calculate the area of any triangle using ½ab sin C"
    ],
    "key_concepts": [
      "SOHCAHTOA",
      "sine rule a/sinA = b/sinB",
      "cosine rule a² = b² + c² − 2bc cosA",
      "sin(180−θ) = sinθ",
      "angle of elevation equals angle of depression (alternate angles)",
      "shortest distance is the perpendicular"
    ],
    "assessment_objectives": [
      "AO1: apply trig ratios and rules",
      "AO2: extract right triangles from word/3-D contexts",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Paper 2 structured question combining bearings, cosine rule and area (8-10 marks)",
      "Elevation/depression two-triangle problem (4-6 marks)",
      "Paper 1 exact-value or simple ratio question (2 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 7,
    "prerequisites": [
      "Geometry",
      "Algebra"
    ],
    "common_misconceptions": [
      "Using sine rule when cosine rule is needed (two sides and the included angle)",
      "Calculator in the wrong angle mode",
      "Taking the acute answer when the obtuse angle is required"
    ],
    "exemplar_question_stems": [
      "From a point on level ground 50 m from the foot of a tower, the angle of elevation of the top is 32°. Calculate the height of the tower.",
      "In triangle ABC, AB = 9 cm, AC = 7 cm and angle A = 58°. Calculate BC and the area of the triangle."
    ]
  },
  {
    "name": "Vectors and Transformations",
    "subtopics": [
      "Column vectors, addition and scalar multiplication",
      "Magnitude of a vector",
      "Position vectors and vector geometry (ratio, collinearity, midpoints)",
      "Translation, reflection, rotation, enlargement",
      "Stretch and shear",
      "Describing transformations fully",
      "Matrices of transformations"
    ],
    "learning_objectives": [
      "Add, subtract and scale column vectors; find magnitude",
      "Express vectors in terms of given base vectors and prove collinearity",
      "Perform and fully describe all transformations on the Cartesian plane",
      "Identify the 2×2 matrix representing a given transformation and vice versa"
    ],
    "key_concepts": [
      "magnitude |v| = √(x²+y²)",
      "AB = b − a",
      "parallel vectors are scalar multiples",
      "centre and angle of rotation",
      "scale factor including negative",
      "invariant line of a stretch/shear",
      "determinant as area scale factor"
    ],
    "assessment_objectives": [
      "AO1: compute with vectors and matrices",
      "AO2: reason geometrically using vectors; describe transformations fully",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Vector geometry with ratios: express vectors, show three points are collinear (6-8 marks)",
      "Full-page transformation question: draw images then describe the single transformation mapping one shape to another (8-10 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 7,
    "prerequisites": [
      "Algebra",
      "Geometry"
    ],
    "common_misconceptions": [
      "Describing a rotation without giving centre, angle AND direction",
      "Confusing scale factor sign in enlargement through a centre",
      "Adding vectors nose-to-nose instead of nose-to-tail"
    ],
    "exemplar_question_stems": [
      "Given a = (3, −1) and b = (−2, 4), calculate |a + 2b|.",
      "Triangle A has vertices (1,1), (3,1), (1,4). Triangle B is the image of A under an enlargement centre (0,0), scale factor −2. Draw triangle B and state the coordinates of its vertices."
    ]
  },
  {
    "name": "Matrices",
    "subtopics": [
      "Order of a matrix",
      "Addition, subtraction and scalar multiplication",
      "Matrix multiplication",
      "Identity matrix",
      "Determinant of a 2×2 matrix",
      "Inverse of a 2×2 matrix",
      "Solving simultaneous equations with matrices",
      "Singular matrices"
    ],
    "learning_objectives": [
      "Multiply conformable matrices and know when multiplication is undefined",
      "Find the determinant and inverse of a 2×2 matrix",
      "Use the inverse matrix to solve a pair of simultaneous linear equations",
      "Find unknowns given that a matrix is singular"
    ],
    "key_concepts": [
      "rows × columns rule for products",
      "determinant ad − bc",
      "inverse = 1/det × adjugate",
      "singular means det = 0",
      "AI = IA = A",
      "matrix equation AX = B gives X = A⁻¹B"
    ],
    "assessment_objectives": [
      "AO1: perform matrix operations",
      "AO2: apply matrices to equations and transformations",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Find the inverse and use it to solve simultaneous equations (5-6 marks)",
      "Find x given the matrix has no inverse (3 marks)",
      "Product of two 2×2 matrices (2-3 marks, Paper 1)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 4,
    "prerequisites": [
      "Algebra"
    ],
    "common_misconceptions": [
      "Multiplying corresponding entries instead of row-by-column",
      "Forgetting to swap the leading diagonal AND negate the other diagonal in the inverse",
      "Dividing by a zero determinant"
    ],
    "exemplar_question_stems": [
      "Given M = (2 1; 3 4), find the inverse of M.",
      "The matrix (x 2; 8 4) is singular. Find the value of x."
    ]
  },
  {
    "name": "Statistics",
    "subtopics": [
      "Data collection and classification",
      "Frequency tables and grouped data",
      "Bar charts, pie charts and histograms (equal and unequal intervals)",
      "Mean, median, mode of raw and grouped data",
      "Assumed mean",
      "Cumulative frequency curves, median and quartiles",
      "Interquartile range"
    ],
    "learning_objectives": [
      "Construct and interpret histograms using frequency density for unequal class widths",
      "Estimate the mean of grouped data using mid-values",
      "Draw a cumulative frequency curve and read off median, quartiles and percentiles",
      "Compare two distributions using averages and spread"
    ],
    "key_concepts": [
      "frequency density = frequency ÷ class width",
      "midpoint method for grouped mean",
      "median position n/2 on the ogive",
      "interquartile range Q3 − Q1",
      "modal class",
      "pie chart angle = fraction × 360"
    ],
    "assessment_objectives": [
      "AO1: compute statistical measures",
      "AO2: interpret and compare distributions",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Full Paper 2 question: complete a cumulative frequency table, draw the ogive, estimate median/IQR and answer a 'greater than' question (10-12 marks)",
      "Histogram with unequal widths: find missing frequency (3-4 marks)",
      "Grouped mean estimate (4 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 7,
    "prerequisites": [
      "Graphs and Variation"
    ],
    "common_misconceptions": [
      "Plotting cumulative frequency against midpoints instead of upper class boundaries",
      "Using frequency instead of frequency density for histogram heights",
      "Reading quartiles from the frequency axis instead of the data axis"
    ],
    "exemplar_question_stems": [
      "The masses of 80 parcels are grouped in a table. Draw a cumulative frequency curve and use it to estimate the median mass and the interquartile range.",
      "A histogram has classes 0–10, 10–15, 15–35. The bar over 10–15 has height 4.2 and frequency 21. Find the frequency of the 15–35 class if its height is 0.9."
    ]
  },
  {
    "name": "Probability",
    "subtopics": [
      "Experimental and theoretical probability",
      "Single events",
      "Combined events (sample space)",
      "Tree diagrams (with and without replacement)",
      "Mutually exclusive and independent events",
      "Expected frequency"
    ],
    "learning_objectives": [
      "Calculate probabilities of single and combined events as fractions in lowest terms",
      "Construct and use tree diagrams, distinguishing with/without replacement",
      "Apply the addition law for mutually exclusive events and multiplication law for independent events"
    ],
    "key_concepts": [
      "P(A) = favourable/total",
      "multiplication law for independent events",
      "addition law for mutually exclusive events",
      "denominator decreases without replacement",
      "branch probabilities sum to 1",
      "P(at least one) = 1 − P(none)"
    ],
    "assessment_objectives": [
      "AO1: compute basic probabilities",
      "AO2: model multi-stage experiments with tree diagrams",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Two-stage tree diagram without replacement: complete the tree then find P(at least one) (6-8 marks)",
      "Sample-space table for two dice (3-4 marks)",
      "Single event probability (1-2 marks, Paper 1)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 4,
    "prerequisites": [
      "Sets",
      "Statistics"
    ],
    "common_misconceptions": [
      "Adding probabilities along branches instead of multiplying",
      "Forgetting the denominator decreases without replacement",
      "Computing P(at least one) case-by-case instead of using 1 − P(none)"
    ],
    "exemplar_question_stems": [
      "A bag contains 5 red and 3 blue beads. Two beads are taken at random without replacement. Draw a tree diagram and find the probability that the beads are different colours."
    ]
  },
  {
    "name": "Inequalities and Linear Programming",
    "subtopics": [
      "Linear inequalities in two variables",
      "Graphing inequality regions",
      "Forming constraints from word problems",
      "Objective function and optimisation",
      "Integer solutions in a region"
    ],
    "learning_objectives": [
      "Translate word constraints into inequalities",
      "Shade the unwanted regions and identify the feasible region R",
      "Use vertex testing or a search line to maximise/minimise an objective function",
      "List integer coordinate solutions in R"
    ],
    "key_concepts": [
      "solid boundary for ≤ and ≥, broken for < and >",
      "feasible region",
      "objective function P = ax + by",
      "optimum at a vertex of the region",
      "non-negativity constraints"
    ],
    "assessment_objectives": [
      "AO2: model resource-allocation problems",
      "AO3: interpret optimal solutions in context",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Full Paper 2 linear programming question: write constraints, draw region, find maximum profit (10-12 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 5,
    "prerequisites": [
      "Graphs and Variation",
      "Algebra"
    ],
    "common_misconceptions": [
      "Shading the wanted region when the instruction says shade the UNWANTED region",
      "Using a broken line for ≤",
      "Testing interior points instead of vertices for the optimum"
    ],
    "exemplar_question_stems": [
      "A carpenter makes x tables and y chairs. Each table needs 4 hours and each chair 2 hours; at most 40 hours are available. He must make at least 3 tables. Write down two inequalities in x and y, and given profit P = 30x + 10y, find the values of x and y that maximise profit."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
