-- Verified curriculum seed: ZIMSEC Form 2 History
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 2 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 2', 'History', $topics$
[
  {
    "name": "Pre-Colonial States of Southern Africa",
    "subtopics": [
      "Great Zimbabwe state: origins, economy, society, decline",
      "The Mutapa state",
      "The Rozvi state",
      "The Ndebele state under Mzilikazi and Lobengula",
      "Political, social and economic organisation of pre-colonial states",
      "Trade networks with the east coast"
    ],
    "learning_objectives": [
      "Describe the rise, organisation and decline of Great Zimbabwe, Mutapa, Rozvi and Ndebele states",
      "Explain the economic bases of pre-colonial states: agriculture, cattle, mining, tribute and trade",
      "Describe political structures: kingship, succession, and the role of religion in legitimising rule",
      "Explain the importance of long-distance trade in gold and ivory with coastal traders",
      "Assess the factors that led to the decline of each state"
    ],
    "key_concepts": [
      "tribute system",
      "religious legitimation of authority",
      "cattle as a store of wealth",
      "succession disputes",
      "trade goods: gold, ivory, cloth, beads",
      "raiding and incorporation in state building"
    ],
    "assessment_objectives": [
      "Knowledge and recall of events, structures and dates",
      "Analysis: explaining causes, significance and change over time",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe the political organisation of a named pre-colonial state (part (a), 5-8 marks)",
      "Explain the factors that led to the rise of the state (part (b), 6-8 marks)",
      "To what extent did trade contribute to the growth of the state? (part (c), evaluative, 6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Primary school social studies foundations"
    ],
    "common_misconceptions": [
      "Treating pre-colonial states as static and unchanging",
      "Attributing state decline to a single cause",
      "Assuming all authority was purely military rather than also religious and economic",
      "Confusing the chronology of the successive states"
    ],
    "exemplar_question_stems": [
      "Describe the economic activities of the people of the Mutapa state.",
      "Explain the role of religion in the government of pre-colonial states.",
      "To what extent were succession disputes responsible for the decline of the Rozvi state?",
      "Outline the relations between the Ndebele state and its neighbours under Lobengula."
    ]
  },
  {
    "name": "The Scramble for and Partition of Africa",
    "subtopics": [
      "Motives for European colonisation (economic, political, social)",
      "The Berlin Conference and its principles",
      "Methods of colonisation: treaties, concessions, conquest",
      "The Rudd Concession and the British South Africa Company",
      "The occupation of Zimbabwe (Pioneer Column)",
      "African responses to colonisation"
    ],
    "learning_objectives": [
      "Explain the economic, strategic and prestige motives behind the scramble",
      "Describe the decisions of the Berlin Conference including effective occupation",
      "Explain how treaties and concessions were used to claim territory",
      "Describe the terms and significance of the Rudd Concession and the role of the chartered company",
      "Trace the occupation of Mashonaland and Matabeleland",
      "Compare African responses: collaboration, negotiation and resistance"
    ],
    "key_concepts": [
      "effective occupation doctrine",
      "sphere of influence",
      "chartered company rule",
      "verbal versus written treaty disputes",
      "concession-seeking rivalry",
      "collaboration as strategic choice rather than betrayal"
    ],
    "assessment_objectives": [
      "Knowledge of events and agreements",
      "Analysis of motives and consequences",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Outline the terms of the Rudd Concession (5-8 marks)",
      "Explain why European powers scrambled for Africa in the late nineteenth century (6-8 marks)",
      "How far did African rulers benefit from signing treaties with Europeans? (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Pre-Colonial States of Southern Africa"
    ],
    "common_misconceptions": [
      "Believing the Berlin Conference physically divided the whole continent overnight",
      "Assuming African rulers fully understood the written terms of concessions they signed",
      "Treating all African responses as armed resistance",
      "Confusing the Rudd Concession with later land legislation"
    ],
    "exemplar_question_stems": [
      "Describe the events that led to the signing of the Rudd Concession in 1888.",
      "Explain the significance of the Berlin Conference in the partition of Africa.",
      "To what extent did economic motives drive the colonisation of southern Africa?",
      "Describe the journey and purpose of the Pioneer Column of 1890."
    ]
  },
  {
    "name": "Colonial Rule and Early Resistance",
    "subtopics": [
      "Causes of the first uprisings of the 1890s",
      "The course of the risings in Matabeleland and Mashonaland",
      "The role of spirit mediums",
      "Reasons for African defeat and results",
      "Colonial administration: company rule to settler government",
      "Land, labour and taxation policies",
      "African life under colonial rule"
    ],
    "learning_objectives": [
      "Explain the grievances (land loss, cattle seizures, forced labour, taxation, natural disasters) that caused the 1896-97 uprisings",
      "Describe the course of the uprisings in both regions and the role of religious leaders",
      "Explain why the uprisings were suppressed and assess their short- and long-term results",
      "Describe the transition from chartered company rule to responsible government",
      "Explain the effects of land apportionment, labour laws and taxation on African communities"
    ],
    "key_concepts": [
      "primary resistance",
      "spirit mediums as coordinators and symbols",
      "hut tax as labour lever",
      "land alienation and reserves",
      "migrant labour system",
      "collaborators and neutrals in conflict"
    ],
    "assessment_objectives": [
      "Knowledge of causes, course and results",
      "Evaluation of relative importance of causes and significance of outcomes",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Outline the causes of the uprisings of 1896-97 (5-8 marks)",
      "Explain the role of religious leaders in the uprisings (6-8 marks)",
      "Did the uprisings achieve anything for Africans? Explain your answer (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "The Scramble for and Partition of Africa"
    ],
    "common_misconceptions": [
      "Reducing the causes of the uprisings to a single grievance",
      "Assuming the two regional risings were centrally coordinated as one",
      "Believing defeat ended all forms of resistance rather than changing its form",
      "Confusing early colonial land measures with later apportionment acts"
    ],
    "exemplar_question_stems": [
      "Describe the grievances of Africans that led to the uprisings of 1896-97.",
      "Explain why the uprisings of 1896-97 were defeated.",
      "To what extent were natural disasters responsible for the outbreak of the uprisings?",
      "Describe the effects of colonial taxation on African families."
    ]
  },
  {
    "name": "Nationalism and the Liberation Struggle",
    "subtopics": [
      "Rise of mass nationalism after 1945",
      "Early nationalist organisations and leaders",
      "The federation period and African opposition",
      "Unilateral Declaration of Independence and its effects",
      "The armed struggle: causes, course and turning points",
      "The role of peasants, women and youth in the struggle",
      "Regional and international support",
      "Negotiations and the Lancaster House settlement",
      "Achievement of independence in 1980"
    ],
    "learning_objectives": [
      "Explain the factors that stimulated African nationalism after the Second World War",
      "Trace the development of nationalist movements from associations and unions to mass parties",
      "Explain African opposition to the Central African Federation",
      "Describe the effects of the settler government's unilateral declaration of independence and international sanctions",
      "Explain why nationalists turned to armed struggle and describe its main phases",
      "Assess the contributions of different social groups and of neighbouring countries to the struggle",
      "Describe the negotiations that led to the Lancaster House agreement and the 1980 elections"
    ],
    "key_concepts": [
      "mass nationalism vs elite petition politics",
      "federation as settler consolidation",
      "sanctions and sanctions-busting",
      "guerrilla warfare and mass mobilisation",
      "frontline states' support",
      "detente and negotiation phases",
      "ceasefire and transitional arrangements"
    ],
    "assessment_objectives": [
      "Knowledge of movements, events and agreements",
      "Analysis of causes, contributions and turning points",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Outline the factors that led to the rise of mass nationalism (5-8 marks)",
      "Explain why the armed struggle intensified in the 1970s (6-8 marks)",
      "How important was external support to the success of the liberation struggle? (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Colonial Rule and Early Resistance"
    ],
    "common_misconceptions": [
      "Treating independence as the result of armed struggle alone without negotiation",
      "Ignoring the roles of women, peasants and youth in the struggle",
      "Assuming sanctions immediately crippled the settler economy",
      "Confusing the sequence of major conferences and agreements"
    ],
    "exemplar_question_stems": [
      "Describe the methods used by early nationalist movements before the armed struggle.",
      "Explain the effects of the Unilateral Declaration of Independence on the African majority.",
      "To what extent did the support of neighbouring countries contribute to the achievement of independence?",
      "Outline the main provisions of the Lancaster House agreement."
    ]
  },
  {
    "name": "Post-Independence Zimbabwe",
    "subtopics": [
      "Reconstruction and reconciliation after 1980",
      "Expansion of education and health services",
      "Land reform phases",
      "Economic policies and structural adjustment",
      "Unity Accord of 1987",
      "Regional cooperation (SADC) and foreign relations",
      "Challenges: drought, debt and economic decline"
    ],
    "learning_objectives": [
      "Describe the policies of reconciliation and reconstruction adopted at independence",
      "Assess achievements in education, health and rural development in the first decade",
      "Trace the phases of land reform and the debates surrounding them",
      "Explain the aims and effects of economic structural adjustment in the 1990s",
      "Describe the background to and terms of the Unity Accord",
      "Outline Zimbabwe's role in regional organisations and peacekeeping"
    ],
    "key_concepts": [
      "reconciliation policy",
      "growth with equity",
      "willing-buyer willing-seller principle",
      "structural adjustment conditions and social costs",
      "unity and nation building",
      "regional integration"
    ],
    "assessment_objectives": [
      "Knowledge of policies and events since 1980",
      "Evaluation of successes and challenges",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe the social achievements of the government in the first ten years of independence (5-8 marks)",
      "Explain the reasons for adopting economic structural adjustment (6-8 marks)",
      "How successful was the land reform programme up to the year 2000? (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Nationalism and the Liberation Struggle"
    ],
    "common_misconceptions": [
      "Assuming all post-independence policies had immediate uniform effects",
      "Treating land reform as a single event rather than phases with different methods",
      "Ignoring external factors (drought, world prices) when judging economic performance",
      "Confusing the dates of major post-independence agreements"
    ],
    "exemplar_question_stems": [
      "Describe the policy of reconciliation adopted at independence in 1980.",
      "Explain the achievements of the government in expanding education after 1980.",
      "To what extent did economic structural adjustment improve the lives of ordinary people?",
      "Outline the circumstances that led to the signing of the Unity Accord in 1987."
    ]
  },
  {
    "name": "The World Wars and International Relations",
    "subtopics": [
      "Causes of the First World War",
      "Course and results of the First World War",
      "The Versailles settlement",
      "The League of Nations: aims, successes, failures",
      "Rise of dictatorships in the interwar period",
      "Causes of the Second World War",
      "Course and results of the Second World War",
      "Africa and Africans in the world wars"
    ],
    "learning_objectives": [
      "Explain the long-term and immediate causes of the First World War (alliances, arms race, imperial rivalry, the 1914 crisis)",
      "Describe the main features and results of the war including the human and economic costs",
      "Outline the terms of the peace settlement and German grievances",
      "Assess the League of Nations' organisation, achievements and weaknesses",
      "Explain the conditions that allowed dictatorships to rise in the interwar years",
      "Explain the steps to war in the 1930s: rearmament, expansionism and the failure of appeasement",
      "Describe the global course of the Second World War in outline and its results",
      "Describe the contributions and experiences of African soldiers and colonies in both wars"
    ],
    "key_concepts": [
      "alliance systems",
      "militarism and mobilisation timetables",
      "war guilt and reparations",
      "collective security",
      "unanimity rule weakness",
      "appeasement debate",
      "total war",
      "war service and rising political consciousness in the colonies"
    ],
    "assessment_objectives": [
      "Knowledge of events, treaties and organisations",
      "Analysis and judgement on causes and consequences",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Outline the causes of the First World War (5-8 marks)",
      "Explain why the League of Nations failed to keep world peace (6-8 marks)",
      "To what extent was the policy of appeasement responsible for the outbreak of the Second World War? (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Primary school social studies foundations"
    ],
    "common_misconceptions": [
      "Treating the assassination crisis of 1914 as the sole cause of the First World War",
      "Assuming the League failed only because of one weakness",
      "Believing appeasement alone caused the Second World War",
      "Overlooking African participation and its political effects"
    ],
    "exemplar_question_stems": [
      "Describe the alliance system in Europe before 1914.",
      "Explain the weaknesses in the organisation of the League of Nations.",
      "How far did the peace settlement of 1919 contribute to the outbreak of war in 1939?",
      "Describe the contribution of African soldiers to the Second World War."
    ]
  },
  {
    "name": "The Cold War and Decolonisation",
    "subtopics": [
      "Origins of the Cold War",
      "Features: blocs, arms race, crises",
      "The United Nations: organisation and role",
      "Decolonisation in Africa and Asia",
      "Non-Aligned Movement",
      "The Organisation of African Unity / African Union",
      "End of the Cold War and its effects on Africa"
    ],
    "learning_objectives": [
      "Explain the ideological and political origins of the Cold War",
      "Describe key features and crises of the Cold War at an outline level",
      "Describe the structure of the United Nations and assess its peacekeeping role",
      "Explain the factors that speeded decolonisation after 1945",
      "Describe the aims of the Non-Aligned Movement and continental unity organisations",
      "Assess the effects of superpower rivalry and its end on African states"
    ],
    "key_concepts": [
      "ideological rivalry",
      "spheres of influence and proxy conflict",
      "veto power in the Security Council",
      "winds of change",
      "positive neutrality",
      "pan-Africanism",
      "aid and alignment pressures"
    ],
    "assessment_objectives": [
      "Knowledge of institutions and processes",
      "Analysis of impacts on Africa and the wider world",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "Describe the origins of the Cold War (5-8 marks)",
      "Explain the factors that promoted the decolonisation of Africa after 1945 (6-8 marks)",
      "How effective has the United Nations been in maintaining world peace? (6-8 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "The World Wars and International Relations"
    ],
    "common_misconceptions": [
      "Treating the Cold War as direct fighting between the superpowers",
      "Assuming decolonisation happened at the same pace everywhere",
      "Believing non-alignment meant isolation from both blocs",
      "Confusing the roles of the General Assembly and the Security Council"
    ],
    "exemplar_question_stems": [
      "Explain the meaning of the term Cold War.",
      "Describe the aims of the Non-Aligned Movement.",
      "To what extent did the Second World War speed up the decolonisation of Africa?",
      "Outline the functions of the Security Council of the United Nations."
    ]
  },
  {
    "name": "Historical Skills and Source Analysis",
    "subtopics": [
      "Primary and secondary sources",
      "Reliability, bias and provenance",
      "Interpreting written, pictorial and statistical evidence",
      "Cross-referencing sources",
      "Constructing structured answers: describe, explain, evaluate",
      "Chronology and periodisation"
    ],
    "learning_objectives": [
      "Distinguish primary from secondary sources and state the value of each",
      "Assess reliability by examining author, purpose, audience and date",
      "Extract and interpret information from documents, cartoons, photographs and tables",
      "Cross-reference two or more sources to test a claim",
      "Structure answers to the three-part question format: description, explanation, balanced evaluation with a conclusion",
      "Place events in correct chronological order and relate them across topics"
    ],
    "key_concepts": [
      "provenance questions: who, when, why",
      "bias is not the same as uselessness",
      "corroboration",
      "tone and intended audience",
      "balanced argument with supported judgement"
    ],
    "assessment_objectives": [
      "Source comprehension and evaluation",
      "Structured, evidence-based argument",
      "Form 2 (ZJC) depth: developing treatment of this strand — extending Form 1 foundations with more independent application; full O-Level demand is developed by Form 4."
    ],
    "typical_question_styles": [
      "What does the source reveal about attitudes at the time? (4-6 marks)",
      "How reliable is this source to a historian studying the event? (5-6 marks)",
      "Using the sources and your own knowledge, how far do you agree with the statement? (8-10 marks)",
      "Structured questions of growing independence, appropriate to Form 2"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "Primary school social studies foundations"
    ],
    "common_misconceptions": [
      "Dismissing a biased source as worthless instead of using it as evidence of attitudes",
      "Assuming primary sources are always more reliable than secondary ones",
      "Describing source content when the question asks for evaluation",
      "Writing one-sided answers to 'to what extent' questions without a conclusion"
    ],
    "exemplar_question_stems": [
      "Study the poster. What message was the artist trying to convey?",
      "How useful is this letter to a historian studying life under colonial rule? Use the source and your own knowledge.",
      "The two sources give different accounts of the same event. Suggest reasons for the differences.",
      "Using all the sources and your own knowledge, explain how far you agree that the uprisings failed to achieve their aims."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
