-- Verified curriculum seed: NSC Grade 10 Tourism
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 10 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('NSC', 'Grade 10', 'Tourism', $topics$
[
  {
    "name": "Tourism Sectors and Professional Conduct",
    "subtopics": [
      "Sectors and sub-sectors of the tourism industry",
      "Professional image and conduct in the workplace",
      "Conditions of employment and workplace ethics",
      "Contracts and codes of conduct",
      "The role of technology in the tourism workplace",
      "Career opportunities in tourism"
    ],
    "learning_objectives": [
      "Describe the structure and sectors of the tourism industry",
      "Explain expectations of professional conduct and appearance",
      "Interpret conditions of employment and codes of conduct",
      "Evaluate how technology changes tourism jobs and services"
    ],
    "key_concepts": [
      "Accommodation, transport, attractions, hospitality and support sectors",
      "Professional image (appearance, punctuality, communication)",
      "Code of conduct and grievance procedures",
      "Basic conditions of employment",
      "Online booking systems and e-tourism",
      "Interdependence of tourism sectors"
    ],
    "assessment_objectives": [
      "Identify sectors and roles within the industry",
      "Apply professional-conduct principles to workplace scenarios",
      "Evaluate the impact of technology on tourism operations",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Identify the sector and sub-sector in which the business operates",
      "Discuss why the employee's behaviour in the scenario is unprofessional",
      "Explain TWO ways technology has changed the process described",
      "Give advice to the new employee on maintaining a professional image",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 tourism sectors"
    ],
    "common_misconceptions": [
      "Believing tourism only involves travel agencies and hotels",
      "Confusing a code of conduct with an employment contract",
      "Assuming professional image only concerns physical appearance",
      "Thinking technology replaces rather than changes tourism roles"
    ],
    "exemplar_question_stems": [
      "Classify the business described into the correct tourism sector and sub-sector, giving a reason",
      "The receptionist arrives late and argues with a guest; discuss THREE aspects of professional conduct being violated",
      "Explain TWO advantages of online check-in for both the airline and the traveller"
    ]
  },
  {
    "name": "Map Work, Tour Planning and Itineraries",
    "subtopics": [
      "World time zones and time calculations",
      "Daylight saving time",
      "Flight schedules and travel documentation",
      "Tour itineraries and tour planning",
      "Route planning using maps and technology",
      "Factors influencing tour plans (health, safety, seasons)"
    ],
    "learning_objectives": [
      "Calculate times across time zones including daylight saving adjustments",
      "Interpret flight schedules and travel documents",
      "Design or evaluate a tour itinerary for a described tourist profile",
      "Apply route planning and travel logistics to scenarios"
    ],
    "key_concepts": [
      "UTC/GMT and time zone offsets",
      "International Date Line",
      "Elapsed flying time vs local arrival time",
      "Jet lag and its management",
      "Itinerary components (day-by-day activities, transfers, meals)",
      "Travel documents: passports, visas, health certificates"
    ],
    "assessment_objectives": [
      "Perform accurate time-zone and flight-time calculations",
      "Compile or amend itineraries to fit tourist needs and budgets",
      "Interpret maps, schedules and travel documentation",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Calculate the local arrival time given departure time, flying time and time zones",
      "Adjust the calculation for daylight saving in the destination country",
      "Study the itinerary and suggest changes to suit the tourist profile described",
      "Identify the travel documents required for the journey described",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Grade 11 time zone calculations and tour planning"
    ],
    "common_misconceptions": [
      "Adding instead of subtracting hours when travelling west across time zones",
      "Ignoring daylight saving time in the destination when calculating arrival times",
      "Confusing flying time with the difference between departure and arrival clock times",
      "Believing a passport alone guarantees entry to any country without a visa"
    ],
    "exemplar_question_stems": [
      "A flight departs Johannesburg at the given time and flies for eleven hours to a city seven hours behind; calculate the local arrival time",
      "Explain how daylight saving time will affect the calculation if the destination has moved its clocks forward",
      "Evaluate whether the three-day itinerary suits an elderly tour group and suggest TWO amendments"
    ]
  },
  {
    "name": "Tourist Attractions: South African and World Icons",
    "subtopics": [
      "South African world-famous attractions and icons",
      "Global tourist icons and attractions across continents",
      "Factors contributing to the success of attractions",
      "Managing tourist expectations at attractions",
      "Spatial location of major attractions",
      "Universal accessibility at attractions"
    ],
    "learning_objectives": [
      "Locate and describe major South African and international attractions",
      "Explain the tourist appeal of iconic attractions",
      "Evaluate factors that make attractions successful and sustainable",
      "Assess accessibility and visitor management at attractions"
    ],
    "key_concepts": [
      "Icon vs attraction distinction",
      "Natural vs cultural vs man-made attractions",
      "Visitor management and carrying capacity",
      "Universal access for tourists with disabilities",
      "Marketing an attraction's unique selling points",
      "Location on world and regional maps"
    ],
    "assessment_objectives": [
      "Identify and locate attractions from descriptions or maps",
      "Explain the significance and appeal of icons",
      "Evaluate management and accessibility practices at attractions",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Identify the attraction from the description and name the country/city where it is found",
      "Explain TWO reasons why the attraction draws international visitors",
      "Suggest ways the attraction could improve universal accessibility",
      "Discuss how the attraction manages large visitor numbers",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Grade 11 South African attractions"
    ],
    "common_misconceptions": [
      "Confusing an icon (symbolic, world-renowned) with any popular attraction",
      "Assuming all attractions are natural features",
      "Believing accessibility only refers to wheelchair ramps",
      "Mixing up the locations of similar-sounding international attractions"
    ],
    "exemplar_question_stems": [
      "Name the world icon described in the extract and the city in which it is located",
      "Explain TWO factors that contribute to the ongoing success of the South African attraction described",
      "Recommend THREE measures the attraction could implement to accommodate tourists with limited mobility"
    ]
  },
  {
    "name": "Culture and Heritage Tourism",
    "subtopics": [
      "World Heritage Sites in South Africa",
      "Cultural uniqueness of South African communities",
      "Heritage bodies and their roles",
      "Benefits of heritage tourism for communities",
      "Preservation vs commercialisation of culture",
      "Cultural etiquette for tourists"
    ],
    "learning_objectives": [
      "Describe South Africa's World Heritage Sites and their significance",
      "Explain how cultural tourism can benefit local communities",
      "Evaluate tensions between preserving and commercialising culture",
      "Advise tourists on respectful cultural conduct"
    ],
    "key_concepts": [
      "Natural, cultural and mixed World Heritage Sites",
      "Tangible vs intangible heritage",
      "Community-based tourism",
      "Authenticity in cultural experiences",
      "Role of heritage organisations",
      "Economic spin-offs of heritage tourism"
    ],
    "assessment_objectives": [
      "Identify heritage sites and classify their type",
      "Explain the value of heritage to tourism and communities",
      "Critically evaluate cultural tourism practices",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Identify the World Heritage Site from the description and classify it as natural, cultural or mixed",
      "Explain TWO ways the local community benefits from the heritage site",
      "Critically discuss whether the cultural village described presents culture authentically",
      "Advise tourists on appropriate behaviour when visiting the community described",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 culture and heritage tourism"
    ],
    "common_misconceptions": [
      "Believing all World Heritage Sites are historical buildings",
      "Confusing heritage (inherited significance) with any old object or place",
      "Assuming commercialisation always destroys cultural authenticity",
      "Thinking heritage tourism benefits only the government rather than communities"
    ],
    "exemplar_question_stems": [
      "Classify the World Heritage Site described as natural, cultural or mixed, and motivate your classification",
      "Discuss TWO economic and ONE social benefit that heritage tourism brings to the community in the case study",
      "Evaluate the statement that staged cultural performances undermine authentic heritage"
    ]
  },
  {
    "name": "Foreign Exchange and Tourism Economics",
    "subtopics": [
      "Foreign exchange rates: buying and selling rates",
      "Currency conversions for travellers",
      "The value of the rand and its effect on tourism",
      "Strong vs weak currency implications for inbound/outbound tourism",
      "Budgeting for international travel",
      "Multiplier effect of tourism spending"
    ],
    "learning_objectives": [
      "Convert between currencies using bank buying and selling rates",
      "Explain how exchange-rate movements affect tourist decisions",
      "Analyse the effect of a weak or strong rand on inbound and outbound tourism",
      "Calculate travel budgets involving foreign currency"
    ],
    "key_concepts": [
      "Bank buying rate vs bank selling rate",
      "Rand appreciation and depreciation",
      "Inbound vs outbound tourism flows",
      "Value for money for foreign tourists",
      "The tourism multiplier effect",
      "Commission on currency exchange"
    ],
    "assessment_objectives": [
      "Perform accurate currency conversion calculations",
      "Interpret exchange-rate tables",
      "Explain economic effects of currency movements on tourism",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Use the exchange-rate table to convert the given amount, selecting the correct rate",
      "Calculate how much foreign currency the traveller will receive for the rand amount",
      "Explain how the weak rand will affect the number of foreign tourists visiting South Africa",
      "Determine whether the tourist can afford the itinerary within the stated budget",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Grade 11 foreign exchange basics",
      "Basic arithmetic and ratios"
    ],
    "common_misconceptions": [
      "Using the bank buying rate when the bank is selling foreign currency to the traveller",
      "Believing a weak rand is bad for all tourism, ignoring the boost to inbound tourism",
      "Multiplying instead of dividing (or vice versa) when converting currencies",
      "Ignoring commission and fees in travel budget calculations"
    ],
    "exemplar_question_stems": [
      "A tourist exchanges the given rand amount for euros; use the correct rate from the table and calculate the amount received",
      "Explain TWO ways in which a depreciating rand benefits the South African tourism industry",
      "Calculate the total cost in rand of the tour priced in US dollars, using the rate provided"
    ]
  },
  {
    "name": "Customer Care and Service Excellence",
    "subtopics": [
      "Customer service vs customer care",
      "Service excellence in tourism businesses",
      "Dealing with complaints and feedback",
      "Customer feedback methods and their value",
      "The impact of service on business success and repeat visits",
      "Service delivery evaluation"
    ],
    "learning_objectives": [
      "Distinguish between customer service and customer care",
      "Apply complaint-handling procedures to scenarios",
      "Evaluate feedback methods used by tourism businesses",
      "Explain the link between service excellence and profitability"
    ],
    "key_concepts": [
      "Exceeding customer expectations",
      "Complaint-handling steps (listen, apologise, act, follow up)",
      "Feedback tools: questionnaires, online reviews, follow-up calls",
      "Word-of-mouth and online reputation",
      "Staff training and empowerment",
      "Repeat business and customer loyalty"
    ],
    "assessment_objectives": [
      "Explain customer-care concepts and procedures",
      "Apply service-recovery steps to complaint scenarios",
      "Evaluate the impact of service quality on a business",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Distinguish between the two concepts with examples",
      "Explain how the staff member should handle the complaint in the scenario",
      "Evaluate the feedback method used by the establishment",
      "Discuss how poor service in the case study could affect future business",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 customer care"
    ],
    "common_misconceptions": [
      "Treating customer care as identical to customer service rather than the broader relationship",
      "Believing complaints are purely negative rather than opportunities to improve",
      "Assuming an apology alone resolves a complaint without corrective action",
      "Ignoring online reviews as unimportant to business success"
    ],
    "exemplar_question_stems": [
      "A guest complains that their booked room is unavailable; describe FOUR steps the receptionist should follow",
      "Evaluate the usefulness of online review platforms as a feedback method for the guesthouse described",
      "Explain TWO ways in which service excellence contributes to the profitability of a tourism business"
    ]
  },
  {
    "name": "Sustainable and Responsible Tourism",
    "subtopics": [
      "Concepts: sustainable, responsible and fair-trade tourism",
      "Environmental, social and economic pillars of sustainability",
      "Responsible tourist behaviour",
      "Green practices in tourism businesses",
      "Codes of conduct for tourists and operators",
      "Impacts of unsustainable tourism practices"
    ],
    "learning_objectives": [
      "Define and distinguish sustainability-related tourism concepts",
      "Evaluate tourism practices against the three pillars of sustainability",
      "Recommend responsible behaviour for tourists and businesses",
      "Analyse the consequences of unsustainable tourism"
    ],
    "key_concepts": [
      "Triple bottom line (planet, people, profit)",
      "Carbon footprint of travel",
      "Community involvement and fair wages",
      "Eco-certification and green grading",
      "Overtourism and environmental degradation",
      "Reduce-reuse-recycle in hospitality"
    ],
    "assessment_objectives": [
      "Explain sustainability concepts accurately",
      "Apply the three pillars to evaluate case studies",
      "Propose realistic responsible-tourism measures",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Define responsible tourism and give an example from the case study",
      "Evaluate the lodge's practices against the three pillars of sustainability",
      "Suggest ways the tourists in the scenario could reduce their negative impact",
      "Discuss the possible long-term effects of the unsustainable practice described",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 sustainable tourism"
    ],
    "common_misconceptions": [
      "Believing sustainability only concerns the environment and not people or profit",
      "Confusing responsible tourism (behaviour) with sustainable tourism (long-term balance)",
      "Assuming eco-labels always guarantee genuinely green practices",
      "Thinking individual tourist choices are too small to matter"
    ],
    "exemplar_question_stems": [
      "Evaluate the hotel's initiatives in the case study against the economic, social and environmental pillars",
      "Recommend THREE responsible behaviours for tourists visiting the fragile ecosystem described",
      "Discuss TWO negative consequences the community may face if overtourism at the site continues"
    ]
  },
  {
    "name": "Domestic, Regional and International Tourism; Marketing",
    "subtopics": [
      "Domestic, regional and international tourism flows",
      "Statistics and trends in tourist arrivals",
      "Factors influencing tourist decisions (safety, exchange rates, events)",
      "Marketing South Africa as a destination",
      "Marketing organisations and campaigns",
      "Global events and their tourism impact"
    ],
    "learning_objectives": [
      "Distinguish domestic, regional and international tourism with examples",
      "Interpret tourism statistics, graphs and trends",
      "Analyse factors that attract or deter tourists",
      "Evaluate destination-marketing strategies and campaigns"
    ],
    "key_concepts": [
      "Inbound, outbound and domestic tourist definitions",
      "Tourist arrival statistics interpretation",
      "Push and pull factors",
      "Destination branding and unique selling points",
      "Role of national marketing bodies",
      "Mega-events and their legacy"
    ],
    "assessment_objectives": [
      "Classify tourism flows correctly",
      "Interpret statistical data on tourism",
      "Evaluate the effectiveness of marketing initiatives",
      "FET Phase (Grade 10) depth: the full subject structure is introduced at Grade 10 depth; content deepens each year toward the Grade 12 examination."
    ],
    "typical_question_styles": [
      "Classify the traveller in the scenario as a domestic, regional or international tourist",
      "Study the graph of tourist arrivals and describe the trend",
      "Explain TWO factors that could explain the decline shown in the statistics",
      "Evaluate the marketing campaign's likely success in attracting the target market",
      "FET-style structured questions at Grade 10 depth"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 tourism marketing basics",
      "Basic graph interpretation"
    ],
    "common_misconceptions": [
      "Classifying a South African travelling within SADC as an international rather than regional tourist",
      "Confusing inbound tourism (foreigners arriving) with outbound tourism (residents leaving)",
      "Reading a single data point instead of describing the overall trend in statistics",
      "Believing marketing alone can overcome fundamental deterrents like safety concerns"
    ],
    "exemplar_question_stems": [
      "A tourist from a neighbouring SADC country visits Cape Town; classify this tourist and motivate your answer",
      "Describe the trend in international arrivals shown in the table and suggest TWO possible reasons for it",
      "Evaluate whether the described campaign effectively markets South Africa to young adventure travellers"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
