-- Backfill missing thumbnails on existing rows
UPDATE public.library_system_resources
SET thumbnail_url = 'https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg'
WHERE thumbnail_url IS NULL OR thumbnail_url = '' OR thumbnail_url = '/placeholder.svg';

-- Seed openstax textbooks + practice papers across all four curricula.
-- Idempotent via ON CONFLICT (none specified — duplicates skipped by manual rerun-safety).
INSERT INTO public.library_system_resources (kind, curriculum, subject, topic, title, description, pdf_url, thumbnail_url, grade_levels)
SELECT v.kind, v.curriculum, v.subject, NULL::text, v.title, v.description, v.pdf_url, v.thumbnail_url, v.grade_levels
FROM (VALUES
  ('textbook','CAPS','Mathematics','Algebra and Trigonometry 2e (CAPS)','OpenStax open textbook — Algebra & Trigonometry.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Grade 11','Grade 12','Form 5','Form 6','A-Level','AS Level','IGCSE']),
  ('textbook','ZIMSEC','Mathematics','Algebra and Trigonometry 2e (ZIMSEC)','OpenStax open textbook — Algebra & Trigonometry.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Form 5','Form 6','A-Level']),
  ('textbook','Cambridge','Mathematics','Algebra and Trigonometry 2e (Cambridge)','OpenStax open textbook — Algebra & Trigonometry.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),
  ('textbook','IEB','Mathematics','Algebra and Trigonometry 2e (IEB)','OpenStax open textbook — Algebra & Trigonometry.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Mathematics','College Algebra 2e (CAPS)','OpenStax College Algebra.','https://assets.openstax.org/oscms-prodcms/media/documents/college-algebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_algebra_2e_web_card.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('textbook','ZIMSEC','Mathematics','College Algebra 2e (ZIMSEC)','OpenStax College Algebra.','https://assets.openstax.org/oscms-prodcms/media/documents/college-algebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_algebra_2e_web_card.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('textbook','Cambridge','Mathematics','College Algebra 2e (Cambridge)','OpenStax College Algebra.','https://assets.openstax.org/oscms-prodcms/media/documents/college-algebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_algebra_2e_web_card.svg',ARRAY['IGCSE','O-Level','AS Level']),
  ('textbook','IEB','Mathematics','College Algebra 2e (IEB)','OpenStax College Algebra.','https://assets.openstax.org/oscms-prodcms/media/documents/college-algebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_algebra_2e_web_card.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Mathematics','Prealgebra 2e (CAPS)','OpenStax Prealgebra.','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra_2e_web_card.svg',ARRAY['Grade 7','Grade 8','Grade 9']),
  ('textbook','ZIMSEC','Mathematics','Prealgebra 2e (ZIMSEC)','OpenStax Prealgebra.','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra_2e_web_card.svg',ARRAY['Form 1','Form 2','Form 3']),
  ('textbook','Cambridge','Mathematics','Prealgebra 2e (Cambridge)','OpenStax Prealgebra.','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/prealgebra_2e_web_card.svg',ARRAY['Grade 7','Grade 8','Grade 9']),

  ('textbook','CAPS','Mathematics','Calculus Volume 1 (CAPS)','OpenStax Calculus Vol 1.','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-1_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-v1.svg',ARRAY['Grade 12','Form 6','A-Level']),
  ('textbook','Cambridge','Mathematics','Calculus Volume 1 (Cambridge)','OpenStax Calculus Vol 1.','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-1_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-v1.svg',ARRAY['A-Level','AS Level']),
  ('textbook','ZIMSEC','Mathematics','Calculus Volume 1 (ZIMSEC)','OpenStax Calculus Vol 1.','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-volume-1_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/calculus-v1.svg',ARRAY['Form 6','A-Level']),

  ('textbook','CAPS','Statistics','Introductory Statistics 2e (CAPS)','OpenStax Statistics.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['Grade 11','Grade 12']),
  ('textbook','Cambridge','Statistics','Introductory Statistics 2e (Cambridge)','OpenStax Statistics.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['AS Level','A-Level','IGCSE']),
  ('textbook','ZIMSEC','Statistics','Introductory Statistics 2e (ZIMSEC)','OpenStax Statistics.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['Form 5','Form 6']),

  ('textbook','CAPS','Biology','Biology 2e (CAPS)','OpenStax Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('textbook','ZIMSEC','Biology','Biology 2e (ZIMSEC)','OpenStax Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('textbook','Cambridge','Biology','Biology 2e (Cambridge)','OpenStax Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),
  ('textbook','IEB','Biology','Biology 2e (IEB)','OpenStax Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Biology','Concepts of Biology (CAPS)','OpenStax Concepts of Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsofBiology-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/concpets_biology_eZrc8yQ.svg',ARRAY['Grade 9','Grade 10']),
  ('textbook','ZIMSEC','Biology','Concepts of Biology (ZIMSEC)','OpenStax Concepts of Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsofBiology-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/concpets_biology_eZrc8yQ.svg',ARRAY['Form 3','Form 4']),
  ('textbook','Cambridge','Biology','Concepts of Biology (Cambridge)','OpenStax Concepts of Biology.','https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsofBiology-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/concpets_biology_eZrc8yQ.svg',ARRAY['IGCSE','O-Level']),

  ('textbook','CAPS','Chemistry','Chemistry 2e (CAPS)','OpenStax Chemistry.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('textbook','ZIMSEC','Chemistry','Chemistry 2e (ZIMSEC)','OpenStax Chemistry.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('textbook','Cambridge','Chemistry','Chemistry 2e (Cambridge)','OpenStax Chemistry.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),
  ('textbook','IEB','Chemistry','Chemistry 2e (IEB)','OpenStax Chemistry.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Physics','College Physics 2e (CAPS)','OpenStax College Physics.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('textbook','ZIMSEC','Physics','College Physics 2e (ZIMSEC)','OpenStax College Physics.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('textbook','Cambridge','Physics','College Physics 2e (Cambridge)','OpenStax College Physics.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),
  ('textbook','IEB','Physics','College Physics 2e (IEB)','OpenStax College Physics.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Physics','Astronomy 2e (CAPS)','OpenStax Astronomy.','https://assets.openstax.org/oscms-prodcms/media/documents/astronomy-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/astronomy_2e_webcard.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('textbook','Cambridge','Physics','Astronomy 2e (Cambridge)','OpenStax Astronomy.','https://assets.openstax.org/oscms-prodcms/media/documents/astronomy-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/astronomy_2e_webcard.svg',ARRAY['IGCSE','O-Level','AS Level']),

  ('textbook','CAPS','Economics','Principles of Economics 3e (CAPS)','OpenStax Economics.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['Grade 11','Grade 12']),
  ('textbook','ZIMSEC','Economics','Principles of Economics 3e (ZIMSEC)','OpenStax Economics.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['Form 5','Form 6']),
  ('textbook','Cambridge','Economics','Principles of Economics 3e (Cambridge)','OpenStax Economics.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['AS Level','A-Level','IGCSE','O-Level']),

  ('textbook','CAPS','History','World History Volume 1 (CAPS)','OpenStax World History to 1500.','https://assets.openstax.org/oscms-prodcms/media/documents/world-history-volume-1-to-1500_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/world_history_volume_1_to_1500_web_card.svg',ARRAY['Grade 9','Grade 10','Grade 11']),
  ('textbook','Cambridge','History','World History Volume 1 (Cambridge)','OpenStax World History to 1500.','https://assets.openstax.org/oscms-prodcms/media/documents/world-history-volume-1-to-1500_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/world_history_volume_1_to_1500_web_card.svg',ARRAY['IGCSE','O-Level']),
  ('textbook','ZIMSEC','History','World History Volume 1 (ZIMSEC)','OpenStax World History to 1500.','https://assets.openstax.org/oscms-prodcms/media/documents/world-history-volume-1-to-1500_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/world_history_volume_1_to_1500_web_card.svg',ARRAY['Form 3','Form 4']),

  ('textbook','CAPS','English','Writing Guide with Handbook (CAPS)','OpenStax Writing Guide.','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Writing_Guide_with_Handbook.svg',ARRAY['Grade 9','Grade 10','Grade 11','Grade 12']),
  ('textbook','ZIMSEC','English','Writing Guide with Handbook (ZIMSEC)','OpenStax Writing Guide.','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Writing_Guide_with_Handbook.svg',ARRAY['Form 3','Form 4','Form 5','Form 6']),
  ('textbook','Cambridge','English','Writing Guide with Handbook (Cambridge)','OpenStax Writing Guide.','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Writing_Guide_with_Handbook.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),
  ('textbook','IEB','English','Writing Guide with Handbook (IEB)','OpenStax Writing Guide.','https://assets.openstax.org/oscms-prodcms/media/documents/writing-guide-with-handbook_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Writing_Guide_with_Handbook.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('textbook','CAPS','Psychology','Psychology 2e (CAPS)','OpenStax Psychology.','https://assets.openstax.org/oscms-prodcms/media/documents/psychology-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Psych2e_webcard.svg',ARRAY['Grade 11','Grade 12']),
  ('textbook','Cambridge','Psychology','Psychology 2e (Cambridge)','OpenStax Psychology.','https://assets.openstax.org/oscms-prodcms/media/documents/psychology-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Psych2e_webcard.svg',ARRAY['AS Level','A-Level']),

  -- Past papers / practice question banks
  ('past_paper','Cambridge','Biology','IGCSE Biology 0610 — Past Paper Question Bank','Compiled past paper questions for Cambridge IGCSE Biology 0610.','https://archive.org/download/cambridge-igcse-biology-0610-past-paper-questions-and-pdfdrive/Cambridge%20IGCSE%20Biology%20%280610%29%20Past%20paper%20questions%20and%20%28%20PDFDrive%20%29.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['IGCSE','O-Level','Grade 10','Grade 11','Form 4','Form 5']),
  ('past_paper','Cambridge','Computer Science','IGCSE Computer Science Paper 1 Workbook','Past paper practice — Cambridge IGCSE / O-Level Computer Science Paper 1.','https://archive.org/download/IGCSEOLevelComputerP1WorkbookByInqilabPatel/IGCSE%20O%20Level%20Computer%20P%201%20Workbook%20By%20Inqilab%20Patel.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['IGCSE','O-Level','Grade 10','Grade 11','Form 4','Form 5']),
  ('past_paper','Cambridge','Computer Science','IGCSE Computer Science Paper 2 Workbook','Past paper practice — Cambridge IGCSE / O-Level Computer Science Paper 2.','https://archive.org/download/IGCSEOLevelComputerP2WorkbookByInqilabPatel/IGCSE%20O%20Level%20Computer%20P%202%20Workbook%20By%20Inqilab%20Patel.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['IGCSE','O-Level','Grade 10','Grade 11','Form 4','Form 5']),

  ('past_paper','CAPS','Mathematics','Algebra 2e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax Algebra 2e end-of-chapter questions.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('past_paper','ZIMSEC','Mathematics','Algebra 2e — Practice & Review Questions (ZIMSEC)','Exam-style practice from OpenStax Algebra 2e end-of-chapter questions.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('past_paper','IEB','Mathematics','Algebra 2e — Practice & Review Questions (IEB)','Exam-style practice from OpenStax Algebra 2e end-of-chapter questions.','https://assets.openstax.org/oscms-prodcms/media/documents/algebra-and-trigonometry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/algebra_trigonometry_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('past_paper','CAPS','Biology','Biology 2e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax Biology 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('past_paper','ZIMSEC','Biology','Biology 2e — Practice & Review Questions (ZIMSEC)','Exam-style practice from OpenStax Biology 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('past_paper','IEB','Biology','Biology 2e — Practice & Review Questions (IEB)','Exam-style practice from OpenStax Biology 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/biology_book_card_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),

  ('past_paper','CAPS','Chemistry','Chemistry 2e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax Chemistry 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('past_paper','ZIMSEC','Chemistry','Chemistry 2e — Practice & Review Questions (ZIMSEC)','Exam-style practice from OpenStax Chemistry 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('past_paper','Cambridge','Chemistry','Chemistry 2e — Practice & Review Questions (Cambridge)','Exam-style practice from OpenStax Chemistry 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/chemistry_2e_book_card.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),

  ('past_paper','CAPS','Physics','College Physics 2e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax College Physics 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['Grade 10','Grade 11','Grade 12']),
  ('past_paper','ZIMSEC','Physics','College Physics 2e — Practice & Review Questions (ZIMSEC)','Exam-style practice from OpenStax College Physics 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['Form 4','Form 5','Form 6']),
  ('past_paper','Cambridge','Physics','College Physics 2e — Practice & Review Questions (Cambridge)','Exam-style practice from OpenStax College Physics 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/college-physics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/college_physics_2e.svg',ARRAY['IGCSE','O-Level','AS Level','A-Level']),

  ('past_paper','CAPS','Statistics','Statistics 2e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax Introductory Statistics 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['Grade 11','Grade 12']),
  ('past_paper','Cambridge','Statistics','Statistics 2e — Practice & Review Questions (Cambridge)','Exam-style practice from OpenStax Introductory Statistics 2e.','https://assets.openstax.org/oscms-prodcms/media/documents/introductory-statistics-2e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/intro_statistics_2e_web_card.svg',ARRAY['AS Level','A-Level','IGCSE']),

  ('past_paper','CAPS','Economics','Economics 3e — Practice & Review Questions (CAPS)','Exam-style practice from OpenStax Principles of Economics 3e.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['Grade 11','Grade 12']),
  ('past_paper','Cambridge','Economics','Economics 3e — Practice & Review Questions (Cambridge)','Exam-style practice from OpenStax Principles of Economics 3e.','https://assets.openstax.org/oscms-prodcms/media/documents/principles-economics-3e_-_WEB.pdf','https://assets.openstax.org/oscms-prodcms/media/documents/Economics3e_webcard.svg',ARRAY['AS Level','A-Level','IGCSE','O-Level'])
) AS v(kind, curriculum, subject, title, description, pdf_url, thumbnail_url, grade_levels)
WHERE NOT EXISTS (
  SELECT 1 FROM public.library_system_resources r
  WHERE r.title = v.title AND r.curriculum = v.curriculum AND r.kind = v.kind
);