-- Verified curriculum seed: CAMB Grade 8 English as a Second Language
-- Generated by adapting the merged IGCSE template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 8 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('CAMB', 'Grade 8', 'English as a Second Language', $topics$
[
  {
    "name": "Reading: Skimming, Scanning and Detail",
    "subtopics": [
      "Scanning for specific facts",
      "Skimming for gist and main ideas",
      "Multiple matching tasks",
      "Short-answer detail questions",
      "Understanding signposting and text organisation",
      "Vocabulary in context"
    ],
    "learning_objectives": [
      "Locate specific information quickly in factual texts",
      "Identify the main idea of paragraphs and whole texts",
      "Answer detail questions concisely using appropriate words from the text",
      "Work out unfamiliar vocabulary from context"
    ],
    "key_concepts": [
      "Gist vs detail reading",
      "Keyword matching and paraphrase recognition",
      "Topic sentences",
      "Distractors in matching tasks",
      "Text types: advertisements, articles, brochures, reports"
    ],
    "assessment_objectives": [
      "Identify and retrieve facts and details",
      "Understand main ideas and organisation of texts",
      "Show understanding of vocabulary in context",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Answer the short questions using words from the advertisement",
      "Match each statement to the correct paragraph",
      "According to the article, why did the project succeed",
      "Which section mentions the cost of the activity",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 14,
    "prerequisites": [
      "Intermediate general English reading"
    ],
    "common_misconceptions": [
      "Matching identical words rather than paraphrased meaning",
      "Writing long answers when a word or phrase suffices",
      "Reading the whole text slowly instead of scanning for the target",
      "Ignoring headings and layout clues that speed up location of answers"
    ],
    "exemplar_question_stems": [
      "According to the brochure, what TWO items must visitors bring",
      "Match statements A to F with the paragraphs in which the information appears",
      "Find a word in paragraph 2 that means the same as ancient"
    ]
  },
  {
    "name": "Reading: Note-Making and Information Transfer",
    "subtopics": [
      "Making notes under given headings",
      "Selecting points relevant to each heading",
      "Brief note form vs full sentences",
      "Avoiding duplication across headings",
      "Identifying all available content points",
      "Organising details from multi-section texts"
    ],
    "learning_objectives": [
      "Extract points from a text and organise them under supplied headings",
      "Write notes concisely without unnecessary words",
      "Distinguish between similar points to avoid repetition",
      "Cover the full range of the text rather than one section"
    ],
    "key_concepts": [
      "Heading-point alignment",
      "Note form conventions",
      "Content point completeness",
      "Paraphrase vs selective lifting for notes",
      "Systematic text coverage"
    ],
    "assessment_objectives": [
      "Select and organise relevant information for a specific purpose",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Make notes about the advantages and challenges of the scheme under the headings provided",
      "Complete the notes about the animal's habitat, diet and threats",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 10,
    "prerequisites": [
      "Reading detail strand"
    ],
    "common_misconceptions": [
      "Writing full sentences where brief notes are expected",
      "Placing a correct point under the wrong heading",
      "Repeating the same point in different words under two headings",
      "Stopping after finding the minimum number of points when more improve reliability"
    ],
    "exemplar_question_stems": [
      "You are preparing a talk about the festival; make brief notes under the headings History, Activities and Food",
      "Complete the notes on the causes and effects described in the article"
    ]
  },
  {
    "name": "Writing: Summary",
    "subtopics": [
      "Summarising a section of a longer text",
      "Selecting content relevant to the summary focus",
      "Own-words paraphrase",
      "Connecting points fluently",
      "Keeping within the word limit",
      "Objective tone"
    ],
    "learning_objectives": [
      "Identify the points relevant to the stated summary focus",
      "Rephrase source ideas in own words at B1-B2 level",
      "Link points with appropriate connectives into a single paragraph",
      "Control length while preserving all key content"
    ],
    "key_concepts": [
      "Relevance filtering",
      "Paraphrase strategies: synonyms and structure change",
      "Cohesive devices",
      "Concision",
      "Third-person objective style"
    ],
    "assessment_objectives": [
      "Select relevant content for a summary",
      "Write concise, accurate, connected prose in own words",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Write a summary of the problems the town faced, using no more than the stated number of words",
      "Summarise what the article says about the benefits of the invention",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Reading strands"
    ],
    "common_misconceptions": [
      "Copying whole sentences from the text",
      "Including examples and figures that are illustration rather than content",
      "Writing separate disconnected sentences instead of linked prose",
      "Going far over the word limit and losing later points"
    ],
    "exemplar_question_stems": [
      "Write a summary of the reasons why the sport became popular, in no more than 80 words",
      "Summarise the difficulties the scientists experienced during the expedition"
    ]
  },
  {
    "name": "Writing: Emails and Informal Writing",
    "subtopics": [
      "Informal register and tone",
      "Responding to all bullet-point prompts",
      "Openings and closings for informal messages",
      "Describing experiences and giving news",
      "Inviting, suggesting, apologising and thanking",
      "Paragraphing short informal texts"
    ],
    "learning_objectives": [
      "Write informal emails covering all required prompts",
      "Use informal register features naturally and consistently",
      "Develop each prompt with relevant detail rather than one line",
      "Organise the message with clear paragraphs and suitable opening/closing"
    ],
    "key_concepts": [
      "Register markers: contractions, phrasal verbs, informal linkers",
      "Prompt coverage and development",
      "Audience awareness (friend or family)",
      "Functional language for common purposes",
      "Appropriate length control"
    ],
    "assessment_objectives": [
      "Communicate ideas appropriately for an informal audience and purpose",
      "Use accurate grammar, vocabulary and punctuation at the target level",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Write an email to a friend about an event you attended, covering the three prompts given",
      "Write an email inviting your cousin to visit, explaining what you have planned",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Core sentence grammar"
    ],
    "common_misconceptions": [
      "Using formal business phrases in a message to a friend",
      "Answering only two of the three required prompts",
      "Writing one long unparagraphed block",
      "Memorised chunks that do not fit the specific task"
    ],
    "exemplar_question_stems": [
      "You recently moved to a new town; write an email to a friend describing the move, your new home and how you feel",
      "Write an email to a friend who missed your school concert, telling them what happened and suggesting a meeting"
    ]
  },
  {
    "name": "Writing: Articles, Reports and Reviews",
    "subtopics": [
      "Semi-formal register for school magazine articles",
      "Report structure and neutral tone",
      "Giving and justifying opinions",
      "Presenting two sides of an argument",
      "Using linking devices for discursive writing",
      "Audience-appropriate style choices"
    ],
    "learning_objectives": [
      "Write discursive or opinion articles with clear structure",
      "Produce balanced reports based on stated scenarios",
      "Support opinions with reasons and examples",
      "Use a range of connectives to sequence and contrast ideas"
    ],
    "key_concepts": [
      "Introduction-body-conclusion structure",
      "Fact vs opinion signalling",
      "Discourse markers: however, furthermore, on the other hand",
      "Semi-formal register",
      "Developing rather than listing ideas"
    ],
    "assessment_objectives": [
      "Communicate ideas effectively for the given form and audience",
      "Organise extended writing coherently",
      "Use grammar and vocabulary accurately at the target level",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Write an article for the school magazine giving your views on the statement",
      "Write a report for your teacher about the school event, describing what happened and making recommendations",
      "Some people think teenagers spend too much time online; write an article giving your opinion",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Email writing strand",
      "Core grammar"
    ],
    "common_misconceptions": [
      "Writing a one-sided rant when a balanced discussion scores better",
      "Ignoring the target audience stated in the task",
      "Overusing memorised discourse markers unnaturally",
      "Failing to reach a conclusion or recommendation"
    ],
    "exemplar_question_stems": [
      "Write an article for the school magazine discussing whether homework should be limited",
      "Write a report about the sports day for the school website, including suggestions for next year"
    ]
  },
  {
    "name": "Listening Skills",
    "subtopics": [
      "Short extracts: gap-fill and short answers",
      "Understanding announcements and conversations",
      "Note completion from talks",
      "Multiple choice on longer interviews",
      "Identifying speakers' opinions and attitudes",
      "Matching speakers to statements"
    ],
    "learning_objectives": [
      "Extract specific details (times, prices, places) from short recordings",
      "Complete notes from an informative talk",
      "Identify opinion and attitude in interviews and discussions",
      "Track multiple speakers and match ideas to voices"
    ],
    "key_concepts": [
      "Prediction from question stems before listening",
      "Spelling of common answer words",
      "Distractors and self-correction by speakers",
      "Paraphrase between audio and questions",
      "Gist vs specific-information listening"
    ],
    "assessment_objectives": [
      "Identify and retrieve facts and details from spoken texts",
      "Understand ideas, opinions and attitudes of speakers",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Listen and complete the notes with one or two words in each gap",
      "Choose the correct answer for each question about the interview",
      "Match each speaker with the statement that reflects their view",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 19,
    "prerequisites": [
      "Intermediate listening exposure"
    ],
    "common_misconceptions": [
      "Writing the first number or place heard, missing the speaker's correction",
      "Exceeding the word limit in gap-fills",
      "Trying to understand every word instead of listening for the target",
      "Ignoring tone of voice when questions ask about attitude"
    ],
    "exemplar_question_stems": [
      "Listen to the announcement and write down the departure time and platform",
      "Listen to the interview with the athlete and answer the multiple-choice questions",
      "Complete the notes about the museum tour using no more than two words per gap"
    ]
  },
  {
    "name": "Speaking Skills",
    "subtopics": [
      "Warm-up conversation",
      "Discussing a topic card with prompts",
      "Developing and extending ideas",
      "Giving and justifying opinions",
      "Fluency, pronunciation and intonation",
      "Interactive communication strategies"
    ],
    "learning_objectives": [
      "Sustain a conversation on familiar and abstract topics",
      "Develop prompt ideas with reasons, examples and personal experience",
      "Use a range of structures and vocabulary in speech",
      "Employ strategies to keep the conversation flowing"
    ],
    "key_concepts": [
      "Topic development vs one-word answers",
      "Fillers and paraphrase strategies",
      "Agreeing, disagreeing and speculating language",
      "Pronunciation clarity over accent imitation",
      "Turn-taking and responding to the examiner"
    ],
    "assessment_objectives": [
      "Communicate ideas fluently and coherently in spoken interaction",
      "Use accurate structures and appropriate vocabulary in speech",
      "Cambridge Lower Secondary (Grade 8) depth: foundational treatment of this strand — core concepts and skills that progress to IGCSE demand from Grade 10."
    ],
    "typical_question_styles": [
      "Discuss the topic on the card, using the prompts to develop the conversation",
      "Prompts move from personal experience toward more abstract ideas on the theme",
      "Follow-up questions ask you to justify or speculate",
      "Short scaffolded questions with guided steps, appropriate to Grade 8"
    ],
    "exam_weight": 19,
    "prerequisites": [
      "Classroom speaking practice"
    ],
    "common_misconceptions": [
      "Memorising speeches that do not answer the actual prompts",
      "Giving minimal answers without development",
      "Believing accent matters more than clarity and communication",
      "Panicking over unknown words instead of paraphrasing"
    ],
    "exemplar_question_stems": [
      "Topic card theme: the importance of hobbies — discuss what you enjoy, why people need free-time activities, and whether schools should timetable them",
      "Follow-up: some say technology has changed friendships; what is your view?"
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
