-- Verified curriculum seed: ZIMSEC Form 3 English Language
-- Generated by adapting the merged Form 4 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Form 3 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('ZIMSEC', 'Form 3', 'English Language', $topics$
[
  {
    "name": "Reading Comprehension",
    "subtopics": [
      "Literal comprehension",
      "Inferential comprehension",
      "Vocabulary in context",
      "Writer's tone and attitude",
      "Figurative language interpretation",
      "Reference questions (pronouns and connectors)",
      "Evaluating arguments in a passage"
    ],
    "learning_objectives": [
      "Locate explicitly stated information in a passage",
      "Infer meaning, motive and attitude from textual clues",
      "Deduce the meaning of unfamiliar words from context",
      "Identify and explain figures of speech such as similes, metaphors and irony",
      "Distinguish fact from opinion in a text",
      "Answer in own words without lifting whole sentences"
    ],
    "key_concepts": [
      "Literal vs inferential meaning",
      "Context clues",
      "Tone, mood and attitude",
      "Figurative vs literal language",
      "Fact vs opinion",
      "Own-words responses"
    ],
    "assessment_objectives": [
      "Retrieve and interpret information from continuous prose",
      "Infer meaning and evaluate a writer's craft and viewpoint",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Short-answer questions on a prose passage",
      "Own-words explanation questions",
      "Vocabulary-in-context questions (choose or explain the meaning)",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 18,
    "prerequisites": [
      "Basic reading fluency",
      "Core vocabulary"
    ],
    "common_misconceptions": [
      "Lifting whole sentences from the passage instead of answering in own words",
      "Confusing what the writer says with what the writer implies",
      "Giving a dictionary meaning of a word instead of its meaning in the passage"
    ],
    "exemplar_question_stems": [
      "From paragraph 2, pick out one word which shows that the farmer was reluctant to leave his land.",
      "Explain in your own words why the narrator decided not to report the incident.",
      "What does the writer's use of the phrase 'a cage without bars' suggest about the town?",
      "Give one fact and one opinion expressed by the writer in the final paragraph."
    ]
  },
  {
    "name": "Summary Writing",
    "subtopics": [
      "Identifying relevant points",
      "Discarding examples, repetition and illustrations",
      "Paraphrasing in own words",
      "Connecting points into continuous prose",
      "Observing the word limit",
      "Content vs language marks"
    ],
    "learning_objectives": [
      "Select only material relevant to the summary instruction",
      "Rewrite points concisely in own words",
      "Combine points into a coherent paragraph using appropriate connectors",
      "Keep within the prescribed word limit without losing content points",
      "Avoid adding personal opinions or outside information"
    ],
    "key_concepts": [
      "Relevance to the rubric",
      "Concision",
      "Paraphrase",
      "Cohesion and connectors",
      "Word limit discipline"
    ],
    "assessment_objectives": [
      "Select and organise relevant content points",
      "Express points accurately and economically in own words",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Guided summary of a section of the comprehension passage with a word limit",
      "Point-based summary marked for content and language",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Reading Comprehension"
    ],
    "common_misconceptions": [
      "Copying sentences wholesale from the passage",
      "Including examples and illustrations as if they were points",
      "Believing that longer summaries earn more marks",
      "Summarising the whole passage instead of only the aspect asked for"
    ],
    "exemplar_question_stems": [
      "In not more than 120 of your own words, summarise the problems the villagers faced during the drought and the steps they took to survive.",
      "Using only material from paragraphs 3 to 6, summarise the advantages of the new irrigation scheme.",
      "List the writer's reasons for opposing the proposal, then combine them into one paragraph of continuous prose."
    ]
  },
  {
    "name": "Free Composition",
    "subtopics": [
      "Narrative essays",
      "Descriptive essays",
      "Argumentative and discursive essays",
      "Expository essays",
      "Planning and paragraphing",
      "Openings and endings",
      "Relevance to the chosen topic"
    ],
    "learning_objectives": [
      "Plan an essay with a clear introduction, body and conclusion",
      "Sustain relevance to the chosen title throughout",
      "Use varied sentence structures and precise vocabulary",
      "Develop a narrative with plot, setting and character",
      "Present balanced arguments with supporting evidence in discursive writing",
      "Use paragraphs to organise ideas logically"
    ],
    "key_concepts": [
      "Essay types and their conventions",
      "Paragraph unity",
      "Register appropriate to purpose",
      "Coherence and cohesion",
      "Audience awareness"
    ],
    "assessment_objectives": [
      "Communicate ideas accurately and appropriately for purpose and audience",
      "Organise and develop content with relevance, coherence and linguistic accuracy",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Choice of essay titles covering narrative, descriptive, argumentative and expository types",
      "Open-ended one-line titles requiring interpretation",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 20,
    "prerequisites": [
      "Grammar and Language Structures",
      "Vocabulary and Idiomatic Usage"
    ],
    "common_misconceptions": [
      "Writing a prepared essay and forcing it onto the title",
      "Believing long compositions automatically score highly",
      "Ignoring paragraphing and writing one continuous block",
      "Mixing registers, e.g. slang in a formal discursive essay"
    ],
    "exemplar_question_stems": [
      "Write a story which ends with the words: 'I never took anything for granted again.'",
      "Describe a busy market scene in your neighbourhood on a month-end Saturday.",
      "'Social media does more harm than good to teenagers.' Discuss.",
      "Write about a time when you had to make a difficult choice between loyalty and honesty."
    ]
  },
  {
    "name": "Guided Composition",
    "subtopics": [
      "Formal letters",
      "Informal letters",
      "Reports",
      "Speeches",
      "Articles for magazines or newspapers",
      "Memoranda and notices",
      "Using given notes or data"
    ],
    "learning_objectives": [
      "Use the correct format for letters, reports, speeches and articles",
      "Address all the given content points",
      "Expand given notes into full, grammatical sentences",
      "Adopt a register appropriate to the audience and purpose",
      "Organise the response logically within the required format"
    ],
    "key_concepts": [
      "Format conventions",
      "Content point coverage",
      "Register and audience",
      "Expansion of notes",
      "Purpose-driven writing"
    ],
    "assessment_objectives": [
      "Reproduce required formats accurately while covering all content points",
      "Adapt tone and register to the specified audience",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Letter, report, speech or article task with bullet-point content requirements",
      "Task based on given notes, a diagram or a short scenario",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 15,
    "prerequisites": [
      "Free Composition",
      "Registers and Functional Language"
    ],
    "common_misconceptions": [
      "Using informal letter format for a formal letter",
      "Omitting some of the given content points",
      "Copying the given notes verbatim instead of expanding them",
      "Writing a speech without any audience address or sign-off"
    ],
    "exemplar_question_stems": [
      "Your school recently held a careers day. As the secretary of the careers club, write a report to the headmaster covering the following points: ...",
      "Write a letter to the town council complaining about uncollected refuse in your suburb, suggesting at least two solutions.",
      "You have been asked to give a speech to Form 1 pupils on how to study effectively. Using the notes provided, write out your speech.",
      "Write an article for your school magazine encouraging students to take part in community service."
    ]
  },
  {
    "name": "Grammar and Language Structures",
    "subtopics": [
      "Tenses and verb forms",
      "Subject-verb agreement",
      "Direct and reported speech",
      "Active and passive voice",
      "Conditional sentences",
      "Question tags and question forms",
      "Punctuation",
      "Sentence transformation"
    ],
    "learning_objectives": [
      "Use tenses consistently and accurately in continuous writing",
      "Convert sentences between direct and reported speech",
      "Transform sentences between active and passive voice without changing meaning",
      "Construct the three main types of conditional sentences",
      "Apply punctuation marks correctly including commas, apostrophes and speech marks",
      "Rewrite sentences to a given pattern while retaining meaning"
    ],
    "key_concepts": [
      "Tense consistency",
      "Concord",
      "Speech conversion rules",
      "Voice transformation",
      "Conditionals",
      "Sentence patterns"
    ],
    "assessment_objectives": [
      "Apply grammatical rules accurately in transformation exercises",
      "Maintain grammatical accuracy in extended writing",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Sentence transformation beginning with a given word or phrase",
      "Error identification and correction",
      "Fill-in exercises testing tense, concord or prepositions",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Basic parts of speech"
    ],
    "common_misconceptions": [
      "Changing meaning when transforming a sentence",
      "Forgetting backshift of tense in reported speech",
      "Treating collective nouns as always plural",
      "Using the apostrophe for simple plurals"
    ],
    "exemplar_question_stems": [
      "Rewrite the sentence beginning with the given words, keeping the meaning the same: 'She was so tired that she could not finish the race.' Begin: 'So ...'",
      "Change the following into reported speech: 'I will visit my grandmother tomorrow,' said Rudo.",
      "Rewrite in the passive voice: 'The committee has approved the new rules.'",
      "Correct the error in the sentence: 'Neither of the boys have submitted their work.'"
    ]
  },
  {
    "name": "Vocabulary and Idiomatic Usage",
    "subtopics": [
      "Synonyms and antonyms",
      "Idioms and their meanings",
      "Phrasal verbs",
      "Commonly confused words",
      "Word formation (prefixes and suffixes)",
      "Collocations",
      "Proverbs in context"
    ],
    "learning_objectives": [
      "Choose the most precise word for a given context",
      "Use common idioms and phrasal verbs correctly in sentences",
      "Distinguish between commonly confused pairs such as 'affect' and 'effect'",
      "Form nouns, adjectives and adverbs from given root words",
      "Interpret proverbs and idioms encountered in passages"
    ],
    "key_concepts": [
      "Precision in word choice",
      "Idiomatic meaning vs literal meaning",
      "Phrasal verbs",
      "Word families",
      "Collocation"
    ],
    "assessment_objectives": [
      "Deploy a wide and precise vocabulary in context",
      "Interpret idiomatic and figurative expressions accurately",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Choose the word closest in meaning to an underlined word in the passage",
      "Use a given idiom or phrasal verb in a sentence of your own",
      "Complete sentences with the correct form of a given word",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 8,
    "prerequisites": [
      "Reading Comprehension"
    ],
    "common_misconceptions": [
      "Interpreting idioms literally",
      "Assuming synonyms are interchangeable in every context",
      "Confusing phrasal verbs that share a base verb, e.g. 'put off' vs 'put up with'"
    ],
    "exemplar_question_stems": [
      "Choose the expression closest in meaning to 'threw in the towel' as used in the passage.",
      "Use the following in a sentence of your own to bring out its meaning: 'to turn over a new leaf'.",
      "Give one word which can replace the underlined phrase without changing the meaning of the sentence.",
      "Form an adjective from the word 'benefit' and use it in a sentence."
    ]
  },
  {
    "name": "Registers and Functional Language",
    "subtopics": [
      "Formal vs informal register",
      "Language of specific fields (law, medicine, agriculture, sport)",
      "Polite requests and expressions",
      "Language functions: apologising, inviting, advising, warning",
      "Audience-appropriate address"
    ],
    "learning_objectives": [
      "Identify the register or field to which given words belong",
      "Select vocabulary appropriate to a specified audience and situation",
      "Rewrite informal expressions in formal language and vice versa",
      "Match language functions to appropriate expressions",
      "Recognise jargon and specialised terms in context"
    ],
    "key_concepts": [
      "Register",
      "Field-specific vocabulary",
      "Formality scale",
      "Language functions",
      "Appropriacy"
    ],
    "assessment_objectives": [
      "Recognise and produce language appropriate to field, audience and situation",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Identify the field or register from a list of related terms",
      "Rewrite a sentence in a more formal or informal register",
      "Match expressions to their communicative functions",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 8,
    "prerequisites": [
      "Vocabulary and Idiomatic Usage"
    ],
    "common_misconceptions": [
      "Believing formal language always means long words",
      "Mixing registers within one piece of writing",
      "Confusing the register of a word with its dictionary meaning"
    ],
    "exemplar_question_stems": [
      "The following words were used at a court hearing: 'plaintiff', 'verdict', 'bail'. State the register to which they belong.",
      "Rewrite the following in formal English suitable for a letter to a headmaster: 'Sorry I bunked class, it won't happen again.'",
      "Which of the following expressions would be most suitable when advising a friend against dropping out of school?"
    ]
  },
  {
    "name": "Oral and Listening Skills",
    "subtopics": [
      "Listening for main ideas and detail",
      "Following spoken instructions",
      "Pronunciation and stress",
      "Participating in discussion and debate",
      "Giving directions and explanations",
      "Note-taking from spoken texts"
    ],
    "learning_objectives": [
      "Extract main ideas and specific details from spoken passages",
      "Follow and reproduce multi-step spoken instructions",
      "Speak audibly with appropriate stress and intonation",
      "Contribute relevantly and courteously to discussions",
      "Take accurate notes from an oral presentation"
    ],
    "key_concepts": [
      "Active listening",
      "Main idea vs detail",
      "Intonation and stress",
      "Turn-taking",
      "Oral coherence"
    ],
    "assessment_objectives": [
      "Comprehend spoken English accurately",
      "Communicate orally with clarity and appropriacy",
      "Form 3 depth: consolidating treatment of this strand, building directly toward the O-Level examination demand reached in Form 4."
    ],
    "typical_question_styles": [
      "Listening comprehension with short-answer questions",
      "Prepared and unprepared oral presentation or reading aloud",
      "O-Level-style structured questions at reduced mark tariffs, appropriate to Form 3"
    ],
    "exam_weight": 7,
    "prerequisites": [
      "Reading Comprehension"
    ],
    "common_misconceptions": [
      "Trying to write down every word instead of noting key points",
      "Believing oral work is not assessed and therefore unimportant",
      "Reading aloud in a flat tone without attention to punctuation cues"
    ],
    "exemplar_question_stems": [
      "Listen to the announcement and state the date, venue and purpose of the meeting.",
      "After listening to the talk on road safety, list three precautions pedestrians are advised to take.",
      "Prepare a two-minute talk on a memorable school event, paying attention to clarity and organisation."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
