-- Verified curriculum seed: NSC Grade 9 Computer Applications Technology
-- Generated by adapting the merged Grade 12 template for the same subject.
-- Rationale: syllabus strands are continuous across the school phase; each
-- topic carries an explicit depth note marking the Grade 9 treatment relative
-- to the terminal examination year. Strand structure and weightings are
-- factual syllabus information; all exemplar question stems are original and
-- no exam-board text is reproduced.
INSERT INTO public.curriculum_topic_templates (curriculum, grade, subject, topics, source, verified_at)
VALUES ('NSC', 'Grade 9', 'Computer Applications Technology', $topics$
[
  {
    "name": "Systems Technologies: Hardware and Software",
    "subtopics": [
      "Information processing cycle",
      "Input, output, storage and processing devices",
      "Specifications: CPU, RAM, storage when buying a computer",
      "Types of software: system vs application, licensing",
      "Operating system functions and utilities",
      "Troubleshooting common hardware and software problems",
      "Accessibility options and green computing"
    ],
    "learning_objectives": [
      "Explain the components of the information processing cycle",
      "Interpret computer specifications in advertisements and recommend suitable configurations",
      "Distinguish system software from application software and compare licensing models",
      "Describe operating system functions including file management and security",
      "Diagnose and suggest solutions for common computer problems",
      "Discuss accessibility features and environmentally responsible computing"
    ],
    "key_concepts": [
      "Information processing cycle",
      "Hardware specifications",
      "Software categories",
      "Licensing",
      "Troubleshooting",
      "Green computing"
    ],
    "assessment_objectives": [
      "Demonstrate knowledge of hardware and software concepts",
      "Apply systems knowledge to buying and troubleshooting scenarios",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Advertisement-based questions interpreting specifications",
      "Scenario troubleshooting questions",
      "Match-the-term and short explanation questions",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Grade 11 CAT theory and practical skills"
    ],
    "common_misconceptions": [
      "Believing more storage automatically makes a computer faster",
      "Confusing RAM with hard drive capacity",
      "Assuming freeware and open-source software are identical",
      "Thinking all software problems require reinstalling the operating system"
    ],
    "exemplar_question_stems": [
      "Study the computer advertisement and state which specification determines how many programs can run smoothly at the same time.",
      "A learner's computer is running very slowly. Give TWO possible causes and a solution for each.",
      "Explain the difference between proprietary software and open-source software, giving one example of each.",
      "Recommend a suitable storage device for transferring a 6 GB video file between two computers, motivating your choice."
    ]
  },
  {
    "name": "Internet and Network Technologies",
    "subtopics": [
      "Network concepts: PAN, LAN, WAN and network advantages",
      "Wired and wireless connection technologies",
      "Internet connection options: fibre, LTE, ADSL, mobile data",
      "Internet services: browsing, email, cloud, VoIP, streaming",
      "Web addresses, URLs and hyperlinks",
      "Downloading, uploading and data usage (caps, throttling, shaping)",
      "Digital communication tools and best practice"
    ],
    "learning_objectives": [
      "Explain the advantages and disadvantages of networking computers",
      "Compare internet connection options for speed, cost and availability",
      "Describe internet services and select appropriate ones for scenarios",
      "Interpret the parts of a URL",
      "Explain data usage concepts including caps, throttling and shaping",
      "Recommend communication tools for personal and business use"
    ],
    "key_concepts": [
      "Network types",
      "Connection technologies",
      "Internet services",
      "URL structure",
      "Data management",
      "Cloud computing"
    ],
    "assessment_objectives": [
      "Demonstrate understanding of networks and internet technologies",
      "Apply networking concepts to home and small business scenarios",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Scenario questions recommending a connection option",
      "Short questions on internet services and terminology",
      "Interpret-the-URL questions",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Systems Technologies: Hardware and Software"
    ],
    "common_misconceptions": [
      "Using 'internet' and 'web' interchangeably",
      "Believing an uncapped connection is always unthrottled",
      "Confusing Wi-Fi (local wireless) with mobile data",
      "Thinking cloud storage means files are not stored anywhere physical"
    ],
    "exemplar_question_stems": [
      "A family of five streams video daily and works from home. Recommend a suitable internet connection option and motivate your answer.",
      "Break down the URL provided into its protocol, domain and path, and state what each part indicates.",
      "Explain the difference between throttling and shaping of an internet connection.",
      "State TWO advantages for a small business of storing its documents in the cloud."
    ]
  },
  {
    "name": "Information Management and the PAT Process",
    "subtopics": [
      "Formulating task definitions and questions",
      "Finding and evaluating information sources",
      "Quality criteria: authority, currency, accuracy, objectivity",
      "Questionnaires and surveys as data sources",
      "Processing data into information",
      "Referencing sources and avoiding plagiarism",
      "Presenting findings in a report"
    ],
    "learning_objectives": [
      "Formulate focused questions to guide an information task",
      "Locate information using effective search techniques",
      "Evaluate websites and sources against quality criteria",
      "Design simple questionnaires to gather data",
      "Process and analyse gathered data using appropriate tools",
      "Reference sources correctly and explain plagiarism and its consequences",
      "Structure findings into a coherent word-processed report"
    ],
    "key_concepts": [
      "Task definition",
      "Search techniques",
      "Source evaluation",
      "Data gathering",
      "Information processing",
      "Referencing"
    ],
    "assessment_objectives": [
      "Demonstrate information management skills across the task cycle",
      "Evaluate information quality and manage sources ethically",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Scenario questions on evaluating a website",
      "Questions on designing questionnaire items",
      "Questions on the stages of an information task",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Grade 11 CAT theory and practical skills"
    ],
    "common_misconceptions": [
      "Trusting the first search result without evaluation",
      "Believing citing a source permits copying it verbatim",
      "Designing leading or double-barrelled questionnaire questions",
      "Confusing data with information"
    ],
    "exemplar_question_stems": [
      "Give TWO criteria you would use to decide whether a website about nutrition is trustworthy, and explain each.",
      "Rewrite the following questionnaire question so that it no longer leads the respondent: 'Don't you agree the tuckshop is too expensive?'",
      "Explain the difference between data and information, using an example from a school survey.",
      "State TWO consequences of plagiarism for a learner submitting a research task."
    ]
  },
  {
    "name": "Word Processing Skills",
    "subtopics": [
      "Styles, headings and automatic tables of contents",
      "Page layout: sections, breaks, headers and footers",
      "Tables, columns and tab settings",
      "Mail merge with data sources",
      "Reviewing tools: track changes and comments",
      "Fields, bookmarks, hyperlinks and captions",
      "Templates and forms with controls",
      "Proofing and document properties"
    ],
    "learning_objectives": [
      "Apply and modify styles and generate automatic tables of contents",
      "Control layout using section breaks, different headers and page numbering",
      "Create and format tables and set custom tab stops",
      "Perform mail merges with conditions from spreadsheet or database sources",
      "Use track changes and comments to review documents",
      "Insert fields, captions, bookmarks and cross-references",
      "Create fill-in forms using content controls"
    ],
    "key_concepts": [
      "Styles and TOC",
      "Section breaks",
      "Tab and table formatting",
      "Mail merge",
      "Reviewing tools",
      "Fields and forms"
    ],
    "assessment_objectives": [
      "Execute advanced word processing operations accurately in practical tasks",
      "Select efficient word processing techniques for document requirements",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Practical editing tasks on a provided document",
      "Theory questions naming the feature for a described need",
      "Error-fixing tasks on broken formatting",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Information Management and the PAT Process"
    ],
    "common_misconceptions": [
      "Typing a table of contents manually instead of generating it",
      "Using repeated spaces or empty paragraphs for alignment",
      "Confusing a page break with a section break",
      "Forgetting to update fields after editing"
    ],
    "exemplar_question_stems": [
      "Insert an automatic table of contents based on the Heading 1 and Heading 2 styles at the position indicated.",
      "Change the page numbering so that the first two pages use roman numerals and the rest use ordinary numbers.",
      "Complete the mail merge so that only members owing more than R100 receive the reminder letter.",
      "Explain why the page numbers in the table of contents no longer match the document, and how to fix this."
    ]
  },
  {
    "name": "Spreadsheet Skills",
    "subtopics": [
      "Cell formatting and conditional formatting",
      "Absolute and relative references",
      "Functions: SUM, AVERAGE, MAX, MIN, COUNT family, ROUND",
      "Logical and lookup functions: IF, nested IF, VLOOKUP",
      "Text and date functions: LEFT, RIGHT, MID, CONCATENATE, TODAY",
      "Charts: selection, creation and formatting",
      "Sorting, filtering and error indicators",
      "Verifying and interpreting results"
    ],
    "learning_objectives": [
      "Construct formulas using appropriate absolute and relative referencing",
      "Apply statistical, logical, lookup, text and date functions to real data",
      "Combine functions to solve multi-step problems",
      "Create and format appropriate charts for given data",
      "Use conditional formatting to highlight values",
      "Interpret common spreadsheet errors and correct them",
      "Check results for reasonableness"
    ],
    "key_concepts": [
      "Referencing",
      "Function categories",
      "Nested functions",
      "VLOOKUP",
      "Charting",
      "Error values"
    ],
    "assessment_objectives": [
      "Build correct spreadsheet solutions in practical tasks",
      "Interpret and troubleshoot spreadsheet output",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Practical tasks completing formulas in a marked workbook",
      "Explain-the-error questions on #N/A or #VALUE!",
      "Chart creation to communicate given data",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Word Processing Skills"
    ],
    "common_misconceptions": [
      "Omitting absolute references before copying formulas",
      "Using VLOOKUP without sorting or exact-match settings appropriately",
      "Choosing chart types that misrepresent the data",
      "Typing values over formulas when results look wrong"
    ],
    "exemplar_question_stems": [
      "Use a function in cell E3 to determine the number of learners who scored above 80, and make the formula copyable down the column.",
      "Write a nested IF in column F to award 'Gold' for 80 and above, 'Silver' for 60 to 79, and 'Bronze' otherwise.",
      "Use VLOOKUP to display each item's price from the PriceList sheet, and explain the #N/A error that appears in row 12.",
      "Create a chart that best compares the monthly sales of the three branches, with a suitable title and labels."
    ]
  },
  {
    "name": "Database Skills",
    "subtopics": [
      "Tables: fields, data types, field properties",
      "Primary keys and input masks",
      "Validation rules and default values",
      "Queries: criteria, calculated fields, totals",
      "Forms: creation and controls",
      "Reports: grouping, sorting and calculations",
      "Importing data and relationships basics"
    ],
    "learning_objectives": [
      "Design tables with appropriate data types and field properties",
      "Apply validation rules, input masks and default values to improve data quality",
      "Build queries with multiple criteria, wildcards and calculated fields",
      "Create forms for user-friendly data entry",
      "Generate grouped reports with summary calculations",
      "Explain how a primary key prevents duplicate records"
    ],
    "key_concepts": [
      "Data types and properties",
      "Validation and input masks",
      "Query criteria",
      "Calculated fields",
      "Forms",
      "Grouped reports"
    ],
    "assessment_objectives": [
      "Construct database objects accurately in practical tasks",
      "Apply database features to enforce data integrity and extract information",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Practical tasks on a provided database",
      "Write-the-criteria questions",
      "Design questions on field types and validation",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 13,
    "prerequisites": [
      "Spreadsheet Skills"
    ],
    "common_misconceptions": [
      "Storing numbers used as codes (like phone numbers) as Number type",
      "Confusing validation rules with input masks",
      "Using AND when OR criteria are required across rows",
      "Placing calculations in tables instead of queries or reports"
    ],
    "exemplar_question_stems": [
      "Create a query that displays all members from Gauteng or Limpopo who joined after 2023, showing only the name and town fields.",
      "Add a validation rule to the Age field so that only values from 12 to 20 are accepted, with suitable validation text.",
      "Create a report grouped by province that shows the number of members in each province.",
      "Explain why the MembershipNumber field is a better primary key than the Surname field."
    ]
  },
  {
    "name": "HTML and Web Basics",
    "subtopics": [
      "Structure of an HTML document",
      "Tags: headings, paragraphs, breaks, horizontal rules",
      "Text formatting tags and attributes",
      "Lists: ordered and unordered",
      "Inserting images and links",
      "Simple tables in HTML",
      "Fixing broken HTML code"
    ],
    "learning_objectives": [
      "Construct a basic web page using correct HTML structure",
      "Apply heading, paragraph and formatting tags appropriately",
      "Create ordered and unordered lists",
      "Insert images with alternative text and hyperlinks to other pages",
      "Build simple tables with rows, cells and borders",
      "Identify and correct errors in given HTML code"
    ],
    "key_concepts": [
      "HTML structure",
      "Tags and attributes",
      "Lists",
      "Images and links",
      "Tables",
      "Debugging HTML"
    ],
    "assessment_objectives": [
      "Produce working HTML pages in practical tasks",
      "Diagnose and repair faulty HTML code",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Practical task completing a partially built web page",
      "Fix-the-code questions with broken tags",
      "Short questions matching tags to their functions",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Word Processing Skills"
    ],
    "common_misconceptions": [
      "Forgetting closing tags and expecting correct rendering",
      "Confusing ordered with unordered list tags",
      "Omitting quotation marks around attribute values",
      "Believing spacing in the code file controls spacing on the page"
    ],
    "exemplar_question_stems": [
      "Insert an image called logo.png at the top of the page with the alternative text 'School logo'.",
      "The numbered list on the page displays as bullets. Correct the code so that it displays as numbers.",
      "Add a link to the page contact.html with the display text 'Contact us'.",
      "Identify TWO errors in the given HTML code extract and write down the corrected code."
    ]
  },
  {
    "name": "Social Implications and e-Communication",
    "subtopics": [
      "Safe internet use: malware, phishing, pharming",
      "Protecting personal information and privacy settings",
      "Computer crimes and identity theft",
      "Netiquette and responsible social media use",
      "Impact of technology on work, health and society",
      "BYOD, telecommuting and the digital divide",
      "Ergonomics and healthy computer use"
    ],
    "learning_objectives": [
      "Identify online threats and recommend protection measures",
      "Explain how personal information is harvested and how to protect it",
      "Describe common computer crimes and their prevention",
      "Apply netiquette principles to digital communication",
      "Discuss the social effects of technology including the digital divide",
      "Explain ergonomic practices that prevent computer-related health problems"
    ],
    "key_concepts": [
      "Malware and phishing",
      "Privacy",
      "Computer crime",
      "Netiquette",
      "Digital divide",
      "Ergonomics"
    ],
    "assessment_objectives": [
      "Demonstrate awareness of safe, ethical and healthy technology use",
      "Evaluate the social impact of computing technologies",
      "Senior Phase (Grade 9) depth: developing treatment of this strand, preparing for subject specialisation in the FET phase."
    ],
    "typical_question_styles": [
      "Scenario questions identifying a threat and response",
      "Discussion questions on the digital divide",
      "Short questions on netiquette and ergonomics",
      "Structured questions of growing independence, appropriate to Grade 9"
    ],
    "exam_weight": 12,
    "prerequisites": [
      "Internet and Network Technologies"
    ],
    "common_misconceptions": [
      "Believing phishing only happens through email",
      "Assuming private social media accounts make content permanently private",
      "Thinking antivirus software prevents all forms of online crime",
      "Ignoring posture because problems are not immediate"
    ],
    "exemplar_question_stems": [
      "A learner receives an SMS claiming to be from a bank, asking them to click a link. Name this type of attack and state how the learner should respond.",
      "Discuss TWO ways in which the digital divide affects learners in rural areas.",
      "Give TWO guidelines for responsible behaviour when posting in a school WhatsApp group.",
      "Recommend TWO ergonomic adjustments for a learner who works at a computer for long periods."
    ]
  }
]
$topics$::jsonb, 'verified', now())
ON CONFLICT (curriculum, grade, subject) DO UPDATE
SET topics = EXCLUDED.topics, source = 'verified', verified_at = now(), updated_at = now()
WHERE curriculum_topic_templates.source IN ('ai', 'hybrid');
