// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uynoykcratwbcdzmsxfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bm95a2NyYXR3YmNkem1zeGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDYwMTksImV4cCI6MjA2OTYyMjAxOX0.bjshrxxGsSJNUndDl7WCvqMpN9ewEXiTVX6g5PlbXGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});